"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'florida-tenders-monitor' (local .actor/input_schema.json), generated 2026-09-18.
Regenerate with: node generate-all.js

NOTE: this targets AG2 Classic (import autogen), the AutoGen-lineage conversational-agent API.
"AutoGen" itself is in Microsoft-maintenance mode as of 2026; AG2 (ag2ai/ag2) is the actively
developed continuation. AG2 also has a newer, separate v1.0 protocol-driven surface (shipped
2026-09-11) not covered here because its docs could not be verified at generation time.
"""
import os
from typing import Annotated, Optional

import requests
from autogen import ConversableAgent, register_function, LLMConfig

APIFY_ACTOR_ID = 'afSZyXLVcgnLpucyo'  # stefano_seggio/florida-tenders-monitor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


def run_florida_tenders_monitor(
    statuses: Annotated[Optional[list[str]], 'Which advertisement statuses to walk. OPEN is small and cheap (2 pages). Add CLOSED to track awards and to receive STATUS_CHANGE events when an open solicitation closes (131 pages, fetched in parallel; only new or changed records cost anything).'] = ["OPEN"],
    types: Annotated[Optional[list[str]], 'The portal\'s 10 advertisement types. Select several to get their union. Agency Decision = intent-to-award / award notice (starts the 72-hour protest clock); Single Source = non-competitive purchase notice.'] = [],
    agencyIds: Annotated[Optional[list[str]], 'MFMP organization ids, e.g. 30000021 (FDOT), 30000023 (DCF), 30000029 (AHCA), 30000032 (DMS), 30000026 (DOH), 30000031 (FDLE), 30000018 (DOE), 30000011 (DEP), 30000015 (FDACS), 30000012 (DOC), 30000036 (FWC), 30000039 (DJJ), 30000034 (REV), 30000019 (FSDB), 30000030 (FDC), 30000020 (FDVA), 30000025 (DMA), 30000013 (DLA), 30000033 (DOAH). Every record carries its `organizationId`, so run once without this filter to discover the rest (the portal has no public agency list).'] = [],
    agencyNameContains: Annotated[Optional[str], 'Case-insensitive substring on the agency name or short name, e.g. \'Transportation\' or \'AHCA\'. Applied client-side after the listing is read (cheap - the listing is walked in full anyway).'] = None,
    titleContains: Annotated[Optional[str], 'Case-insensitive substring on the advertisement title, e.g. \'software\' or \'construction\'.'] = None,
    commodityCodes: Annotated[Optional[list[str]], 'Exact 8-digit UNSPSC codes, e.g. 83112200 (Enhanced telecommunications services), 43230000 (Software). Several codes = union. The portal matches exact codes only - a prefix such as \'43\' returns nothing.'] = [],
    adNumber: Annotated[Optional[str], 'One specific advertisement, e.g. 16672 or AD-16672 (the numeric part is used).'] = None,
    agencyAdNumberContains: Annotated[Optional[str], 'Substring on the agency\'s own reference, e.g. \'DOT-ITB-27\' or \'RFP 2526\'.'] = None,
    dateFrom: Annotated[Optional[str], 'Only advertisements first published on or after this UTC calendar day: absolute (2026-09-01) or relative (\'7 days\', \'3 months\' back from today). A one-day window (from = to) is pushed to the portal; wider windows are applied client-side on the listing. Note: amendments keep the original publish date - use delta mode to catch them.'] = None,
    dateTo: Annotated[Optional[str], 'Upper bound of the publish window (inclusive). Leave empty for \'today\'.'] = None,
    openBefore: Annotated[Optional[str], 'Server-side: only advertisements whose open date is on or before this day (absolute or relative). Useful to skip solicitations that have not started accepting responses yet.'] = None,
    closesAfter: Annotated[Optional[str], 'Server-side: only advertisements whose close date is on or after this day (absolute, or relative such as \'0 days\' for \'still open today\'). Great for \'give me only what I can still bid on\'.'] = None,
    eventTypes: Annotated[Optional[list[str]], 'NEW_LISTING = an advertisement never delivered before; UPDATED = a known advertisement whose version counter rose (addendum, Q&A, close-date extension, new document); STATUS_CHANGE = a known advertisement whose status changed (e.g. OPEN -> CLOSED; only visible if that status is in \'Statuses\').'] = ["NEW_LISTING","UPDATED","STATUS_CHANGE"],
    onlyNew: Annotated[Optional[bool], 'Remembers every advertisement it has delivered (id, version, status - per filter set, in a named key-value store) and returns only what is new, amended or status-changed since. The portal has no timestamp sort, so every listing page is re-read on each run (cheap: OPEN is 2 pages, fetched in parallel); detail is fetched only for records that will be delivered. The first run is the baseline: with a small \'Max records\' it delivers the most recently published advertisements and treats everything older as history.'] = false,
    deltaStateName: Annotated[Optional[str], 'Optional label for the memory of a monitoring task. Defaults to a fingerprint of your filters, so different schedules never interfere. Set the same name on two tasks to make them share one memory.'] = None,
    resetState: Annotated[Optional[bool], 'Forget every previously delivered advertisement for this delta state and re-baseline (the run then returns up to \'Max records\' of the most recently published advertisements).'] = false,
    maxItems: Annotated[Optional[int], 'Hard cap on delivered records (and therefore on cost: you pay per record). Newest-published first; amendments and status changes to known records always come first. In delta mode anything beyond the cap stays unseen and is delivered by the next run.'] = 100,
    fetchDetail: Annotated[Optional[bool], 'One extra request per delivered record for the description (HTML + plain text), UNSPSC commodity codes, documents with download links, response contact, response due date, last-update timestamp, linked solicitation and indicator flags. Off = listing-only summary records (cheaper \'result-summary\' price).'] = true,
    maxConcurrency: Annotated[Optional[int], 'How many listing pages / detail requests are in flight at once. Detail pages tolerate 10; the listing endpoint starts returning HTTP 429 above about 8 in flight (the Actor backs off and retries), so keep 5 for large backfills.'] = 5,
    dateRange: Annotated[Optional[str], 'Kept for tasks created with version 1: \'24h\', \'7d\' or \'30d\' are interpreted as \'Published from\'.'] = None,
) -> str:
    """Monitor Florida state-agency procurement on MyFloridaMarketPlace (MFMP VBS): ITB, RFP, ITN, RFI, RSQ, Single Source and intent-to-award notices with UNSPSC codes, contacts and documents. Server-side filters, delta mode flags new, amended and closed solicitations, normalised dates. Pay per result."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        **({"statuses": statuses} if statuses is not None else {}),
        **({"types": types} if types is not None else {}),
        **({"agencyIds": agencyIds} if agencyIds is not None else {}),
        **({"agencyNameContains": agencyNameContains} if agencyNameContains is not None else {}),
        **({"titleContains": titleContains} if titleContains is not None else {}),
        **({"commodityCodes": commodityCodes} if commodityCodes is not None else {}),
        **({"adNumber": adNumber} if adNumber is not None else {}),
        **({"agencyAdNumberContains": agencyAdNumberContains} if agencyAdNumberContains is not None else {}),
        **({"dateFrom": dateFrom} if dateFrom is not None else {}),
        **({"dateTo": dateTo} if dateTo is not None else {}),
        **({"openBefore": openBefore} if openBefore is not None else {}),
        **({"closesAfter": closesAfter} if closesAfter is not None else {}),
        **({"eventTypes": eventTypes} if eventTypes is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"deltaStateName": deltaStateName} if deltaStateName is not None else {}),
        **({"resetState": resetState} if resetState is not None else {}),
        **({"maxItems": maxItems} if maxItems is not None else {}),
        **({"fetchDetail": fetchDetail} if fetchDetail is not None else {}),
        **({"maxConcurrency": maxConcurrency} if maxConcurrency is not None else {}),
        **({"dateRange": dateRange} if dateRange is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.text


# Wire into your own agents, e.g.:
#
# with LLMConfig(api_type="openai", model="gpt-4o-mini"):
#     compliance_agent = ConversableAgent(name="compliance_agent", system_message="...")
# executor_agent = ConversableAgent(name="executor_agent", human_input_mode="NEVER")
#
# register_function(
#     run_florida_tenders_monitor,
#     caller=compliance_agent,
#     executor=executor_agent,
#     description='Monitor Florida state-agency procurement on MyFloridaMarketPlace (MFMP VBS): ITB, RFP, ITN, RFI, RSQ, Single Source and intent-to-award notices with UNSPSC codes, contacts and documents. Server-side filters, delta mode flags new, amended and closed solicitations, normalised dates. Pay per result.',
# )
