// Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
// Source: Apify actor 'florida-tenders-monitor' (local .actor/input_schema.json), generated 2026-09-18.
// Regenerate with: node generate-all.js
import { tool } from "langchain";
import * as z from "zod";

const APIFY_ACTOR_ID = "afSZyXLVcgnLpucyo"; // stefano_seggio/florida-tenders-monitor

export const floridaTendersMonitorTool = tool(
  async (input) => {
    const token = process.env.APIFY_TOKEN;
    if (!token) throw new Error("APIFY_TOKEN is not set");
    const res = await fetch(
      `https://api.apify.com/v2/acts/${APIFY_ACTOR_ID}/run-sync-get-dataset-items?token=${token}`,
      { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) },
    );
    if (!res.ok) throw new Error(`Apify run failed: ${res.status} ${res.statusText}`);
    return res.json(); // dataset items array, returned directly
  },
  {
    name: "florida-tenders-monitor",
    description: "Monitor Florida state-agency procurement on MyFloridaMarketPlace (MFMP VBS): ITB, RFP, ITN, RFI, RSQ, Single Source and intent-to-award notices with UNSPSC codes, contacts and documents. Server-side filters, delta mode flags new, amended and closed solicitations, normalised dates. Pay per result.",
    schema: z.object({
    statuses: z.array(z.string()).min(1).describe("Which advertisement statuses to walk. OPEN is small and cheap (2 pages). Add CLOSED to track awards and to receive STATUS_CHANGE events when an open solicitation closes (131 pages, fetched in parallel; only new or changed records cost anything).").default(["OPEN"]),
    types: z.array(z.string()).describe("The portal's 10 advertisement types. Select several to get their union. Agency Decision = intent-to-award / award notice (starts the 72-hour protest clock); Single Source = non-competitive purchase notice.").default([]),
    agencyIds: z.array(z.string()).describe("MFMP organization ids, e.g. 30000021 (FDOT), 30000023 (DCF), 30000029 (AHCA), 30000032 (DMS), 30000026 (DOH), 30000031 (FDLE), 30000018 (DOE), 30000011 (DEP), 30000015 (FDACS), 30000012 (DOC), 30000036 (FWC), 30000039 (DJJ), 30000034 (REV), 30000019 (FSDB), 30000030 (FDC), 30000020 (FDVA), 30000025 (DMA), 30000013 (DLA), 30000033 (DOAH). Every record carries its `organizationId`, so run once without this filter to discover the rest (the portal has no public agency list).").default([]),
    agencyNameContains: z.string().describe("Case-insensitive substring on the agency name or short name, e.g. 'Transportation' or 'AHCA'. Applied client-side after the listing is read (cheap - the listing is walked in full anyway).").optional(),
    titleContains: z.string().describe("Case-insensitive substring on the advertisement title, e.g. 'software' or 'construction'.").optional(),
    commodityCodes: z.array(z.string()).describe("Exact 8-digit UNSPSC codes, e.g. 83112200 (Enhanced telecommunications services), 43230000 (Software). Several codes = union. The portal matches exact codes only - a prefix such as '43' returns nothing.").default([]),
    adNumber: z.string().regex(new RegExp("^\\s*([A-Za-z]{2,3}-?)?\\d+\\s*$")).describe("One specific advertisement, e.g. 16672 or AD-16672 (the numeric part is used).").optional(),
    agencyAdNumberContains: z.string().describe("Substring on the agency's own reference, e.g. 'DOT-ITB-27' or 'RFP 2526'.").optional(),
    dateFrom: z.string().describe("Only advertisements first published on or after this UTC calendar day: absolute (2026-09-01) or relative ('7 days', '3 months' back from today). A one-day window (from = to) is pushed to the portal; wider windows are applied client-side on the listing. Note: amendments keep the original publish date - use delta mode to catch them.").optional(),
    dateTo: z.string().describe("Upper bound of the publish window (inclusive). Leave empty for 'today'.").optional(),
    openBefore: z.string().describe("Server-side: only advertisements whose open date is on or before this day (absolute or relative). Useful to skip solicitations that have not started accepting responses yet.").optional(),
    closesAfter: z.string().describe("Server-side: only advertisements whose close date is on or after this day (absolute, or relative such as '0 days' for 'still open today'). Great for 'give me only what I can still bid on'.").optional(),
    eventTypes: z.array(z.string()).describe("NEW_LISTING = an advertisement never delivered before; UPDATED = a known advertisement whose version counter rose (addendum, Q&A, close-date extension, new document); STATUS_CHANGE = a known advertisement whose status changed (e.g. OPEN -> CLOSED; only visible if that status is in 'Statuses').").default(["NEW_LISTING","UPDATED","STATUS_CHANGE"]),
    onlyNew: z.boolean().describe("Remembers every advertisement it has delivered (id, version, status - per filter set, in a named key-value store) and returns only what is new, amended or status-changed since. The portal has no timestamp sort, so every listing page is re-read on each run (cheap: OPEN is 2 pages, fetched in parallel); detail is fetched only for records that will be delivered. The first run is the baseline: with a small 'Max records' it delivers the most recently published advertisements and treats everything older as history.").default(false),
    deltaStateName: z.string().regex(new RegExp("^[A-Za-z0-9-]{1,30}$")).describe("Optional label for the memory of a monitoring task. Defaults to a fingerprint of your filters, so different schedules never interfere. Set the same name on two tasks to make them share one memory.").optional(),
    resetState: z.boolean().describe("Forget every previously delivered advertisement for this delta state and re-baseline (the run then returns up to 'Max records' of the most recently published advertisements).").default(false),
    maxItems: z.number().int().min(1).describe("Hard cap on delivered records (and therefore on cost: you pay per record). Newest-published first; amendments and status changes to known records always come first. In delta mode anything beyond the cap stays unseen and is delivered by the next run.").default(100),
    fetchDetail: z.boolean().describe("One extra request per delivered record for the description (HTML + plain text), UNSPSC commodity codes, documents with download links, response contact, response due date, last-update timestamp, linked solicitation and indicator flags. Off = listing-only summary records (cheaper 'result-summary' price).").default(true),
    maxConcurrency: z.number().int().min(1).describe("How many listing pages / detail requests are in flight at once. Detail pages tolerate 10; the listing endpoint starts returning HTTP 429 above about 8 in flight (the Actor backs off and retries), so keep 5 for large backfills.").default(5),
    dateRange: z.string().regex(new RegExp("^(24h|7d|30d)$")).describe("Kept for tasks created with version 1: '24h', '7d' or '30d' are interpreted as 'Published from'.").optional(),
    }),
  },
);
