"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'actor-21-patent-ip-enforcement-monitor' (local .actor/input_schema.json), generated 2026-09-18.
Regenerate with: node generate-all.js

NOTE: this targets AG2 Classic (import autogen), the AutoGen-lineage conversational-agent API.
"AutoGen" itself is in Microsoft-maintenance mode as of 2026; AG2 (ag2ai/ag2) is the actively
developed continuation. AG2 also has a newer, separate v1.0 protocol-driven surface (shipped
2026-09-11) not covered here because its docs could not be verified at generation time.
"""
import os
from typing import Annotated, Optional

import requests
from autogen import ConversableAgent, register_function, LLMConfig

APIFY_ACTOR_ID = 'fTvz8lwj3F1FrPQfM'  # stefano_seggio/actor-21-patent-ip-enforcement-monitor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


def run_actor_21_patent_ip_enforcement_monitor(
    sources: Annotated[Optional[list[str]], 'uspto_ptab = real USPTO PTAB Trial proceedings (IPR/PGR/CBM/DER), newest-filed-first, via the USPTO Open Data Portal. epo_opposition = EPO Open Patent Services opposition-family legal-status watch for a caller-supplied list of EP publication numbers (epWatchlist). Both require the matching credential fields below (BYOK) -- see this actor\'s README/src/http.ts for the live-verified access requirements of each.'] = ["uspto_ptab"],
    usptoOdpApiKey: Annotated[Optional[str], 'Required when sources includes uspto_ptab. Bring-your-own-key: obtain a free key from a USPTO.gov account (MFA required) at https://data.uspto.gov/myodp -- this actor never attempts to create that account on your behalf. Never logged or persisted beyond this run.'] = None,
    epoOpsConsumerKey: Annotated[Optional[str], 'Required when sources includes epo_opposition. From a free developers.epo.org account + registered App (OAuth2 client-credentials flow). Never logged or persisted beyond this run.'] = None,
    epoOpsConsumerSecret: Annotated[Optional[str], 'Paired with epoOpsConsumerKey. Never logged or persisted beyond this run.'] = None,
    epWatchlist: Annotated[Optional[list[str]], 'Required when sources includes epo_opposition -- EPO OPS has no bulk \'recent oppositions\' search, only a per-publication-number legal-status lookup, so this actor is watchlist-driven for that source. Example: "EP3000000".'] = [],
    trialTypeCodes: Annotated[Optional[list[str]], 'Filters uspto_ptab results by trialMetaData.trialTypeCode. Leave empty for all four: Inter Partes Review (IPR), Post-Grant Review (PGR), Covered Business Method (CBM), Derivation (DER).'] = [],
    dateRange: Annotated[Optional[str], 'Optionally restricts uspto_ptab results to proceedings whose petitionFilingDate falls within this window (applied server-side as an ODP rangeFilter). Does not affect epo_opposition, which is watchlist-driven.'] = None,
    maxItemsPerSource: Annotated[Optional[int], 'Hard cap on how many records to return per selected source this run (applied independently to uspto_ptab and epo_opposition).'] = 100,
    onlyNew: Annotated[Optional[bool], 'When enabled, persists seen record ids and a status fingerprint between runs (in this actor\'s own key-value store) and skips records whose status is unchanged since the prior run. A first-seen record is emitted as event_type SANCTION; a previously-seen record whose status/decision fields changed is emitted as UPDATED; a uspto_ptab record whose terminationDate newly became set since it was last seen is emitted as the more specific TERMINATED instead. Recommended for recurring monitoring.'] = false,
) -> str:
    """Tracks USPTO PTAB patent-dispute proceedings (IPR/PGR/CBM/Derivation), plus an optional EPO opposition-watch module for a caller-supplied EP watchlist. Both sources are BYOK via free registration; delta mode flags new, updated, and concluded proceedings. PatentsView/WIPO out of scope."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        **({"sources": sources} if sources is not None else {}),
        **({"usptoOdpApiKey": usptoOdpApiKey} if usptoOdpApiKey is not None else {}),
        **({"epoOpsConsumerKey": epoOpsConsumerKey} if epoOpsConsumerKey is not None else {}),
        **({"epoOpsConsumerSecret": epoOpsConsumerSecret} if epoOpsConsumerSecret is not None else {}),
        **({"epWatchlist": epWatchlist} if epWatchlist is not None else {}),
        **({"trialTypeCodes": trialTypeCodes} if trialTypeCodes is not None else {}),
        **({"dateRange": dateRange} if dateRange is not None else {}),
        **({"maxItemsPerSource": maxItemsPerSource} if maxItemsPerSource is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.text


# Wire into your own agents, e.g.:
#
# with LLMConfig(api_type="openai", model="gpt-4o-mini"):
#     compliance_agent = ConversableAgent(name="compliance_agent", system_message="...")
# executor_agent = ConversableAgent(name="executor_agent", human_input_mode="NEVER")
#
# register_function(
#     run_actor_21_patent_ip_enforcement_monitor,
#     caller=compliance_agent,
#     executor=executor_agent,
#     description='Tracks USPTO PTAB patent-dispute proceedings (IPR/PGR/CBM/Derivation), plus an optional EPO opposition-watch module for a caller-supplied EP watchlist. Both sources are BYOK via free registration; delta mode flags new, updated, and concluded proceedings. PatentsView/WIPO out of scope.',
# )
