// Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
// Source: Apify actor 'actor-21-patent-ip-enforcement-monitor' (local .actor/input_schema.json), generated 2026-09-18.
// Regenerate with: node generate-all.js
import { tool } from "langchain";
import * as z from "zod";

const APIFY_ACTOR_ID = "fTvz8lwj3F1FrPQfM"; // stefano_seggio/actor-21-patent-ip-enforcement-monitor

export const actor21PatentIpEnforcementMonitorTool = tool(
  async (input) => {
    const token = process.env.APIFY_TOKEN;
    if (!token) throw new Error("APIFY_TOKEN is not set");
    const res = await fetch(
      `https://api.apify.com/v2/acts/${APIFY_ACTOR_ID}/run-sync-get-dataset-items?token=${token}`,
      { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) },
    );
    if (!res.ok) throw new Error(`Apify run failed: ${res.status} ${res.statusText}`);
    return res.json(); // dataset items array, returned directly
  },
  {
    name: "actor-21-patent-ip-enforcement-monitor",
    description: "Tracks USPTO PTAB patent-dispute proceedings (IPR/PGR/CBM/Derivation), plus an optional EPO opposition-watch module for a caller-supplied EP watchlist. Both sources are BYOK via free registration; delta mode flags new, updated, and concluded proceedings. PatentsView/WIPO out of scope.",
    schema: z.object({
    sources: z.array(z.string()).min(1).describe("uspto_ptab = real USPTO PTAB Trial proceedings (IPR/PGR/CBM/DER), newest-filed-first, via the USPTO Open Data Portal. epo_opposition = EPO Open Patent Services opposition-family legal-status watch for a caller-supplied list of EP publication numbers (epWatchlist). Both require the matching credential fields below (BYOK) -- see this actor's README/src/http.ts for the live-verified access requirements of each.").default(["uspto_ptab"]),
    usptoOdpApiKey: z.string().describe("Required when sources includes uspto_ptab. Bring-your-own-key: obtain a free key from a USPTO.gov account (MFA required) at https://data.uspto.gov/myodp -- this actor never attempts to create that account on your behalf. Never logged or persisted beyond this run.").optional(),
    epoOpsConsumerKey: z.string().describe("Required when sources includes epo_opposition. From a free developers.epo.org account + registered App (OAuth2 client-credentials flow). Never logged or persisted beyond this run.").optional(),
    epoOpsConsumerSecret: z.string().describe("Paired with epoOpsConsumerKey. Never logged or persisted beyond this run.").optional(),
    epWatchlist: z.array(z.string()).describe("Required when sources includes epo_opposition -- EPO OPS has no bulk 'recent oppositions' search, only a per-publication-number legal-status lookup, so this actor is watchlist-driven for that source. Example: \"EP3000000\".").default([]),
    trialTypeCodes: z.array(z.string()).describe("Filters uspto_ptab results by trialMetaData.trialTypeCode. Leave empty for all four: Inter Partes Review (IPR), Post-Grant Review (PGR), Covered Business Method (CBM), Derivation (DER).").default([]),
    dateRange: z.enum(["24h", "7d", "30d", "90d"]).describe("Optionally restricts uspto_ptab results to proceedings whose petitionFilingDate falls within this window (applied server-side as an ODP rangeFilter). Does not affect epo_opposition, which is watchlist-driven.").optional(),
    maxItemsPerSource: z.number().int().min(1).describe("Hard cap on how many records to return per selected source this run (applied independently to uspto_ptab and epo_opposition).").default(100),
    onlyNew: z.boolean().describe("When enabled, persists seen record ids and a status fingerprint between runs (in this actor's own key-value store) and skips records whose status is unchanged since the prior run. A first-seen record is emitted as event_type SANCTION; a previously-seen record whose status/decision fields changed is emitted as UPDATED; a uspto_ptab record whose terminationDate newly became set since it was last seen is emitted as the more specific TERMINATED instead. Recommended for recurring monitoring.").default(false),
    }),
  },
);
