"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'actor-22-drug-safety-recalls-monitor' (local .actor/input_schema.json), generated 2026-09-18.
Regenerate with: node generate-all.js
"""
import os
from typing import Optional, Type

import requests
from crewai.tools import BaseTool
from pydantic import BaseModel, Field

APIFY_ACTOR_ID = 'HJZvKxFUpZop6gIQ3'  # stefano_seggio/actor-22-drug-safety-recalls-monitor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


class Actor22DrugSafetyRecallsMonitorInput(BaseModel):
    """Mirrors actor-22-drug-safety-recalls-monitor's real .actor/input_schema.json field-for-field."""

    sources: Optional[list[str]] = Field(default=["fda","ema"], min_length=1, description='FDA = US openFDA drug enforcement (recall) API. EMA = EU Direct Healthcare Professional Communications (DHPC) safety-alert JSON export. Both are independent regulator-native feeds with different fields, combined into one Unified Master Schema stream.')
    maxItemsPerSource: Optional[int] = Field(default=100, ge=1, description='Hard cap on how many records to return per selected regulator this run, applied independently to FDA and EMA, both sorted newest-first. openFDA\'s own API caps a single request at 1000 results (verified live 2026-09-07); values above 1000 are paginated automatically via skip.')
    onlyNew: Optional[bool] = Field(default=False, description='When enabled, persists a content fingerprint per record between runs (in this actor\'s own named key-value store) and returns only records that are new since the last run OR whose status (FDA status / EMA regulatory_outcome) or other tracked fields changed since they were last seen - records that are byte-for-byte identical to last time are skipped. Recommended for recurring monitoring, so a status change on an already-known recall (e.g. Ongoing -> Terminated) is still surfaced, not silently suppressed just because the recall itself isn\'t brand new. Leave off for a full one-off extraction of every currently-visible record.')
    dateRange: Optional[str] = Field(default=None, description='Optionally restrict results to records whose own date field (FDA report_date; EMA dissemination_date) falls within this window. Independent of onlyNew.')
    fdaClassification: Optional[list[str]] = Field(default=None, description='Restrict FDA results to one or more FDA recall classification tiers (Class I = most severe / reasonable probability of serious harm or death, down to Class III = least severe). Ignored for EMA records, which use their own dhpc_type taxonomy instead (no equivalent tiering in the DHPC feed).')
    fdaApiKey: Optional[str] = Field(default=None, description='Optional. Without a key, openFDA allows 240 requests/minute and 1,000 requests/day per IP address (verified live against https://open.fda.gov/apis/authentication/ on 2026-09-07). With a free key (open.fda.gov signup), the daily cap rises to 120,000 requests/day per key, same 240/minute. This actor\'s own request volume is trivially within the unauthenticated limit for normal use; the key is offered only for high-frequency scheduled runs.')


class Actor22DrugSafetyRecallsMonitorTool(BaseTool):
    name: str = 'actor-22-drug-safety-recalls-monitor'
    description: str = 'Combines the FDA\'s openFDA drug enforcement API and the EMA\'s DHPC safety-alert feed into one normalized 18-field schema, tagged by jurisdiction and agency, sorted newest-first, with a mandatory regulatory-data disclaimer on every record. Delta mode flags status changes across scheduled runs.'
    args_schema: Type[BaseModel] = Actor22DrugSafetyRecallsMonitorInput

    def _run(self, sources: Optional[list[str]] = None, maxItemsPerSource: Optional[int] = None, onlyNew: Optional[bool] = None, dateRange: Optional[str] = None, fdaClassification: Optional[list[str]] = None, fdaApiKey: Optional[str] = None) -> str:
        token = os.environ["APIFY_TOKEN"]
        payload = {
            **({"sources": sources} if sources is not None else {}),
            **({"maxItemsPerSource": maxItemsPerSource} if maxItemsPerSource is not None else {}),
            **({"onlyNew": onlyNew} if onlyNew is not None else {}),
            **({"dateRange": dateRange} if dateRange is not None else {}),
            **({"fdaClassification": fdaClassification} if fdaClassification is not None else {}),
            **({"fdaApiKey": fdaApiKey} if fdaApiKey is not None else {}),
        }
        resp = requests.post(
            APIFY_RUN_SYNC_URL,
            params={"token": token},
            json=payload,
            timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
        )
        resp.raise_for_status()
        return resp.text  # dataset items as a JSON array string
