"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'page-metadata-extractor' (live Apify API), generated 2026-09-18.
Regenerate with: node generate-all.js

NOTE: this targets AG2 Classic (import autogen), the AutoGen-lineage conversational-agent API.
"AutoGen" itself is in Microsoft-maintenance mode as of 2026; AG2 (ag2ai/ag2) is the actively
developed continuation. AG2 also has a newer, separate v1.0 protocol-driven surface (shipped
2026-09-11) not covered here because its docs could not be verified at generation time.
"""
import os
from typing import Annotated, Optional

import requests
from autogen import ConversableAgent, register_function, LLMConfig

APIFY_ACTOR_ID = 'U9fUBHDngX6IyjzzF'  # stefano_seggio/page-metadata-extractor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


def run_page_metadata_extractor(
    startUrls: Annotated[Optional[list[str]], 'URLs to start crawling from. At least one is required - the Actor charges an actor-start event just for running, so an empty list would bill the caller for zero output.'] = None,
    maxRequestsPerCrawl: Annotated[Optional[int], 'Hard limit on how many pages this run will fetch, across start URLs, discovered same-site links and pagination.'] = 100,
    paginationSelector: Annotated[Optional[str], 'Optional CSS selector for a next-page link, e.g. a[rel=next] or .pagination .next. When set, the crawler follows it up to Max pagination depth pages per start URL, on top of normal same-site link discovery.'] = None,
    maxPaginationDepth: Annotated[Optional[int], 'Maximum number of paginated pages to follow per start URL when Pagination selector is set. Ignored otherwise.'] = 3,
    onlyChanged: Annotated[Optional[bool], 'When enabled, a page is still crawled (its links are still followed) but is only added to the dataset - and charged - if it\'s the first time this exact URL has been scraped, or its extracted metadata differs from the last time this Actor scraped it. Pages with unchanged metadata are skipped. Useful for scheduled re-runs where you only want to pay for what\'s new or different since the last run.'] = false,
) -> str:
    """Extract clean, structured metadata from any site: title, meta description, canonical URL, Open Graph tags, H1 and word count. Built-in retries, session rotation and optional pagination keep every crawl resilient. Built for SEO audits and LLM/RAG pipelines - pay only per result, never per wasted run."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        **({"startUrls": startUrls} if startUrls is not None else {}),
        **({"maxRequestsPerCrawl": maxRequestsPerCrawl} if maxRequestsPerCrawl is not None else {}),
        **({"paginationSelector": paginationSelector} if paginationSelector is not None else {}),
        **({"maxPaginationDepth": maxPaginationDepth} if maxPaginationDepth is not None else {}),
        **({"onlyChanged": onlyChanged} if onlyChanged is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.text


# Wire into your own agents, e.g.:
#
# with LLMConfig(api_type="openai", model="gpt-4o-mini"):
#     compliance_agent = ConversableAgent(name="compliance_agent", system_message="...")
# executor_agent = ConversableAgent(name="executor_agent", human_input_mode="NEVER")
#
# register_function(
#     run_page_metadata_extractor,
#     caller=compliance_agent,
#     executor=executor_agent,
#     description='Extract clean, structured metadata from any site: title, meta description, canonical URL, Open Graph tags, H1 and word count. Built-in retries, session rotation and optional pagination keep every crawl resilient. Built for SEO audits and LLM/RAG pipelines - pay only per result, never per wasted run.',
# )
