// Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
// Source: Apify actor 'page-metadata-extractor' (live Apify API), generated 2026-09-18.
// Regenerate with: node generate-all.js
import { tool } from "langchain";
import * as z from "zod";

const APIFY_ACTOR_ID = "U9fUBHDngX6IyjzzF"; // stefano_seggio/page-metadata-extractor

export const pageMetadataExtractorTool = tool(
  async (input) => {
    const token = process.env.APIFY_TOKEN;
    if (!token) throw new Error("APIFY_TOKEN is not set");
    const res = await fetch(
      `https://api.apify.com/v2/acts/${APIFY_ACTOR_ID}/run-sync-get-dataset-items?token=${token}`,
      { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) },
    );
    if (!res.ok) throw new Error(`Apify run failed: ${res.status} ${res.statusText}`);
    return res.json(); // dataset items array, returned directly
  },
  {
    name: "page-metadata-extractor",
    description: "Extract clean, structured metadata from any site: title, meta description, canonical URL, Open Graph tags, H1 and word count. Built-in retries, session rotation and optional pagination keep every crawl resilient. Built for SEO audits and LLM/RAG pipelines - pay only per result, never per wasted run.",
    schema: z.object({
    startUrls: z.array(z.string()).min(1).describe("URLs to start crawling from. At least one is required - the Actor charges an actor-start event just for running, so an empty list would bill the caller for zero output.").optional(),
    maxRequestsPerCrawl: z.number().int().min(1).describe("Hard limit on how many pages this run will fetch, across start URLs, discovered same-site links and pagination.").default(100),
    paginationSelector: z.string().describe("Optional CSS selector for a next-page link, e.g. a[rel=next] or .pagination .next. When set, the crawler follows it up to Max pagination depth pages per start URL, on top of normal same-site link discovery.").optional(),
    maxPaginationDepth: z.number().int().min(0).describe("Maximum number of paginated pages to follow per start URL when Pagination selector is set. Ignored otherwise.").default(3),
    onlyChanged: z.boolean().describe("When enabled, a page is still crawled (its links are still followed) but is only added to the dataset - and charged - if it's the first time this exact URL has been scraped, or its extracted metadata differs from the last time this Actor scraped it. Pages with unchanged metadata are skipped. Useful for scheduled re-runs where you only want to pay for what's new or different since the last run.").default(false),
    }),
  },
);
