"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'santafe-compras-monitor' (local .actor/input_schema.json), generated 2026-09-18.
Regenerate with: node generate-all.js

NOTE: this targets AG2 Classic (import autogen), the AutoGen-lineage conversational-agent API.
"AutoGen" itself is in Microsoft-maintenance mode as of 2026; AG2 (ag2ai/ag2) is the actively
developed continuation. AG2 also has a newer, separate v1.0 protocol-driven surface (shipped
2026-09-11) not covered here because its docs could not be verified at generation time.
"""
import os
from typing import Annotated, Optional

import requests
from autogen import ConversableAgent, register_function, LLMConfig

APIFY_ACTOR_ID = 'jfoq1flE7KqKb3qAb'  # stefano_seggio/santafe-compras-monitor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


def run_santafe_compras_monitor(
    estados: Annotated[Optional[list[str]], 'Which lists to read. AP = Para Apertura (published, offers not yet opened - where every new tender appears first), ET = En Trámite (opened, being evaluated - actas and preadjudicación land here), CO = Concluida (finished). Each is a separate server-side query.'] = ["AP"],
    anio: Annotated[Optional[int], 'Year of the process number (anioGestion). The site\'s own UI always applies the current year; leave empty for all years (2000 onwards).'] = None,
    objeto: Annotated[Optional[str], 'Case-insensitive phrase search over the tender subject, e.g. \'limpieza\', \'medicamentos\', \'servicio de vigilancia\'. Word order matters (\'servicio de limpieza\' matches, \'limpieza servicio\' does not).'] = None,
    tipoGestion: Annotated[Optional[list[str]], 'One server-side query per selected type. Codes are the site\'s own (L = Licitación Pública, P = Licitación Privada, T = Contratación Directa, ...).'] = [],
    tipoModalidad: Annotated[Optional[str], 'Contracting modality code from the site.'] = None,
    comprador: Annotated[Optional[str], 'The organism running the procedure, as its site id (idOrganismoLey12510, e.g. 27) or a distinctive part of its name (e.g. \'Administración Provincial de Impuestos\', \'Hospital Cullen\'). Names are matched against the site\'s own organism list at run start; an ambiguous name fails with the candidates listed.'] = None,
    solicitante: Annotated[Optional[str], 'The organism the purchase is for, same id space and name matching as \'Buyer\' (e.g. \'Ministerio de Salud\').'] = None,
    rubro: Annotated[Optional[str], 'Product/service category, as the site\'s idEspecie (e.g. 29) or part of its name (e.g. \'medicinales\', \'limpieza\', \'alimentos\'). Matched against the site\'s 78 rubros at run start.'] = None,
    subrubro: Annotated[Optional[str], 'Sub-category within the selected rubro, as idFamilia or part of its name. Requires \'Category (rubro)\'.'] = None,
    nroGestion: Annotated[Optional[str], 'Exact process number as printed on the site, e.g. \'18\' or \'02\' (combine with the year: several organisms share the same numbering).'] = None,
    nroExpediente: Annotated[Optional[str], 'Exact, full expediente number, e.g. \'EE-2026-00001797-APPSF-OD\' (partial values match nothing on the site).'] = None,
    openingFrom: Annotated[Optional[str], 'Only tenders whose bid opening (fecha de apertura) is on or after this date. Absolute (2026-09-01) or relative: \'7 days\' counts back from today, \'+7 days\' counts forward (Santa Fe calendar). Applied client-side after fetching the listing (the site has no date filter) - rows outside the window are simply skipped and not remembered.'] = None,
    openingTo: Annotated[Optional[str], 'Only tenders opening on or before this date. Absolute or relative (\'+30 days\' = opening within the next month). Client-side.'] = None,
    eventTypes: Annotated[Optional[list[str]], 'NEW_LISTING = a process never delivered before; STATUS_CHANGE = a known process that moved to another estado (AP -> ET -> CO); UPDATED = a known open process whose detail page changed (a circular aclaratoria, an acta de apertura, a preadjudicación report, a new opening date...). The last two exist in delta mode only.'] = ["NEW_LISTING","STATUS_CHANGE","UPDATED"],
    onlyNew: Annotated[Optional[bool], 'Remembers every process it has delivered (per filter set, in a named key-value store) with the estado it was in and a fingerprint of its detail page, and returns only processes that are new, moved to another estado, or were amended since. Each estado list is walked newest-first and stops as soon as it reaches already-known records.'] = false,
    recheckWindowDays: Annotated[Optional[int], 'Delta mode with detail: known processes whose opening date is within this many days in the past (or any time in the future) get their detail page re-read every run to detect amendments (UPDATED). The register shows no \'last modified\' signal, so this re-read is the only way to see a new circular or acta. 0 disables it. Re-reads are not charged unless something changed.'] = 30,
    sortBy: Annotated[Optional[str], '\'newest\' (idGestion descending = most recently created first) is required for delta mode. \'openingSoonest\' / \'openingLatest\' order by bid-opening date; \'mostViewed\' by the site\'s own view counter (full runs only).'] = "newest",
    deltaStateName: Annotated[Optional[str], 'Optional label for the memory of a monitoring task. Defaults to a fingerprint of your filters, so different schedules never interfere. Set the same name on two tasks to make them share one memory.'] = None,
    resetState: Annotated[Optional[bool], 'Forget every previously delivered process for this delta state and re-baseline (the run then returns up to \'Max records\' newest processes).'] = false,
    maxItems: Annotated[Optional[int], 'Hard cap on delivered records (and therefore on cost: you pay per record). In delta mode anything beyond the cap is simply delivered by the next run.'] = 100,
    fetchDetail: Annotated[Optional[bool], 'Opens each process page (one extra request) for the publication timestamp, budget (Monto Original), submission deadline, places, rubros, requesting organism, contact, expediente and the pliego / circular / acta / preadjudicación document links. Off = listing-only summary records (cheaper \'result-summary\' price; no UPDATED detection and no status sweep).'] = true,
    maxConcurrency: Annotated[Optional[int], 'How many process pages are fetched at once. The site answers a page in 0.1-0.3 s and tolerated 10 in parallel without throttling; 5 is a polite default.'] = 5,
    dateRange: Annotated[Optional[str], 'Kept for tasks created with version 1: \'24h\', \'7d\' or \'30d\' are interpreted as an opening-date window of that many days before AND after today.'] = None,
) -> str:
    """Scrape and monitor every public tender of Santa Fe Province, Argentina: licitaciones, concursos and contrataciones directas of ministries, hospitals and SAMCOs, with buyer, budget, deadlines, rubros, expediente and pliego/circular/acta PDF links. Delta mode flags new, changed and amended tenders."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        **({"estados": estados} if estados is not None else {}),
        **({"anio": anio} if anio is not None else {}),
        **({"objeto": objeto} if objeto is not None else {}),
        **({"tipoGestion": tipoGestion} if tipoGestion is not None else {}),
        **({"tipoModalidad": tipoModalidad} if tipoModalidad is not None else {}),
        **({"comprador": comprador} if comprador is not None else {}),
        **({"solicitante": solicitante} if solicitante is not None else {}),
        **({"rubro": rubro} if rubro is not None else {}),
        **({"subrubro": subrubro} if subrubro is not None else {}),
        **({"nroGestion": nroGestion} if nroGestion is not None else {}),
        **({"nroExpediente": nroExpediente} if nroExpediente is not None else {}),
        **({"openingFrom": openingFrom} if openingFrom is not None else {}),
        **({"openingTo": openingTo} if openingTo is not None else {}),
        **({"eventTypes": eventTypes} if eventTypes is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"recheckWindowDays": recheckWindowDays} if recheckWindowDays is not None else {}),
        **({"sortBy": sortBy} if sortBy is not None else {}),
        **({"deltaStateName": deltaStateName} if deltaStateName is not None else {}),
        **({"resetState": resetState} if resetState is not None else {}),
        **({"maxItems": maxItems} if maxItems is not None else {}),
        **({"fetchDetail": fetchDetail} if fetchDetail is not None else {}),
        **({"maxConcurrency": maxConcurrency} if maxConcurrency is not None else {}),
        **({"dateRange": dateRange} if dateRange is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.text


# Wire into your own agents, e.g.:
#
# with LLMConfig(api_type="openai", model="gpt-4o-mini"):
#     compliance_agent = ConversableAgent(name="compliance_agent", system_message="...")
# executor_agent = ConversableAgent(name="executor_agent", human_input_mode="NEVER")
#
# register_function(
#     run_santafe_compras_monitor,
#     caller=compliance_agent,
#     executor=executor_agent,
#     description='Scrape and monitor every public tender of Santa Fe Province, Argentina: licitaciones, concursos and contrataciones directas of ministries, hospitals and SAMCOs, with buyer, budget, deadlines, rubros, expediente and pliego/circular/acta PDF links. Delta mode flags new, changed and amended tenders.',
# )
