// Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
// Source: Apify actor 'aozora-bunko-public-domain-text-feed' (live Apify API), generated 2026-09-18.
// Regenerate with: node generate-all.js
import { tool } from "langchain";
import * as z from "zod";

const APIFY_ACTOR_ID = "K0XRDbUteacQL3jeF"; // stefano_seggio/aozora-bunko-public-domain-text-feed

export const aozoraBunkoPublicDomainTextFeedTool = tool(
  async (input) => {
    const token = process.env.APIFY_TOKEN;
    if (!token) throw new Error("APIFY_TOKEN is not set");
    const res = await fetch(
      `https://api.apify.com/v2/acts/${APIFY_ACTOR_ID}/run-sync-get-dataset-items?token=${token}`,
      { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) },
    );
    if (!res.ok) throw new Error(`Apify run failed: ${res.status} ${res.statusText}`);
    return res.json(); // dataset items array, returned directly
  },
  {
    name: "aozora-bunko-public-domain-text-feed",
    description: "Watches Aozora Bunko's own official catalog export for newly digitized or revised confirmed-public-domain Japanese texts and emits NEW_TEXT/REVISED_TEXT/STATUS_CHANGE events with full decoded text where available. Pay-per-event: billed only for what's new or changed.",
    schema: z.object({
    onlyNew: z.boolean().describe("When true (default), only NEW_TEXT, REVISED_TEXT and STATUS_CHANGE rows are pushed, each as a charged PPE event. Set to false for a free baseline run: every catalog row that passes the public-domain filter is pushed once as an uncharged SNAPSHOT_NO_DIFF record.").default(true),
    resetState: z.boolean().describe("When true, clears this feed's stored seen-work state before this run, so the next run re-baselines from scratch (every catalog row becomes a fresh, uncharged SNAPSHOT_NO_DIFF again, subject to onlyNew). Use for testing or recovering a corrupted state store, not routine operation.").default(false),
    onlyConfirmedPublicDomain: z.boolean().describe("When true (default), keeps only catalog rows where Aozora's own work-copyright flag reads なし (no copyright - confirmed public domain). When false, also includes rows flagged あり (the author/estate granted free-use permission, but the work is NOT public domain).").default(true),
    includeFullText: z.boolean().describe("When true (default), NEW_TEXT/REVISED_TEXT events download the linked text ZIP, decode it from Shift_JIS, strip Aozora's ruby/annotation markup and legend preamble, and embed both plain_text and raw_text_with_markup - delivered as the higher-priced 'result' event. When false, or when a text file fails to download/decode, the same events are delivered as metadata-only 'result-summary' records instead.").default(false),
    authorIdAllowlist: z.array(z.string()).describe("Aozora 人物ID values (e.g. \"001257\") to restrict this feed to. Leave empty to monitor the entire catalog.").default([]),
    maxItemsPerRun: z.number().int().min(0).describe("Caps the number of charged (result/result-summary) events this run will push, independent of your Apify spending limit. 0 means no Actor-side cap.").default(20),
    requestDelayMs: z.number().int().min(0).describe("Aozora Bunko is a small, volunteer-run, non-commercial mirror with no published rate limit - this default trades a slower walk for not needing to trust an unconfirmed number, and for being a polite citizen of a small server, not only a cost control.").default(500),
    maxRetries: z.number().int().min(0).describe("Retry attempts (exponential backoff with jitter) for a 429/5xx response or a network-level failure before a single catalog or text-ZIP fetch is given up on as failed.").default(5),
    requestTimeoutSecs: z.number().int().min(5).describe("Aborts a single request to Aozora Bunko (catalog export or per-work text ZIP) that takes longer than this, so one slow response never stalls the whole run.").default(30),
    deltaStateName: z.string().describe("Names the Key-Value Store this feed's seen-work state is kept in. Run multiple independent schedules - e.g. filtered to different author allowlists - without them draining each other's baseline by giving each a distinct name here.").default("default"),
    }),
  },
);
