"""langchain-delta-registry: 28 pay-per-event regulatory, sanctions, procurement, and
corporate-registry monitoring tools for LangChain agents, backed by Apify's hosted MCP gateway.

Auto-generated by lib/schema-generator/langchain-package-generator.ts — do not hand-edit.
"""
from .actor_18_b2b_lead_magnet import actor_18_b2b_lead_magnet_tool
from .actor_19_maritime_sanctions_monitor import actor_19_maritime_sanctions_monitor_tool
from .actor_20_mdb_procurement_monitor import actor_20_mdb_procurement_monitor_tool
from .actor_21_patent_ip_enforcement_monitor import actor_21_patent_ip_enforcement_monitor_tool
from .actor_22_drug_safety_recalls_monitor import actor_22_drug_safety_recalls_monitor_tool
from .actor_24_clinical_trials_delta_engine import actor_24_clinical_trials_delta_engine_tool
from .ai_crawler_content_signal_permission_monitor import ai_crawler_content_signal_permission_monitor_tool
from .aozora_bunko_public_domain_text_feed import aozora_bunko_public_domain_text_feed_tool
from .australia_grantconnect_monitor import australia_grantconnect_monitor_tool
from .cordoba_compras_monitor import cordoba_compras_monitor_tool
from .diario_oficial_cl_monitor import diario_oficial_cl_monitor_tool
from .emerging_market_sovereign_debt_auction_monitor import emerging_market_sovereign_debt_auction_monitor_tool
from .entrerios_compras_monitor import entrerios_compras_monitor_tool
from .eu_ted_procurement_delta_monitor import eu_ted_procurement_delta_monitor_tool
from .florida_tenders_monitor import florida_tenders_monitor_tool
from .kipris_patent_trademark_status_monitor import kipris_patent_trademark_status_monitor_tool
from .mendoza_compras_monitor import mendoza_compras_monitor_tool
from .page_metadata_extractor import page_metadata_extractor_tool
from .pba_tenders_monitor import pba_tenders_monitor_tool
from .regione_lombardia_grants_registry_monitor import regione_lombardia_grants_registry_monitor_tool
from .salta_compras_monitor import salta_compras_monitor_tool
from .santafe_compras_monitor import santafe_compras_monitor_tool
from .sec_enforcement_litigation_delta_feed import sec_enforcement_litigation_delta_feed_tool
from .singapore_acra_registry_monitor import singapore_acra_registry_monitor_tool
from .tucuman_compras_monitor import tucuman_compras_monitor_tool
from .uae_corporate_registry_monitor import uae_corporate_registry_monitor_tool
from .uk_hse_enforcement_monitor import uk_hse_enforcement_monitor_tool
from .uk_modern_slavery_statement_registry_monitor import uk_modern_slavery_statement_registry_monitor_tool

DELTA_REGISTRY_TOOLS = [
    actor_18_b2b_lead_magnet_tool,
    actor_19_maritime_sanctions_monitor_tool,
    actor_20_mdb_procurement_monitor_tool,
    actor_21_patent_ip_enforcement_monitor_tool,
    actor_22_drug_safety_recalls_monitor_tool,
    actor_24_clinical_trials_delta_engine_tool,
    ai_crawler_content_signal_permission_monitor_tool,
    aozora_bunko_public_domain_text_feed_tool,
    australia_grantconnect_monitor_tool,
    cordoba_compras_monitor_tool,
    diario_oficial_cl_monitor_tool,
    emerging_market_sovereign_debt_auction_monitor_tool,
    entrerios_compras_monitor_tool,
    eu_ted_procurement_delta_monitor_tool,
    florida_tenders_monitor_tool,
    kipris_patent_trademark_status_monitor_tool,
    mendoza_compras_monitor_tool,
    page_metadata_extractor_tool,
    pba_tenders_monitor_tool,
    regione_lombardia_grants_registry_monitor_tool,
    salta_compras_monitor_tool,
    santafe_compras_monitor_tool,
    sec_enforcement_litigation_delta_feed_tool,
    singapore_acra_registry_monitor_tool,
    tucuman_compras_monitor_tool,
    uae_corporate_registry_monitor_tool,
    uk_hse_enforcement_monitor_tool,
    uk_modern_slavery_statement_registry_monitor_tool,
]

__all__ = ["DELTA_REGISTRY_TOOLS"]
