"""Auto-generated by lib/schema-generator/langchain-package-generator.ts from
public/schemas/actor-22-drug-safety-recalls-monitor/openapi.json — do not hand-edit. Regenerate instead.
"""
from typing import Optional

from pydantic import BaseModel, Field
from langchain_core.tools import StructuredTool

from ._client import call_apify_actor

APIFY_ACTOR_ID = 'HJZvKxFUpZop6gIQ3'  # stefano_seggio/actor-22-drug-safety-recalls-monitor — immutable Apify ID,
# not the slug: the OpenAPI adapter this package's data is sourced from was itself corrected this
# session to call by ID rather than slug, after a real slug-rename incident (primer-actor ->
# page-metadata-extractor) — kept consistent here for the same reason.


class Actor22DrugSafetyRecallsMonitorInput(BaseModel):
    """Mirrors actor-22-drug-safety-recalls-monitor's real .actor/input_schema.json field-for-field."""

    sources: Optional[list[str]] = Field(default=["fda","ema"], min_length=1, description='FDA = US openFDA drug enforcement (recall) API. EMA = EU Direct Healthcare Professional Communications (DHPC) safety-alert JSON export. Both are independent regulator-native feeds with different fields, combined into one Unified Master Schema stream.')
    maxItemsPerSource: Optional[int] = Field(default=100, ge=1, description='Hard cap on how many records to return per selected regulator this run, applied independently to FDA and EMA, both sorted newest-first. openFDA\'s own API caps a single request at 1000 results (verified live 2026-09-07); values above 1000 are paginated automatically via skip.')
    onlyNew: Optional[bool] = Field(default=False, description='When enabled, persists a content fingerprint per record between runs (in this actor\'s own named key-value store) and returns only records that are new since the last run OR whose status (FDA status / EMA regulatory_outcome) or other tracked fields changed since they were last seen - records that are byte-for-byte identical to last time are skipped. Recommended for recurring monitoring, so a status change on an already-known recall (e.g. Ongoing -> Terminated) is still surfaced, not silently suppressed just because the recall itself isn\'t brand new. Leave off for a full one-off extraction of every currently-visible record.')
    dateRange: Optional[str] = Field(default=None, description='Optionally restrict results to records whose own date field (FDA report_date; EMA dissemination_date) falls within this window. Independent of onlyNew.')
    fdaClassification: Optional[list[str]] = Field(default=None, description='Restrict FDA results to one or more FDA recall classification tiers (Class I = most severe / reasonable probability of serious harm or death, down to Class III = least severe). Ignored for EMA records, which use their own dhpc_type taxonomy instead (no equivalent tiering in the DHPC feed).')
    fdaApiKey: Optional[str] = Field(default=None, description='Optional. Without a key, openFDA allows 240 requests/minute and 1,000 requests/day per IP address (verified live against https://open.fda.gov/apis/authentication/ on 2026-09-07). With a free key (open.fda.gov signup), the daily cap rises to 120,000 requests/day per key, same 240/minute. This actor\'s own request volume is trivially within the unauthenticated limit for normal use; the key is offered only for high-frequency scheduled runs.')


def _actor_22_drug_safety_recalls_monitor(sources: Optional[list[str]] = None, maxItemsPerSource: Optional[int] = None, onlyNew: Optional[bool] = None, dateRange: Optional[str] = None, fdaClassification: Optional[list[str]] = None, fdaApiKey: Optional[str] = None) -> list[dict]:
    payload = {
        **({"sources": sources} if sources is not None else {}),
        **({"maxItemsPerSource": maxItemsPerSource} if maxItemsPerSource is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"dateRange": dateRange} if dateRange is not None else {}),
        **({"fdaClassification": fdaClassification} if fdaClassification is not None else {}),
        **({"fdaApiKey": fdaApiKey} if fdaApiKey is not None else {}),
    }
    return call_apify_actor(APIFY_ACTOR_ID, payload)


actor_22_drug_safety_recalls_monitor_tool = StructuredTool.from_function(
    func=_actor_22_drug_safety_recalls_monitor,
    name='actor-22-drug-safety-recalls-monitor',
    description='Combines the FDA\'s openFDA drug enforcement API and the EMA\'s DHPC safety-alert feed into one normalized 18-field schema, tagged by jurisdiction and agency, sorted newest-first, with a mandatory regulatory-data disclaimer on every record. Delta mode flags status changes across scheduled runs.',
    args_schema=Actor22DrugSafetyRecallsMonitorInput,
)
