"""Auto-generated by lib/schema-generator/langchain-package-generator.ts from
public/schemas/actor-21-patent-ip-enforcement-monitor/openapi.json — do not hand-edit. Regenerate instead.
"""
from typing import Optional

from pydantic import BaseModel, Field
from langchain_core.tools import StructuredTool

from ._client import call_apify_actor

APIFY_ACTOR_ID = 'fTvz8lwj3F1FrPQfM'  # stefano_seggio/actor-21-patent-ip-enforcement-monitor — immutable Apify ID,
# not the slug: the OpenAPI adapter this package's data is sourced from was itself corrected this
# session to call by ID rather than slug, after a real slug-rename incident (primer-actor ->
# page-metadata-extractor) — kept consistent here for the same reason.


class Actor21PatentIpEnforcementMonitorInput(BaseModel):
    """Mirrors actor-21-patent-ip-enforcement-monitor's real .actor/input_schema.json field-for-field."""

    sources: Optional[list[str]] = Field(default=["uspto_ptab"], min_length=1, description='uspto_ptab = real USPTO PTAB Trial proceedings (IPR/PGR/CBM/DER), newest-filed-first, via the USPTO Open Data Portal. epo_opposition = EPO Open Patent Services opposition-family legal-status watch for a caller-supplied list of EP publication numbers (epWatchlist). Both require the matching credential fields below (BYOK) -- see this actor\'s README/src/http.ts for the live-verified access requirements of each.')
    usptoOdpApiKey: Optional[str] = Field(default=None, description='Required when sources includes uspto_ptab. Bring-your-own-key: obtain a free key from a USPTO.gov account (MFA required) at https://data.uspto.gov/myodp -- this actor never attempts to create that account on your behalf. Never logged or persisted beyond this run.')
    epoOpsConsumerKey: Optional[str] = Field(default=None, description='Required when sources includes epo_opposition. From a free developers.epo.org account + registered App (OAuth2 client-credentials flow). Never logged or persisted beyond this run.')
    epoOpsConsumerSecret: Optional[str] = Field(default=None, description='Paired with epoOpsConsumerKey. Never logged or persisted beyond this run.')
    epWatchlist: Optional[list[str]] = Field(default=[], description='Required when sources includes epo_opposition -- EPO OPS has no bulk \'recent oppositions\' search, only a per-publication-number legal-status lookup, so this actor is watchlist-driven for that source. Example: "EP3000000".')
    trialTypeCodes: Optional[list[str]] = Field(default=[], description='Filters uspto_ptab results by trialMetaData.trialTypeCode. Leave empty for all four: Inter Partes Review (IPR), Post-Grant Review (PGR), Covered Business Method (CBM), Derivation (DER).')
    dateRange: Optional[str] = Field(default=None, description='Optionally restricts uspto_ptab results to proceedings whose petitionFilingDate falls within this window (applied server-side as an ODP rangeFilter). Does not affect epo_opposition, which is watchlist-driven.')
    maxItemsPerSource: Optional[int] = Field(default=100, ge=1, description='Hard cap on how many records to return per selected source this run (applied independently to uspto_ptab and epo_opposition).')
    onlyNew: Optional[bool] = Field(default=False, description='When enabled, persists seen record ids and a status fingerprint between runs (in this actor\'s own key-value store) and skips records whose status is unchanged since the prior run. A first-seen record is emitted as event_type SANCTION; a previously-seen record whose status/decision fields changed is emitted as UPDATED; a uspto_ptab record whose terminationDate newly became set since it was last seen is emitted as the more specific TERMINATED instead. Recommended for recurring monitoring.')


def _actor_21_patent_ip_enforcement_monitor(sources: Optional[list[str]] = None, usptoOdpApiKey: Optional[str] = None, epoOpsConsumerKey: Optional[str] = None, epoOpsConsumerSecret: Optional[str] = None, epWatchlist: Optional[list[str]] = None, trialTypeCodes: Optional[list[str]] = None, dateRange: Optional[str] = None, maxItemsPerSource: Optional[int] = None, onlyNew: Optional[bool] = None) -> list[dict]:
    payload = {
        **({"sources": sources} if sources is not None else {}),
        **({"usptoOdpApiKey": usptoOdpApiKey} if usptoOdpApiKey is not None else {}),
        **({"epoOpsConsumerKey": epoOpsConsumerKey} if epoOpsConsumerKey is not None else {}),
        **({"epoOpsConsumerSecret": epoOpsConsumerSecret} if epoOpsConsumerSecret is not None else {}),
        **({"epWatchlist": epWatchlist} if epWatchlist is not None else {}),
        **({"trialTypeCodes": trialTypeCodes} if trialTypeCodes is not None else {}),
        **({"dateRange": dateRange} if dateRange is not None else {}),
        **({"maxItemsPerSource": maxItemsPerSource} if maxItemsPerSource is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
    }
    return call_apify_actor(APIFY_ACTOR_ID, payload)


actor_21_patent_ip_enforcement_monitor_tool = StructuredTool.from_function(
    func=_actor_21_patent_ip_enforcement_monitor,
    name='actor-21-patent-ip-enforcement-monitor',
    description='Tracks USPTO PTAB patent-dispute proceedings (IPR/PGR/CBM/Derivation), plus an optional EPO opposition-watch module for a caller-supplied EP watchlist. Both sources are BYOK via free registration; delta mode flags new, updated, and concluded proceedings. PatentsView/WIPO out of scope.',
    args_schema=Actor21PatentIpEnforcementMonitorInput,
)
