"""Auto-generated by lib/schema-generator/langchain-package-generator.ts from
public/schemas/actor-20-mdb-procurement-monitor/openapi.json — do not hand-edit. Regenerate instead.
"""
from typing import Optional

from pydantic import BaseModel, Field
from langchain_core.tools import StructuredTool

from ._client import call_apify_actor

APIFY_ACTOR_ID = 'dyzTtWjfyYd7bvUZY'  # stefano_seggio/actor-20-mdb-procurement-monitor — immutable Apify ID,
# not the slug: the OpenAPI adapter this package's data is sourced from was itself corrected this
# session to call by ID rather than slug, after a real slug-rename incident (primer-actor ->
# page-metadata-extractor) — kept consistent here for the same reason.


class Actor20MdbProcurementMonitorInput(BaseModel):
    """Mirrors actor-20-mdb-procurement-monitor's real .actor/input_schema.json field-for-field."""

    sources: Optional[list[str]] = Field(default=["worldBankProcurementNotices","worldBankDebarredFirms"], min_length=1, description='worldBankProcurementNotices = the live World Bank Procurement Notices API (search.worldbank.org). worldBankDebarredFirms = the World Bank\'s static \'Other Sanctions\' debarment sub-table (worldbank.org). ADB and IDB are NOT selectable here - both were live-researched and found gated/non-compliant for v1 (Cloudflare/WAF for ADB; Power BI embed + robots.txt-blocked API for IDB) - see README.md.')
    maxItemsPerSource: Optional[int] = Field(default=100, ge=1, description='Hard cap on how many records to return per selected source this run. For worldBankProcurementNotices this bounds rows/os pagination against a live corpus of several hundred thousand notices; for worldBankDebarredFirms it is a no-op ceiling since the \'Other Sanctions\' sub-table is a single small page.')
    onlyNew: Optional[bool] = Field(default=False, description='When enabled, persists a content fingerprint per Procurement Notice between runs (in this actor\'s own named key-value store) and returns only notices that are new since the last run OR whose notice_status or other tracked fields changed since they were last seen - notices identical to last time are skipped. is_new is always populated (true/false) regardless of this setting. Only applies to worldBankProcurementNotices - Other Sanctions has no delta-tracking concept (a small static snapshot page, not a dated/paginated feed). The World Bank Procurement Notices API documents no server-side \'since\' filter, so pagination always walks from the start of the result set each run - onlyNew filters c...')
    countryFilter: Optional[list[str]] = Field(default=None, description='Optional client-side filter on project_ctry_name (e.g. \'Kenya\', \'India\'). The World Bank API documents no server-side country filter parameter, so this is applied after fetching each page.')
    noticeTypeFilter: Optional[list[str]] = Field(default=None, description='Optional client-side filter on notice_type (e.g. \'Invitation for Bids\', \'Request for Expression of Interest\', \'Contract Award\'). Applied after fetching each page, same caveat as countryFilter.')
    dateRange: Optional[str] = Field(default=None, description='Optionally restrict procurement-notice results to records whose noticedate falls within this window. Not applied to worldBankDebarredFirms records (that source has no reliable per-record publish date field in the static sub-table).')


def _actor_20_mdb_procurement_monitor(sources: Optional[list[str]] = None, maxItemsPerSource: Optional[int] = None, onlyNew: Optional[bool] = None, countryFilter: Optional[list[str]] = None, noticeTypeFilter: Optional[list[str]] = None, dateRange: Optional[str] = None) -> list[dict]:
    payload = {
        **({"sources": sources} if sources is not None else {}),
        **({"maxItemsPerSource": maxItemsPerSource} if maxItemsPerSource is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"countryFilter": countryFilter} if countryFilter is not None else {}),
        **({"noticeTypeFilter": noticeTypeFilter} if noticeTypeFilter is not None else {}),
        **({"dateRange": dateRange} if dateRange is not None else {}),
    }
    return call_apify_actor(APIFY_ACTOR_ID, payload)


actor_20_mdb_procurement_monitor_tool = StructuredTool.from_function(
    func=_actor_20_mdb_procurement_monitor,
    name='actor-20-mdb-procurement-monitor',
    description='Monitors the World Bank\'s public Procurement Notices API and \'Other Sanctions\' debarment table, normalizing records into a consistent 18-field schema with cross-run delta detection (new, status-changed, updated). World Bank only — ADB and IDB were researched and excluded as inaccessible.',
    args_schema=Actor20MdbProcurementMonitorInput,
)
