"""Auto-generated by lib/schema-generator/langchain-package-generator.ts from
public/schemas/aozora-bunko-public-domain-text-feed/openapi.json — do not hand-edit. Regenerate instead.
"""
from typing import Optional

from pydantic import BaseModel, Field
from langchain_core.tools import StructuredTool

from ._client import call_apify_actor

APIFY_ACTOR_ID = 'K0XRDbUteacQL3jeF'  # stefano_seggio/aozora-bunko-public-domain-text-feed — immutable Apify ID,
# not the slug: the OpenAPI adapter this package's data is sourced from was itself corrected this
# session to call by ID rather than slug, after a real slug-rename incident (primer-actor ->
# page-metadata-extractor) — kept consistent here for the same reason.


class AozoraBunkoPublicDomainTextFeedInput(BaseModel):
    """Mirrors aozora-bunko-public-domain-text-feed's real .actor/input_schema.json field-for-field."""

    onlyNew: Optional[bool] = Field(default=True, description='When true (default), only NEW_TEXT, REVISED_TEXT and STATUS_CHANGE rows are pushed, each as a charged PPE event. Set to false for a free baseline run: every catalog row that passes the public-domain filter is pushed once as an uncharged SNAPSHOT_NO_DIFF record.')
    resetState: Optional[bool] = Field(default=False, description='When true, clears this feed\'s stored seen-work state before this run, so the next run re-baselines from scratch (every catalog row becomes a fresh, uncharged SNAPSHOT_NO_DIFF again, subject to onlyNew). Use for testing or recovering a corrupted state store, not routine operation.')
    onlyConfirmedPublicDomain: Optional[bool] = Field(default=True, description='When true (default), keeps only catalog rows where Aozora\'s own work-copyright flag reads なし (no copyright - confirmed public domain). When false, also includes rows flagged あり (the author/estate granted free-use permission, but the work is NOT public domain).')
    includeFullText: Optional[bool] = Field(default=False, description='When true (default), NEW_TEXT/REVISED_TEXT events download the linked text ZIP, decode it from Shift_JIS, strip Aozora\'s ruby/annotation markup and legend preamble, and embed both plain_text and raw_text_with_markup - delivered as the higher-priced \'result\' event. When false, or when a text file fails to download/decode, the same events are delivered as metadata-only \'result-summary\' records instead.')
    authorIdAllowlist: Optional[list[str]] = Field(default=[], description='Aozora 人物ID values (e.g. "001257") to restrict this feed to. Leave empty to monitor the entire catalog.')
    maxItemsPerRun: Optional[int] = Field(default=20, ge=0, description='Caps the number of charged (result/result-summary) events this run will push, independent of your Apify spending limit. 0 means no Actor-side cap.')
    requestDelayMs: Optional[int] = Field(default=500, ge=0, description='Aozora Bunko is a small, volunteer-run, non-commercial mirror with no published rate limit - this default trades a slower walk for not needing to trust an unconfirmed number, and for being a polite citizen of a small server, not only a cost control.')
    maxRetries: Optional[int] = Field(default=5, ge=0, description='Retry attempts (exponential backoff with jitter) for a 429/5xx response or a network-level failure before a single catalog or text-ZIP fetch is given up on as failed.')
    requestTimeoutSecs: Optional[int] = Field(default=30, ge=5, description='Aborts a single request to Aozora Bunko (catalog export or per-work text ZIP) that takes longer than this, so one slow response never stalls the whole run.')
    deltaStateName: Optional[str] = Field(default="default", description='Names the Key-Value Store this feed\'s seen-work state is kept in. Run multiple independent schedules - e.g. filtered to different author allowlists - without them draining each other\'s baseline by giving each a distinct name here.')


def _aozora_bunko_public_domain_text_feed(onlyNew: Optional[bool] = None, resetState: Optional[bool] = None, onlyConfirmedPublicDomain: Optional[bool] = None, includeFullText: Optional[bool] = None, authorIdAllowlist: Optional[list[str]] = None, maxItemsPerRun: Optional[int] = None, requestDelayMs: Optional[int] = None, maxRetries: Optional[int] = None, requestTimeoutSecs: Optional[int] = None, deltaStateName: Optional[str] = None) -> list[dict]:
    payload = {
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"resetState": resetState} if resetState is not None else {}),
        **({"onlyConfirmedPublicDomain": onlyConfirmedPublicDomain} if onlyConfirmedPublicDomain is not None else {}),
        **({"includeFullText": includeFullText} if includeFullText is not None else {}),
        **({"authorIdAllowlist": authorIdAllowlist} if authorIdAllowlist is not None else {}),
        **({"maxItemsPerRun": maxItemsPerRun} if maxItemsPerRun is not None else {}),
        **({"requestDelayMs": requestDelayMs} if requestDelayMs is not None else {}),
        **({"maxRetries": maxRetries} if maxRetries is not None else {}),
        **({"requestTimeoutSecs": requestTimeoutSecs} if requestTimeoutSecs is not None else {}),
        **({"deltaStateName": deltaStateName} if deltaStateName is not None else {}),
    }
    return call_apify_actor(APIFY_ACTOR_ID, payload)


aozora_bunko_public_domain_text_feed_tool = StructuredTool.from_function(
    func=_aozora_bunko_public_domain_text_feed,
    name='aozora-bunko-public-domain-text-feed',
    description='Watches Aozora Bunko\'s own official catalog export for newly digitized or revised confirmed-public-domain Japanese texts and emits NEW_TEXT/REVISED_TEXT/STATUS_CHANGE events with full decoded text where available. Pay-per-event: billed only for what\'s new or changed.',
    args_schema=AozoraBunkoPublicDomainTextFeedInput,
)
