"""Auto-generated by lib/schema-generator/langchain-package-generator.ts from
public/schemas/cordoba-compras-monitor/openapi.json — do not hand-edit. Regenerate instead.
"""
from typing import Optional

from pydantic import BaseModel, Field
from langchain_core.tools import StructuredTool

from ._client import call_apify_actor

APIFY_ACTOR_ID = 'q9jhMgJRSGjyNbXKA'  # stefano_seggio/cordoba-compras-monitor — immutable Apify ID,
# not the slug: the OpenAPI adapter this package's data is sourced from was itself corrected this
# session to call by ID rather than slug, after a real slug-rename incident (primer-actor ->
# page-metadata-extractor) — kept consistent here for the same reason.


class CordobaComprasMonitorInput(BaseModel):
    """Mirrors cordoba-compras-monitor's real .actor/input_schema.json field-for-field."""

    maxItems: Optional[int] = Field(default=200, ge=1, description='Hard cap on the number of active tenders (licitaciones) returned this run. The source only covers active/open tenders (Licitaciones) - awarded or historical tenders are out of scope for this actor.')
    onlyNew: Optional[bool] = Field(default=False, description='When enabled, persists which tender ids (nroCotizacion) this actor has already returned - and their last-known estado + content fingerprint - in its own named key-value store that survives between scheduled runs, and returns only tenders that are new, changed estado, amended, or closed since a prior run. IMPORTANT: this source\'s listing is NOT reliably sorted newest-first end to end (verified live - a real tender can appear out of order relative to both its own Fecha Inicio and its own nroCotizacion, within the very first page), so onlyNew filters AFTER a full fetch (up to maxItems) rather than stopping pagination early like this fleet\'s other delta-enabled actors. It is correct, just not...')
    eventTypes: Optional[list[str]] = Field(default=["NEW_LISTING","STATUS_CHANGE","UPDATED","CLOSED"], description='Which kinds of change to deliver when \'Delta mode\' is on (ignored, everything delivered, when it is off). NEW_LISTING = never seen before. STATUS_CHANGE = seen before, estado changed - free to detect. UPDATED = seen before, same estado, a field changed (a prorroga granted, an amended item/budget). CLOSED = a previously-active tender is absent from this run\'s fetch - only computed when maxItems does not truncate the walk (a partial walk cannot prove absence).')
    dateRange: Optional[str] = Field(default=None, description='Optionally restrict results to tenders whose Fecha Inicio (publication date) falls within this window. Independent of onlyNew - this is the source\'s own declared publication timestamp, not independently cross-verified against when a tender actually first appeared on the portal.')


def _cordoba_compras_monitor(maxItems: Optional[int] = None, onlyNew: Optional[bool] = None, eventTypes: Optional[list[str]] = None, dateRange: Optional[str] = None) -> list[dict]:
    payload = {
        **({"maxItems": maxItems} if maxItems is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"eventTypes": eventTypes} if eventTypes is not None else {}),
        **({"dateRange": dateRange} if dateRange is not None else {}),
    }
    return call_apify_actor(APIFY_ACTOR_ID, payload)


cordoba_compras_monitor_tool = StructuredTool.from_function(
    func=_cordoba_compras_monitor,
    name='cordoba-compras-monitor',
    description='Monitors active public tenders (licitaciones) on the Province of Cordoba, Argentina official procurement portal. Returns organism, dates, status, per-item reference budget, and contact phone, with a delta mode that flags new, status-changed, amended, or closed tenders on recurring runs.',
    args_schema=CordobaComprasMonitorInput,
)
