"""Auto-generated by lib/schema-generator/langchain-package-generator.ts from
public/schemas/diario-oficial-cl-monitor/openapi.json — do not hand-edit. Regenerate instead.
"""
from typing import Optional

from pydantic import BaseModel, Field
from langchain_core.tools import StructuredTool

from ._client import call_apify_actor

APIFY_ACTOR_ID = 'qfBeEKuLfYUw9UOuW'  # stefano_seggio/diario-oficial-cl-monitor — immutable Apify ID,
# not the slug: the OpenAPI adapter this package's data is sourced from was itself corrected this
# session to call by ID rather than slug, after a real slug-rename incident (primer-actor ->
# page-metadata-extractor) — kept consistent here for the same reason.


class DiarioOficialClMonitorInput(BaseModel):
    """Mirrors diario-oficial-cl-monitor's real .actor/input_schema.json field-for-field."""

    sections: Optional[list[str]] = Field(default=["normas_generales"], min_length=1, description='Which sections of the edition to fetch. Not every section publishes content every day - a section with nothing that day returns 404 from the source and is skipped, not treated as an error.')
    maxItems: Optional[int] = Field(default=300, ge=1, description='Hard cap on the number of publications returned this run, across all selected sections.')
    onlyNew: Optional[bool] = Field(default=False, description='Return only publications that are new or amended (a correction re-published under the same CVE) since a prior run today, tracked in a named key-value store scoped to this actor. Most useful re-running the same day\'s edition on a schedule to catch late additions/corrections. There is no CLOSED or status-change event in this domain - a published legal notice is never withdrawn or \'closed\', it is a permanent public record.')
    eventTypes: Optional[list[str]] = Field(default=["NEW_LISTING","UPDATED"], description='Which kinds of change to deliver when \'Only new records\' is on (ignored, everything delivered, when it is off). NEW_LISTING = never seen before. UPDATED = same CVE (or identity), the content changed - a correction.')


def _diario_oficial_cl_monitor(sections: Optional[list[str]] = None, maxItems: Optional[int] = None, onlyNew: Optional[bool] = None, eventTypes: Optional[list[str]] = None) -> list[dict]:
    payload = {
        **({"sections": sections} if sections is not None else {}),
        **({"maxItems": maxItems} if maxItems is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"eventTypes": eventTypes} if eventTypes is not None else {}),
    }
    return call_apify_actor(APIFY_ACTOR_ID, payload)


diario_oficial_cl_monitor_tool = StructuredTool.from_function(
    func=_diario_oficial_cl_monitor,
    name='diario-oficial-cl-monitor',
    description='Extracts today\'s edition of Chile\'s Diario Oficial (official gazette): laws, decrees and resolutions with branch, ministry and agency hierarchy, plus a direct PDF link per entry. Delta mode reports only new listings and corrections across recurring runs.',
    args_schema=DiarioOficialClMonitorInput,
)
