"""Auto-generated by lib/schema-generator/langchain-package-generator.ts from
public/schemas/mendoza-compras-monitor/openapi.json — do not hand-edit. Regenerate instead.
"""
from typing import Optional

from pydantic import BaseModel, Field
from langchain_core.tools import StructuredTool

from ._client import call_apify_actor

APIFY_ACTOR_ID = 'bb4cRgt1i27hvr9Ug'  # stefano_seggio/mendoza-compras-monitor — immutable Apify ID,
# not the slug: the OpenAPI adapter this package's data is sourced from was itself corrected this
# session to call by ID rather than slug, after a real slug-rename incident (primer-actor ->
# page-metadata-extractor) — kept consistent here for the same reason.


class MendozaComprasMonitorInput(BaseModel):
    """Mirrors mendoza-compras-monitor's real .actor/input_schema.json field-for-field."""

    maxItems: Optional[int] = Field(default=20, ge=1, description='Hard cap on the number of RAW processes walked this run (10 per page, 25,000+ total at audit time). This is the same cap as before - onlyNew/dateRange are applied on top of this raw walk as post-filters, so the number of records actually returned can be lower than maxItems when either is active. This actor does not yet expose the advanced-search form\'s own filters (date range, organism, process type) as actor input; start small, raise gradually. Default kept low (20) because resolveSourceUrl\'s per-row postback (~1.5s each, see its own description) makes a 100-item blank run take several minutes end-to-end against this site\'s real latency - raise this for a real monitoring run.')
    onlyNew: Optional[bool] = Field(default=False, description='Persists which numeroProceso ids this actor has already returned - and their last-known estado + content fingerprint - in its own private key-value store that survives between scheduled runs, and keeps only the ones that are new, status-changed or amended. IMPORTANT for this source: comprar.mendoza.gov.ar\'s process listing is sorted by numero de proceso ascending (each organism\'s own sequential counter, cycling through years) - NOT by date and NOT newest-first. Verified live: a blank-form search\'s first page mixes processes from 2019 through 2026 rather than showing only the most recent ones. Because of this, onlyNew is a safe POST-FILTER (fetch up to maxItems raw processes exactly as a n...')
    eventTypes: Optional[list[str]] = Field(default=["NEW_LISTING","STATUS_CHANGE","UPDATED"], description='Which kinds of change to deliver when \'Only new records\' is on (ignored, everything delivered, when it is off). NEW_LISTING = never seen before. STATUS_CHANGE = seen before, estado changed (e.g. Pendiente Analisis -> Adjudicado) - free to detect, no extra request. UPDATED = seen before, same estado, a field changed (monto, fecha, unidad ejecutora...).')
    resolveSourceUrl: Optional[bool] = Field(default=True, description='When enabled (default), resolves each delivered record\'s own permalink via one extra postback per row (~1.5s each - a real, measured cost, see AGENTS.md). Disable for a much faster run when you don\'t need a process-specific link: source_url falls back to the plain search page, and delivery is charged at the cheaper result-summary rate instead of result. See README \'How much does it cost\'.')
    dateRange: Optional[str] = Field(default=None, description='Restricts the (raw, up-to-maxItems) results to processes whose own \'Fecha de apertura\' (scheduled bid-opening date/time) falls within this window ending now. Independent of onlyNew. Note: Fecha de apertura is WHEN BIDS OPEN, not when the process was published on the portal - a currently-open tender is routinely dated in the future relative to when it first appeared, so this answers \'opens/opened in the last N\', not \'listed in the last N\'. A future-dated process never matches any window until its own opening date falls inside it. See README for detail.')


def _mendoza_compras_monitor(maxItems: Optional[int] = None, onlyNew: Optional[bool] = None, eventTypes: Optional[list[str]] = None, resolveSourceUrl: Optional[bool] = None, dateRange: Optional[str] = None) -> list[dict]:
    payload = {
        **({"maxItems": maxItems} if maxItems is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"eventTypes": eventTypes} if eventTypes is not None else {}),
        **({"resolveSourceUrl": resolveSourceUrl} if resolveSourceUrl is not None else {}),
        **({"dateRange": dateRange} if dateRange is not None else {}),
    }
    return call_apify_actor(APIFY_ACTOR_ID, payload)


mendoza_compras_monitor_tool = StructuredTool.from_function(
    func=_mendoza_compras_monitor,
    name='mendoza-compras-monitor',
    description='Extracts licitaciones and contrataciones directas from the Province of Mendoza, Argentina\'s COMPR.AR procurement portal, with type, status, organism and budget per process. Delta mode flags new listings, status changes and amendments so you stop manually re-checking comprar.mendoza.gov.ar.',
    args_schema=MendozaComprasMonitorInput,
)
