"""Auto-generated by lib/schema-generator/langchain-package-generator.ts from
public/schemas/page-metadata-extractor/openapi.json — do not hand-edit. Regenerate instead.
"""
from typing import Optional

from pydantic import BaseModel, Field
from langchain_core.tools import StructuredTool

from ._client import call_apify_actor

APIFY_ACTOR_ID = 'U9fUBHDngX6IyjzzF'  # stefano_seggio/page-metadata-extractor — immutable Apify ID,
# not the slug: the OpenAPI adapter this package's data is sourced from was itself corrected this
# session to call by ID rather than slug, after a real slug-rename incident (primer-actor ->
# page-metadata-extractor) — kept consistent here for the same reason.


class PageMetadataExtractorInput(BaseModel):
    """Mirrors page-metadata-extractor's real .actor/input_schema.json field-for-field."""

    startUrls: Optional[list[str]] = Field(default=None, min_length=1, description='URLs to start crawling from. At least one is required - the Actor charges an actor-start event just for running, so an empty list would bill the caller for zero output.')
    maxRequestsPerCrawl: Optional[int] = Field(default=100, ge=1, description='Hard limit on how many pages this run will fetch, across start URLs, discovered same-site links and pagination.')
    paginationSelector: Optional[str] = Field(default=None, description='Optional CSS selector for a next-page link, e.g. a[rel=next] or .pagination .next. When set, the crawler follows it up to Max pagination depth pages per start URL, on top of normal same-site link discovery.')
    maxPaginationDepth: Optional[int] = Field(default=3, ge=0, description='Maximum number of paginated pages to follow per start URL when Pagination selector is set. Ignored otherwise.')
    onlyChanged: Optional[bool] = Field(default=False, description='When enabled, a page is still crawled (its links are still followed) but is only added to the dataset - and charged - if it\'s the first time this exact URL has been scraped, or its extracted metadata differs from the last time this Actor scraped it. Pages with unchanged metadata are skipped. Useful for scheduled re-runs where you only want to pay for what\'s new or different since the last run.')


def _page_metadata_extractor(startUrls: Optional[list[str]] = None, maxRequestsPerCrawl: Optional[int] = None, paginationSelector: Optional[str] = None, maxPaginationDepth: Optional[int] = None, onlyChanged: Optional[bool] = None) -> list[dict]:
    payload = {
        **({"startUrls": startUrls} if startUrls is not None else {}),
        **({"maxRequestsPerCrawl": maxRequestsPerCrawl} if maxRequestsPerCrawl is not None else {}),
        **({"paginationSelector": paginationSelector} if paginationSelector is not None else {}),
        **({"maxPaginationDepth": maxPaginationDepth} if maxPaginationDepth is not None else {}),
        **({"onlyChanged": onlyChanged} if onlyChanged is not None else {}),
    }
    return call_apify_actor(APIFY_ACTOR_ID, payload)


page_metadata_extractor_tool = StructuredTool.from_function(
    func=_page_metadata_extractor,
    name='page-metadata-extractor',
    description='Extract clean, structured metadata from any site: title, meta description, canonical URL, Open Graph tags, H1 and word count. Built-in retries, session rotation and optional pagination keep every crawl resilient. Built for SEO audits and LLM/RAG pipelines - pay only per result, never per wasted run.',
    args_schema=PageMetadataExtractorInput,
)
