"""Auto-generated by lib/schema-generator/langchain-package-generator.ts from
public/schemas/salta-compras-monitor/openapi.json — do not hand-edit. Regenerate instead.
"""
from typing import Optional

from pydantic import BaseModel, Field
from langchain_core.tools import StructuredTool

from ._client import call_apify_actor

APIFY_ACTOR_ID = 'Tx9wBKZyySZa5WcsE'  # stefano_seggio/salta-compras-monitor — immutable Apify ID,
# not the slug: the OpenAPI adapter this package's data is sourced from was itself corrected this
# session to call by ID rather than slug, after a real slug-rename incident (primer-actor ->
# page-metadata-extractor) — kept consistent here for the same reason.


class SaltaComprasMonitorInput(BaseModel):
    """Mirrors salta-compras-monitor's real .actor/input_schema.json field-for-field."""

    fetchDetail: Optional[bool] = Field(default=True, description='When enabled (default), fetches each publication\'s detail page for the full field set (organismo gestor, costo pliego, lugar de entrega, when present) plus attached document links. Disable for a faster, listing-only run.')
    maxItems: Optional[int] = Field(default=100, ge=1, description='Hard cap on the number of publications returned this run. The portal serves ~250 currently-open (vigentes) publications at a time, 5 per page.')
    onlyNew: Optional[bool] = Field(default=False, description='Delta mode for daily/recurring monitoring: returns only publications that are new, changed (a fingerprinted amendment - a new monto, document, date...) or closed since a previous run. Seen ids are persisted across runs in a named key-value store unique to this actor ("salta-compras-monitor-delta-state"), not the run\'s own default store (which is isolated per run and would not survive between scheduled runs). Every record still carries is_new, so a normal (onlyNew=false) run also tells you which of its results are new. Pagination is NOT stopped early once already-seen records are reached: this actor\'s listing is sorted by Fecha/Hora Apertura (the bid-opening deadline), not by when a public...')
    eventTypes: Optional[list[str]] = Field(default=["NEW_LISTING","UPDATED","CLOSED"], description='Which kinds of change to deliver when \'Only new\' is on (ignored, everything delivered, when it is off). NEW_LISTING = never seen before. UPDATED = seen before, a field changed (fingerprinted). CLOSED = a previously-seen publication is absent from a complete walk this run - no longer vigente. CLOSED detection only runs when maxItems does not truncate the walk (a partial walk cannot prove absence) - see AGENTS.md.')
    dateRange: Optional[str] = Field(default=None, description='Filters results to publications whose own Fecha/Hora Apertura (bid-opening deadline - the only date field this source exposes anywhere, listing or detail; there is no separate publication date) falls within the given window. For the "vigentes" (currently open) publications this actor covers, that date is almost always in the FUTURE relative to when this actor runs, so this is an upcoming-deadline filter ("opens within the next 24h/7d/30d"), not a "published in the last N" filter. Independent of onlyNew.')


def _salta_compras_monitor(fetchDetail: Optional[bool] = None, maxItems: Optional[int] = None, onlyNew: Optional[bool] = None, eventTypes: Optional[list[str]] = None, dateRange: Optional[str] = None) -> list[dict]:
    payload = {
        **({"fetchDetail": fetchDetail} if fetchDetail is not None else {}),
        **({"maxItems": maxItems} if maxItems is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"eventTypes": eventTypes} if eventTypes is not None else {}),
        **({"dateRange": dateRange} if dateRange is not None else {}),
    }
    return call_apify_actor(APIFY_ACTOR_ID, payload)


salta_compras_monitor_tool = StructuredTool.from_function(
    func=_salta_compras_monitor,
    name='salta-compras-monitor',
    description='Extracts every currently open tender and contract award (licitaciones, adjudicaciones, contrataciones) from Salta Province, Argentina\'s official procurement portal, with organism, expediente, opening date/time and document links per publication. Delta mode flags new, amended and closed processes.',
    args_schema=SaltaComprasMonitorInput,
)
