"""Auto-generated by lib/schema-generator/langchain-package-generator.ts from
public/schemas/uk-hse-enforcement-monitor/openapi.json — do not hand-edit. Regenerate instead.
"""
from typing import Optional

from pydantic import BaseModel, Field
from langchain_core.tools import StructuredTool

from ._client import call_apify_actor

APIFY_ACTOR_ID = 'jV35qppM82fjyjsle'  # stefano_seggio/uk-hse-enforcement-monitor — immutable Apify ID,
# not the slug: the OpenAPI adapter this package's data is sourced from was itself corrected this
# session to call by ID rather than slug, after a real slug-rename incident (primer-actor ->
# page-metadata-extractor) — kept consistent here for the same reason.


class UkHseEnforcementMonitorInput(BaseModel):
    """Mirrors uk-hse-enforcement-monitor's real .actor/input_schema.json field-for-field."""

    datasets: Optional[list[str]] = Field(default=["convictions","notices"], min_length=1, description='Convictions = successful prosecutions (defendant, fine, costs, breaches, court, hearing date; HSE keeps 5 years). Notices = Improvement and Prohibition enforcement notices (recipient, type, served/compliance dates, result; HSE keeps 10 years).')
    nameContains: Optional[str] = Field(default=None, description='Substring match on the defendant\'s (convictions) or recipient\'s (notices) name, e.g. \'Skanska\' or \'Balfour Beatty\'. The contractor-vetting filter. Quotes are treated as single-character wildcards.')
    descriptionContains: Optional[str] = Field(default=None, description='Full-text substring over the case description (convictions) or notice summary (notices), e.g. \'asbestos\', \'scaffold\', \'silica\'.')
    localAuthorityContains: Optional[str] = Field(default=None, description='Local authority where the offence occurred, e.g. \'Bradford\', \'Cardiff UA\'.')
    mainActivityContains: Optional[str] = Field(default=None, description='A numeric value matches the SIC 2007 code of the offence location; any other text matches the activity description (\'ROOFING\', \'MACHINING\'). The site keeps the two in different columns, so a code never matches as text and vice versa. The code match is a CONTAINS match on the register: use a full 5-digit code for one class (\'43910\' = roofing) or a 4-digit group (\'4391\'); 2-3 digit values also match every code that merely contains those digits (\'43\' returns 14310, 24310, 46430 ...) - use the industry filter for broad selections.')
    region: Optional[str] = Field(default="", description='HSE\'s seven UK regions.')
    country: Optional[str] = Field(default="", description='Country of the offence location.')
    industry: Optional[str] = Field(default="", description='HSE\'s five industry groups.')
    hseDivision: Optional[str] = Field(default="", description='HSE\'s operational division (finer than region).')
    dateFrom: Optional[str] = Field(default=None, description='Offence date (convictions) / date the notice was served (notices). Absolute (2026-01-01) or relative (\'30 days\', \'6 months\', \'1 year\' back from today, UK calendar). Note: both dates lag publication on the register by weeks to years - for \'what is new on the register\' use delta mode instead.')
    dateTo: Optional[str] = Field(default=None, description='Absolute or relative upper bound of the same date. Leave empty for \'today\'.')
    hseReference: Optional[str] = Field(default=None, pattern='^\\s*\\d+\\s*$', description='Everything about one party: the numeric HSE Reference shown on a defendant or recipient page (the same id is used on both registers), e.g. 4392330.')
    recordNumber: Optional[str] = Field(default=None, pattern='^\\s*\\d+\\s*$', description='Look up one record by its case number (convictions) or notice number (notices), e.g. 4883993 or 316005113.')
    defendantStatus: Optional[str] = Field(default="", description='Legal form of the defendant. Convictions only.')
    resultingFromFatality: Optional[str] = Field(default="any", description='Only cases that resulted from the investigation of a (RIDDOR-reportable) fatality. Convictions only.')
    minTotalFineGbp: Optional[int] = Field(default=None, ge=0, description='Only cases with a total fine of at least this amount. Tip: 100000 leaves about 50 of the 210 cases.')
    maxTotalFineGbp: Optional[int] = Field(default=None, ge=0, description='Only cases with a total fine of at most this amount.')
    noticeTypes: Optional[list[str]] = Field(default=[], description='HSE\'s nine notice-type codes (labels verified against the register, 2026-09-07). \'03\' is the ordinary Improvement Notice (22,000+); \'01\' and \'02\' are the rare Crown / FEPA variants. Select several to get their union. Notices only.')
    act: Optional[str] = Field(default="", description='Primary legislation of the breach. Notices only (labels are the register\'s own, some truncated by the site).')
    eventTypes: Optional[list[str]] = Field(default=["SANCTION","NEW_LISTING","UPDATED"], description='SANCTION = a conviction not delivered before; NEW_LISTING = a notice not delivered before; UPDATED = a record you already received whose case/notice page changed (a notice complied with, a revised compliance date, a breach or hearing added) - delta mode only. Applied by the delta engine, not by the site: changing it later does not fork the delta memory.')
    onlyNew: Optional[bool] = Field(default=False, description='Remembers every record it has delivered (per filter set, in a named key-value store) and returns only records that are new or whose page changed since. Convictions (~210 records) are always walked in full; notices stop at the first two pages of already-known records, so a scheduled run costs a few pages.')
    recheckDays: Optional[int] = Field(default=180, ge=0, description='In delta mode, known records that are still open (Improvement Notices with Result \'Ongoing\', and every conviction) are re-read for this many days after they were first delivered (or after their register date, whichever is later) to detect UPDATED events - the register has no \'last updated\' field, so this is the only way to see a notice being complied with or a hearing being added. 0 disables re-checks. Up to 2,000 records are re-checked per run.')
    deltaStateName: Optional[str] = Field(default=None, pattern='^[A-Za-z0-9-]{1,30}$', description='Optional label for the memory of a monitoring task. Defaults to a fingerprint of your filters, so different schedules never interfere. Set the same name on two tasks to make them share one memory.')
    resetState: Optional[bool] = Field(default=False, description='Forget every previously delivered record for this delta state and re-baseline (the run then returns up to \'Max records per register\' most recently entered records).')
    maxItemsPerDataset: Optional[int] = Field(default=100, ge=1, description='Hard cap on delivered records per selected register (and therefore on cost: you pay per record). On the very first delta run the cap defines the baseline: the oldest record that run delivers is remembered per register, and records entered before it are history - later delta runs never deliver or charge for them, whatever the cap (run once with onlyNew=false, or set a high cap on the first run, if you want the history). On every later delta run the overflow is a backlog: the walk remembers where it stopped (a per-register watermark in the delta memory) and the next run walks down to that point instead of stopping at the records already delivered.')
    fetchDetail: Optional[bool] = Field(default=True, description='Opens each record\'s own page for the description, dates, fine and costs, result, address, industry and HSE admin fields (plus, for convictions, the per-case breach list). Off = listing-row-only records (name, date, local authority, main activity, notice type) at the cheaper \'result-summary\' price; no UPDATED detection is possible without it.')
    fetchBreachDetail: Optional[bool] = Field(default=True, description='Convictions: opens each breach\'s page for the court, Act section / Regulation paragraph, hearing date, result and per-breach fine. Notices: fetches the breach list (Act / regulation / paragraph per breach). Off = the cheaper \'result-summary\' price.')
    fetchPartyDetail: Optional[bool] = Field(default=True, description='Opens the party\'s page (registered address, Status such as \'Private Company\' or \'Individual\', HSE Reference) and its case and notice lists on both registers - the repeat-offender signal (3 extra requests per record, no extra charge).')
    maxConcurrency: Optional[int] = Field(default=5, ge=1, description='Run-wide cap on simultaneous HTTP requests (listing, detail, breach and party pages together - never more than this in flight). The register is a classic-ASP site that answered 17 concurrent requests without throttling; 5 keeps a 100-record run around a minute.')
    dateRange: Optional[str] = Field(default=None, pattern='^(24h|7d|30d)$', description='Kept for tasks created with version 1: \'24h\', \'7d\' or \'30d\' are interpreted as \'Date from\'.')


def _uk_hse_enforcement_monitor(datasets: Optional[list[str]] = None, nameContains: Optional[str] = None, descriptionContains: Optional[str] = None, localAuthorityContains: Optional[str] = None, mainActivityContains: Optional[str] = None, region: Optional[str] = None, country: Optional[str] = None, industry: Optional[str] = None, hseDivision: Optional[str] = None, dateFrom: Optional[str] = None, dateTo: Optional[str] = None, hseReference: Optional[str] = None, recordNumber: Optional[str] = None, defendantStatus: Optional[str] = None, resultingFromFatality: Optional[str] = None, minTotalFineGbp: Optional[int] = None, maxTotalFineGbp: Optional[int] = None, noticeTypes: Optional[list[str]] = None, act: Optional[str] = None, eventTypes: Optional[list[str]] = None, onlyNew: Optional[bool] = None, recheckDays: Optional[int] = None, deltaStateName: Optional[str] = None, resetState: Optional[bool] = None, maxItemsPerDataset: Optional[int] = None, fetchDetail: Optional[bool] = None, fetchBreachDetail: Optional[bool] = None, fetchPartyDetail: Optional[bool] = None, maxConcurrency: Optional[int] = None, dateRange: Optional[str] = None) -> list[dict]:
    payload = {
        **({"datasets": datasets} if datasets is not None else {}),
        **({"nameContains": nameContains} if nameContains is not None else {}),
        **({"descriptionContains": descriptionContains} if descriptionContains is not None else {}),
        **({"localAuthorityContains": localAuthorityContains} if localAuthorityContains is not None else {}),
        **({"mainActivityContains": mainActivityContains} if mainActivityContains is not None else {}),
        **({"region": region} if region is not None else {}),
        **({"country": country} if country is not None else {}),
        **({"industry": industry} if industry is not None else {}),
        **({"hseDivision": hseDivision} if hseDivision is not None else {}),
        **({"dateFrom": dateFrom} if dateFrom is not None else {}),
        **({"dateTo": dateTo} if dateTo is not None else {}),
        **({"hseReference": hseReference} if hseReference is not None else {}),
        **({"recordNumber": recordNumber} if recordNumber is not None else {}),
        **({"defendantStatus": defendantStatus} if defendantStatus is not None else {}),
        **({"resultingFromFatality": resultingFromFatality} if resultingFromFatality is not None else {}),
        **({"minTotalFineGbp": minTotalFineGbp} if minTotalFineGbp is not None else {}),
        **({"maxTotalFineGbp": maxTotalFineGbp} if maxTotalFineGbp is not None else {}),
        **({"noticeTypes": noticeTypes} if noticeTypes is not None else {}),
        **({"act": act} if act is not None else {}),
        **({"eventTypes": eventTypes} if eventTypes is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"recheckDays": recheckDays} if recheckDays is not None else {}),
        **({"deltaStateName": deltaStateName} if deltaStateName is not None else {}),
        **({"resetState": resetState} if resetState is not None else {}),
        **({"maxItemsPerDataset": maxItemsPerDataset} if maxItemsPerDataset is not None else {}),
        **({"fetchDetail": fetchDetail} if fetchDetail is not None else {}),
        **({"fetchBreachDetail": fetchBreachDetail} if fetchBreachDetail is not None else {}),
        **({"fetchPartyDetail": fetchPartyDetail} if fetchPartyDetail is not None else {}),
        **({"maxConcurrency": maxConcurrency} if maxConcurrency is not None else {}),
        **({"dateRange": dateRange} if dateRange is not None else {}),
    }
    return call_apify_actor(APIFY_ACTOR_ID, payload)


uk_hse_enforcement_monitor_tool = StructuredTool.from_function(
    func=_uk_hse_enforcement_monitor,
    name='uk-hse-enforcement-monitor',
    description='Track UK HSE enforcement action: prosecutions and fines from the register of convictions, plus Improvement and Prohibition notices. Filter by company name, region, industry, fine amount, notice type and date. Delta mode flags new and updated compliance risk. Pay per record, no proxy needed.',
    args_schema=UkHseEnforcementMonitorInput,
)
