"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'pba-tenders-monitor' (local .actor/input_schema.json), generated 2026-09-18.
Regenerate with: node generate-all.js

NOTE: this targets AG2 Classic (import autogen), the AutoGen-lineage conversational-agent API.
"AutoGen" itself is in Microsoft-maintenance mode as of 2026; AG2 (ag2ai/ag2) is the actively
developed continuation. AG2 also has a newer, separate v1.0 protocol-driven surface (shipped
2026-09-11) not covered here because its docs could not be verified at generation time.
"""
import os
from typing import Annotated, Optional

import requests
from autogen import ConversableAgent, register_function, LLMConfig

APIFY_ACTOR_ID = 'yWvRQyWSyGVLJPtQ7'  # stefano_seggio/pba-tenders-monitor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


def run_pba_tenders_monitor(
    views: Annotated[Optional[list[str]], 'Which PBAC grids to extract. Defaults to all three.'] = ["apertura_proxima","ultimos_30_dias","adjudicados"],
    fetchFullDetail: Annotated[Optional[bool], 'When enabled, simulates the postback for each process. Known limitation: this currently returns only a short status label, not the full Pliego document text - that content lives in a nested panel not yet mapped. Leave off until this is resolved; it adds cost with limited extra value today.'] = false,
    maxItems: Annotated[Optional[int], 'Hard cap on the number of tender processes returned this run, across all selected views.'] = 200,
    onlyNew: Annotated[Optional[bool], 'For recurring/scheduled runs: return only tenders that are new, changed vistaOrigen/estado, amended or closed since a prior run of this actor (tracked in a named key-value store scoped to this actor). CLOSED (a tender no longer in any of the 3 grids) is only ever computed when \'Views to extract\' covers all 3 default views - a narrower selection makes this run\'s fetch a subset of the site, so CLOSED is skipped (and logged) in that case.'] = false,
    eventTypes: Annotated[Optional[list[str]], 'Which kinds of change to deliver when \'Only new records\' is on (ignored, everything delivered, when it is off). NEW_LISTING = never seen before. STATUS_CHANGE = vistaOrigen or estado changed - e.g. a tender moving from upcoming to awarded. UPDATED = same vistaOrigen/estado, a field changed. CLOSED = no longer listed in any of the 3 grids (only computed on an unfiltered \'Views to extract\').'] = ["NEW_LISTING","STATUS_CHANGE","UPDATED","CLOSED"],
    dateRange: Annotated[Optional[str], 'Restricts results to tenders whose fechaApertura falls within this window ending now. Independent of onlyNew. Note: fechaApertura is WHEN BIDS OPEN, not when the tender was published - for the \'Upcoming openings\' view specifically that date is routinely in the future, so this filter will not match those rows (see AGENTS.md/README).'] = None,
) -> str:
    """PBAC is the official public tender portal for Buenos Aires Province, Argentina, not the city of Buenos Aires (CABA) or national procurement. Extracts upcoming openings, last-30-day tenders, and awarded processes, with delta mode flagging new listings, status changes, amendments, and closures."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        **({"views": views} if views is not None else {}),
        **({"fetchFullDetail": fetchFullDetail} if fetchFullDetail is not None else {}),
        **({"maxItems": maxItems} if maxItems is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"eventTypes": eventTypes} if eventTypes is not None else {}),
        **({"dateRange": dateRange} if dateRange is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.text


# Wire into your own agents, e.g.:
#
# with LLMConfig(api_type="openai", model="gpt-4o-mini"):
#     compliance_agent = ConversableAgent(name="compliance_agent", system_message="...")
# executor_agent = ConversableAgent(name="executor_agent", human_input_mode="NEVER")
#
# register_function(
#     run_pba_tenders_monitor,
#     caller=compliance_agent,
#     executor=executor_agent,
#     description='PBAC is the official public tender portal for Buenos Aires Province, Argentina, not the city of Buenos Aires (CABA) or national procurement. Extracts upcoming openings, last-30-day tenders, and awarded processes, with delta mode flagging new listings, status changes, amendments, and closures.',
# )
