"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'regione-lombardia-grants-registry-monitor' (live Apify API), generated 2026-09-18.
Regenerate with: node generate-all.js

NOTE: this targets AG2 Classic (import autogen), the AutoGen-lineage conversational-agent API.
"AutoGen" itself is in Microsoft-maintenance mode as of 2026; AG2 (ag2ai/ag2) is the actively
developed continuation. AG2 also has a newer, separate v1.0 protocol-driven surface (shipped
2026-09-11) not covered here because its docs could not be verified at generation time.
"""
import os
from typing import Annotated, Optional

import requests
from autogen import ConversableAgent, register_function, LLMConfig

APIFY_ACTOR_ID = 'f0xRlvzERsbgbU1ru'  # stefano_seggio/regione-lombardia-grants-registry-monitor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


def run_regione_lombardia_grants_registry_monitor(
    onlyNew: Annotated[Optional[bool], 'When true (default), only NEW_LISTING, STATUS_CHANGE and UPDATED events are delivered - never a BASELINE_SNAPSHOT or SNAPSHOT_NO_DIFF row. When false, every bando currently in scope is delivered every run, including the free first-run baseline and unchanged rows - useful to preview the full dataset before committing spend.'] = true,
    eventTypes: Annotated[Optional[list[str]], 'Restricts which of the three charged event types are delivered. Leave empty to deliver all three. Has no effect on BASELINE_SNAPSHOT/SNAPSHOT_NO_DIFF, which are controlled solely by onlyNew.'] = [],
    statusFilter: Annotated[Optional[list[str]], 'Deliver only bandi whose computed status (derived by this Actor from apertura_adesione/chiusura_adesione against the run\'s own clock - the source itself publishes no lifecycle-status column) is one of these. This is a delivery-time filter only - every bando is still tracked internally regardless, so one that transitions into or out of your filtered status is still correctly reported as STATUS_CHANGE the moment it does. Leave empty to deliver all statuses.'] = [],
    policyAreaFilter: Annotated[Optional[list[str]], 'Deliver only bandi classified into one of these policy areas by this Actor\'s own taxonomy mapper (built from the real, observed direzione_generale values in the live dataset - a free-text field with no controlled vocabulary in the source itself). Delivery-time only, same tracking guarantee as statusFilter. Leave empty for all areas. See README for the full taxonomy and its source mapping.'] = [],
    keyword: Annotated[Optional[str], 'Full-text search passed server-side as Socrata\'s own $q parameter, matched against every text column (titolo_bando, direzione_generale, ente, tipo_strumento). Example: "formazione" or "ICT". Leave empty to skip.'] = "",
    directorateFilter: Annotated[Optional[list[str]], 'Deliver only bandi whose direzione_generale case-insensitively contains one of these values. Free-text matching against whatever Regione Lombardia\'s own back office typed in, not a stable enum - real values observed live include "ISTRUZIONE, FORMAZIONE, LAVORO", "CULTURA", "ARIA SPA". Delivery-time only. Leave empty for all directorates.'] = [],
    maxItems: Annotated[Optional[int], 'Stops the run once this many records have been pushed (and charged, where applicable). Records not yet reached when the limit is hit are simply re-evaluated fresh next run. Leave unset for no limit - the full register is only ~1,912 rows, so an unlimited run is inexpensive even on a full onlyNew:false baseline pass.'] = 20,
    deltaStateName: Annotated[Optional[str], 'Names the persistent Key-Value Store this run\'s delta memory lives in. Use a distinct name per independent schedule/filter configuration so they don\'t share baseline progress.'] = "default",
    resetState: Annotated[Optional[bool], 'When true, ignores all previously-remembered bandi for this deltaStateName and re-baselines from scratch (every bando becomes a fresh, uncharged BASELINE_SNAPSHOT again, subject to onlyNew).'] = false,
    socrataAppToken: Annotated[Optional[str], 'An optional Socrata app token (free, self-service at dati.lombardia.it) sent as the X-App-Token header on every request. Unauthenticated requests share a per-IP throttle Socrata does not fully document publicly. Supplying your own token removes the shared-IP ceiling entirely. Never logged or persisted beyond this run.'] = None,
    requestTimeoutSecs: Annotated[Optional[int], 'Aborts a single Socrata API request that takes longer than this, so one slow response never stalls the whole run.'] = 30,
    maxRetries: Annotated[Optional[int], 'Retry attempts (exponential backoff with jitter) before a single page fetch is given up on as failed. Applies only to retryable outcomes (429 and 5xx responses, or a request timeout) - any other non-2xx response is treated as final immediately.'] = 4,
) -> str:
    """Delta monitor for Regione Lombardia's Socrata open-data grants/tenders registry (bandi). Computes a real OPEN/UPCOMING/CLOSED status from source dates, classifies each bando into a policy-area taxonomy, and emits NEW_LISTING/STATUS_CHANGE/UPDATED events. Pay-per-event: billed only for what changed."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"eventTypes": eventTypes} if eventTypes is not None else {}),
        **({"statusFilter": statusFilter} if statusFilter is not None else {}),
        **({"policyAreaFilter": policyAreaFilter} if policyAreaFilter is not None else {}),
        **({"keyword": keyword} if keyword is not None else {}),
        **({"directorateFilter": directorateFilter} if directorateFilter is not None else {}),
        **({"maxItems": maxItems} if maxItems is not None else {}),
        **({"deltaStateName": deltaStateName} if deltaStateName is not None else {}),
        **({"resetState": resetState} if resetState is not None else {}),
        **({"socrataAppToken": socrataAppToken} if socrataAppToken is not None else {}),
        **({"requestTimeoutSecs": requestTimeoutSecs} if requestTimeoutSecs is not None else {}),
        **({"maxRetries": maxRetries} if maxRetries is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.text


# Wire into your own agents, e.g.:
#
# with LLMConfig(api_type="openai", model="gpt-4o-mini"):
#     compliance_agent = ConversableAgent(name="compliance_agent", system_message="...")
# executor_agent = ConversableAgent(name="executor_agent", human_input_mode="NEVER")
#
# register_function(
#     run_regione_lombardia_grants_registry_monitor,
#     caller=compliance_agent,
#     executor=executor_agent,
#     description='Delta monitor for Regione Lombardia\'s Socrata open-data grants/tenders registry (bandi). Computes a real OPEN/UPCOMING/CLOSED status from source dates, classifies each bando into a policy-area taxonomy, and emits NEW_LISTING/STATUS_CHANGE/UPDATED events. Pay-per-event: billed only for what changed.',
# )
