// Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
// Source: Apify actor 'actor-19-maritime-sanctions-monitor' (local .actor/input_schema.json), generated 2026-09-18.
// Regenerate with: node generate-all.js
import { tool } from "langchain";
import * as z from "zod";

const APIFY_ACTOR_ID = "dR68wHyuOLS2WEhmo"; // stefano_seggio/actor-19-maritime-sanctions-monitor

export const actor19MaritimeSanctionsMonitorTool = tool(
  async (input) => {
    const token = process.env.APIFY_TOKEN;
    if (!token) throw new Error("APIFY_TOKEN is not set");
    const res = await fetch(
      `https://api.apify.com/v2/acts/${APIFY_ACTOR_ID}/run-sync-get-dataset-items?token=${token}`,
      { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) },
    );
    if (!res.ok) throw new Error(`Apify run failed: ${res.status} ${res.statusText}`);
    return res.json(); // dataset items array, returned directly
  },
  {
    name: "actor-19-maritime-sanctions-monitor",
    description: "Screens the US Treasury OFAC Specially Designated Nationals vessel list against the UN Security Council Consolidated List by IMO number, delivering normalized ship-sanctions records with cross-run change detection: new designations, program changes, and vessel delistings.",
    schema: z.object({
    maxItems: z.number().int().min(1).describe("Hard cap on how many vessel-type SDN records to return this run, taken in the order OFAC lists them in the source feed.").default(250),
    onlyNew: z.boolean().describe("When enabled, persists a content fingerprint per vessel (uid) between runs in this actor's own key-value store and returns only records that are new since the last run OR whose sanctions program(s) or other tracked fields changed since they were last seen - records identical to last time are skipped. Vessels no longer present in the current OFAC feed are always reported as DELISTED regardless of this setting (when the run was not itself truncated by maxItems - see the DELISTED section of README.md). Recommended for recurring monitoring; leave off for a full extraction of the current vessel-type SDN list.").default(false),
    enrichWithUnConsolidatedList: z.boolean().describe("When enabled (default), additionally fetches the UN Security Council Consolidated Sanctions List and flags OFAC vessel records whose IMO number is also mentioned in a UN entity's designation text. Adds one extra live fetch and a linear scan of the UN list per run; disable for a faster OFAC-only run.").default(true),
    programFilter: z.array(z.string()).describe("Optional: only return vessels whose Program list contains at least one of these OFAC program codes (case-insensitive substring match, e.g. \"IRAN\", \"DPRK2\", \"RUSSIA-EO14024\"). Leave empty to return vessels from all programs.").optional(),
    vesselNameContains: z.string().describe("Optional case-insensitive substring filter on the vessel's listed name, applied before maxItems. Useful for a narrow monitoring run against one vessel of interest.").optional(),
    }),
  },
);
