// Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
// Source: Apify actor 'uk-hse-enforcement-monitor' (local .actor/input_schema.json), generated 2026-09-18.
// Regenerate with: node generate-all.js
import { tool } from "langchain";
import * as z from "zod";

const APIFY_ACTOR_ID = "jV35qppM82fjyjsle"; // stefano_seggio/uk-hse-enforcement-monitor

export const ukHseEnforcementMonitorTool = tool(
  async (input) => {
    const token = process.env.APIFY_TOKEN;
    if (!token) throw new Error("APIFY_TOKEN is not set");
    const res = await fetch(
      `https://api.apify.com/v2/acts/${APIFY_ACTOR_ID}/run-sync-get-dataset-items?token=${token}`,
      { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) },
    );
    if (!res.ok) throw new Error(`Apify run failed: ${res.status} ${res.statusText}`);
    return res.json(); // dataset items array, returned directly
  },
  {
    name: "uk-hse-enforcement-monitor",
    description: "Track UK HSE enforcement action: prosecutions and fines from the register of convictions, plus Improvement and Prohibition notices. Filter by company name, region, industry, fine amount, notice type and date. Delta mode flags new and updated compliance risk. Pay per record, no proxy needed.",
    schema: z.object({
    datasets: z.array(z.string()).min(1).describe("Convictions = successful prosecutions (defendant, fine, costs, breaches, court, hearing date; HSE keeps 5 years). Notices = Improvement and Prohibition enforcement notices (recipient, type, served/compliance dates, result; HSE keeps 10 years).").default(["convictions","notices"]),
    nameContains: z.string().describe("Substring match on the defendant's (convictions) or recipient's (notices) name, e.g. 'Skanska' or 'Balfour Beatty'. The contractor-vetting filter. Quotes are treated as single-character wildcards.").optional(),
    descriptionContains: z.string().describe("Full-text substring over the case description (convictions) or notice summary (notices), e.g. 'asbestos', 'scaffold', 'silica'.").optional(),
    localAuthorityContains: z.string().describe("Local authority where the offence occurred, e.g. 'Bradford', 'Cardiff UA'.").optional(),
    mainActivityContains: z.string().describe("A numeric value matches the SIC 2007 code of the offence location; any other text matches the activity description ('ROOFING', 'MACHINING'). The site keeps the two in different columns, so a code never matches as text and vice versa. The code match is a CONTAINS match on the register: use a full 5-digit code for one class ('43910' = roofing) or a 4-digit group ('4391'); 2-3 digit values also match every code that merely contains those digits ('43' returns 14310, 24310, 46430 ...) - use the industry filter for broad selections.").optional(),
    region: z.enum(["", "1", "2", "3", "4", "5", "6", "7"]).describe("HSE's seven UK regions.").default(""),
    country: z.enum(["", "8", "9", "10", "11"]).describe("Country of the offence location.").default(""),
    industry: z.enum(["", "12", "13", "14", "15", "16"]).describe("HSE's five industry groups.").default(""),
    hseDivision: z.enum(["", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27"]).describe("HSE's operational division (finer than region).").default(""),
    dateFrom: z.string().describe("Offence date (convictions) / date the notice was served (notices). Absolute (2026-01-01) or relative ('30 days', '6 months', '1 year' back from today, UK calendar). Note: both dates lag publication on the register by weeks to years - for 'what is new on the register' use delta mode instead.").optional(),
    dateTo: z.string().describe("Absolute or relative upper bound of the same date. Leave empty for 'today'.").optional(),
    hseReference: z.string().regex(new RegExp("^\\s*\\d+\\s*$")).describe("Everything about one party: the numeric HSE Reference shown on a defendant or recipient page (the same id is used on both registers), e.g. 4392330.").optional(),
    recordNumber: z.string().regex(new RegExp("^\\s*\\d+\\s*$")).describe("Look up one record by its case number (convictions) or notice number (notices), e.g. 4883993 or 316005113.").optional(),
    defendantStatus: z.enum(["", "1980", "1972", "1981", "1974", "1976", "1978", "1977", "1973", "1975", "1979"]).describe("Legal form of the defendant. Convictions only.").default(""),
    resultingFromFatality: z.enum(["any", "yes", "no"]).describe("Only cases that resulted from the investigation of a (RIDDOR-reportable) fatality. Convictions only.").default("any"),
    minTotalFineGbp: z.number().int().min(0).describe("Only cases with a total fine of at least this amount. Tip: 100000 leaves about 50 of the 210 cases.").optional(),
    maxTotalFineGbp: z.number().int().min(0).describe("Only cases with a total fine of at most this amount.").optional(),
    noticeTypes: z.array(z.string()).describe("HSE's nine notice-type codes (labels verified against the register, 2026-09-07). '03' is the ordinary Improvement Notice (22,000+); '01' and '02' are the rare Crown / FEPA variants. Select several to get their union. Notices only.").default([]),
    act: z.enum(["", "502", "517", "519", "518", "491", "512", "490", "481", "488", "504", "500", "513", "507", "479", "482", "515", "487", "505", "516", "501", "514", "499", "497", "489", "495", "478", "494", "511", "509", "521", "520", "483", "485", "486", "506", "503", "493", "492", "484", "496", "510", "508", "480"]).describe("Primary legislation of the breach. Notices only (labels are the register's own, some truncated by the site).").default(""),
    eventTypes: z.array(z.string()).describe("SANCTION = a conviction not delivered before; NEW_LISTING = a notice not delivered before; UPDATED = a record you already received whose case/notice page changed (a notice complied with, a revised compliance date, a breach or hearing added) - delta mode only. Applied by the delta engine, not by the site: changing it later does not fork the delta memory.").default(["SANCTION","NEW_LISTING","UPDATED"]),
    onlyNew: z.boolean().describe("Remembers every record it has delivered (per filter set, in a named key-value store) and returns only records that are new or whose page changed since. Convictions (~210 records) are always walked in full; notices stop at the first two pages of already-known records, so a scheduled run costs a few pages.").default(false),
    recheckDays: z.number().int().min(0).describe("In delta mode, known records that are still open (Improvement Notices with Result 'Ongoing', and every conviction) are re-read for this many days after they were first delivered (or after their register date, whichever is later) to detect UPDATED events - the register has no 'last updated' field, so this is the only way to see a notice being complied with or a hearing being added. 0 disables re-checks. Up to 2,000 records are re-checked per run.").default(180),
    deltaStateName: z.string().regex(new RegExp("^[A-Za-z0-9-]{1,30}$")).describe("Optional label for the memory of a monitoring task. Defaults to a fingerprint of your filters, so different schedules never interfere. Set the same name on two tasks to make them share one memory.").optional(),
    resetState: z.boolean().describe("Forget every previously delivered record for this delta state and re-baseline (the run then returns up to 'Max records per register' most recently entered records).").default(false),
    maxItemsPerDataset: z.number().int().min(1).describe("Hard cap on delivered records per selected register (and therefore on cost: you pay per record). On the very first delta run the cap defines the baseline: the oldest record that run delivers is remembered per register, and records entered before it are history - later delta runs never deliver or charge for them, whatever the cap (run once with onlyNew=false, or set a high cap on the first run, if you want the history). On every later delta run the overflow is a backlog: the walk remembers where it stopped (a per-register watermark in the delta memory) and the next run walks down to that point instead of stopping at the records already delivered.").default(100),
    fetchDetail: z.boolean().describe("Opens each record's own page for the description, dates, fine and costs, result, address, industry and HSE admin fields (plus, for convictions, the per-case breach list). Off = listing-row-only records (name, date, local authority, main activity, notice type) at the cheaper 'result-summary' price; no UPDATED detection is possible without it.").default(true),
    fetchBreachDetail: z.boolean().describe("Convictions: opens each breach's page for the court, Act section / Regulation paragraph, hearing date, result and per-breach fine. Notices: fetches the breach list (Act / regulation / paragraph per breach). Off = the cheaper 'result-summary' price.").default(true),
    fetchPartyDetail: z.boolean().describe("Opens the party's page (registered address, Status such as 'Private Company' or 'Individual', HSE Reference) and its case and notice lists on both registers - the repeat-offender signal (3 extra requests per record, no extra charge).").default(true),
    maxConcurrency: z.number().int().min(1).describe("Run-wide cap on simultaneous HTTP requests (listing, detail, breach and party pages together - never more than this in flight). The register is a classic-ASP site that answered 17 concurrent requests without throttling; 5 keeps a 100-record run around a minute.").default(5),
    dateRange: z.string().regex(new RegExp("^(24h|7d|30d)$")).describe("Kept for tasks created with version 1: '24h', '7d' or '30d' are interpreted as 'Date from'.").optional(),
    }),
  },
);
