import type { Actor } from './types'

// Real, deployed fleet data — every field here traces to the actor's live Apify Store listing
// (apify.com/stefano_seggio/<slug>) or its own repository README as of 2026-09-16. No actor,
// price, or event type on this page is invented.
//
// `updateFrequency` is deliberately the same string on every actor: every actor in this fleet
// runs on Apify's own Scheduler, configured per-run by whoever operates it — there is no fixed
// operator-side cadence to report, and printing a fake "every 6 hours" per actor would be a
// false precision claim on a live commercial page.
//
// `byok` is 'required' only for actors that cannot run at all without a customer-supplied
// third-party key (KIPRIS Plus), 'optional' where a customer key unlocks one enrichment tier or
// jurisdiction but the actor runs without one (actor-18's Hunter.io/PDL tier, actor-21's EPO
// coverage), and 'none' everywhere else — independently confirmed against each actor's own
// README pricing/BYOK disclosure section on 2026-09-16.
//
// `isPublic` was independently re-verified against the live Apify API (GET /v2/acts/{id}) for
// every actor added in the 2026-09-16 pass; all 24 actors in this fleet are live and public.
const SCHEDULE = 'Configurable — runs on your own Apify Scheduler (cron); no fixed operator cadence'

export const ACTORS: Actor[] = [
  {
    slug: 'actor-18-b2b-lead-magnet',
    title: 'B2B Lead Enrichment Engine',
    domain: 'B2B Data Enrichment',
    category: 'LEAD_GENERATION',
    jurisdiction: 'Global',
    dataSource: 'OpenStreetMap Overpass API + customer seed list (no Google Maps)',
    pricing: [
      { eventName: 'basic_lead', priceUsd: 0.002, unit: 'per lead' },
      { eventName: 'enriched_lead', priceUsd: 0.015, unit: 'per lead' },
    ],
    deltaEvents: [],
    storeUrl: 'https://apify.com/stefano_seggio/actor-18-b2b-lead-magnet',
    githubUrl: 'https://github.com/stefanoseggio/actor-18-b2b-lead-magnet',
    byok: 'optional',
    byokDetail: 'Optional Hunter.io / People Data Labs key unlocks the enriched_lead tier — basic_lead needs no key.',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'actor-19-maritime-sanctions-monitor',
    title: 'Maritime Sanctions Watchdog',
    domain: 'Sanctions & Trade Compliance',
    category: 'BUSINESS',
    jurisdiction: 'Global (OFAC / UN)',
    dataSource: 'OFAC SDN vessel list x UN Security Council Consolidated List (by IMO number)',
    pricing: [{ eventName: 'result', priceUsd: 0.0005, unit: 'per record' }],
    deltaEvents: ['NEW', 'STATUS_CHANGE', 'DELISTED'],
    storeUrl: 'https://apify.com/stefano_seggio/actor-19-maritime-sanctions-monitor',
    githubUrl: 'https://github.com/stefanoseggio/actor-19-maritime-sanctions-monitor',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'actor-20-mdb-procurement-monitor',
    title: 'World Bank Procurement & Debarment Monitor',
    domain: 'Development Finance Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Global (World Bank only — ADB / IDB excluded, see docs)',
    dataSource: 'World Bank Procurement Notices API + "Other Sanctions" debarred-firms table',
    pricing: [
      { eventName: 'result', priceUsd: 0.001, unit: 'per notice record' },
      { eventName: 'result', priceUsd: 0.003, unit: 'per debarred-firm record' },
    ],
    deltaEvents: ['NEW', 'STATUS_CHANGE'],
    storeUrl: 'https://apify.com/stefano_seggio/actor-20-mdb-procurement-monitor',
    githubUrl: 'https://github.com/stefanoseggio/actor-20-mdb-procurement-monitor',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'actor-21-patent-ip-enforcement-monitor',
    title: 'Patent & IP Enforcement Monitor',
    domain: 'Patent & IP Enforcement',
    category: 'BUSINESS',
    jurisdiction: 'US (USPTO, BYOK required) + optional EU (EPO, BYOK)',
    dataSource: 'USPTO PTAB proceedings (IPR/PGR/CBM/Derivation) + optional EPO opposition data',
    pricing: [
      { eventName: 'result', priceUsd: 0.002, unit: 'per record' },
      { eventName: 'compute', priceUsd: 0.25, unit: 'per CU-hour' },
    ],
    deltaEvents: ['NEW', 'TERMINATED'],
    storeUrl: 'https://apify.com/stefano_seggio/actor-21-patent-ip-enforcement-monitor',
    githubUrl: 'https://github.com/stefanoseggio/actor-21-patent-ip-enforcement-monitor',
    byok: 'required',
    byokDetail: 'Requires a free USPTO Open Data Portal (ODP) API key for USPTO PTAB coverage — confirmed as a hard runtime requirement in the actor\'s own source, not optional as earlier documented. An additional, separately optional EPO opposition-data key unlocks EU coverage on top of that.',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'actor-22-drug-safety-recalls-monitor',
    title: 'Drug Safety & Recall Monitor',
    domain: 'Pharma Safety & Clinical Trials',
    category: 'BUSINESS',
    jurisdiction: 'US (FDA) + EU (EMA)',
    dataSource: 'FDA openFDA drug enforcement API + EMA DHPC safety-alert feed',
    pricing: [{ eventName: 'result', priceUsd: 0.001, unit: 'per delivered record' }],
    deltaEvents: ['NEW'],
    storeUrl: 'https://apify.com/stefano_seggio/actor-22-drug-safety-recalls-monitor',
    githubUrl: 'https://github.com/stefanoseggio/actor-22-drug-safety-recalls-monitor',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'actor-24-clinical-trials-delta-engine',
    title: 'Clinical Trial Data Extractor',
    domain: 'Pharma Safety & Clinical Trials',
    category: 'BUSINESS',
    jurisdiction: 'Global (ClinicalTrials.gov) + US (FDA Orange Book)',
    dataSource: 'ClinicalTrials.gov API v2 + FDA Orange Book patent/exclusivity data',
    pricing: [
      { eventName: 'result', priceUsd: 0.002, unit: 'per record' },
      { eventName: 'actor-start', priceUsd: 0.00005, unit: 'per run start' },
    ],
    deltaEvents: ['NEW_TRIAL', 'STATUS_CHANGE'],
    storeUrl: 'https://apify.com/stefano_seggio/actor-24-clinical-trials-delta-engine',
    githubUrl: 'https://github.com/stefanoseggio/actor-24-clinical-trials-delta-engine',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'australia-grantconnect-monitor',
    title: 'Australian Government Grants Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Australia',
    dataSource: 'GrantConnect (grants.gov.au) — 360,000+ record register, no official API',
    pricing: [{ eventName: 'result', priceUsd: 0, unit: 'pay per result (see live Store pricing)' }],
    deltaEvents: ['NEW', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/australia-grantconnect-monitor',
    githubUrl: 'https://github.com/stefanoseggio/australia-grantconnect-monitor',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'cordoba-compras-monitor',
    title: 'Cordoba Government Tenders Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Province of Cordoba, Argentina',
    dataSource: "Province of Cordoba's official public-procurement portal",
    pricing: [{ eventName: 'result', priceUsd: 0, unit: 'pay per result (see live Store pricing)' }],
    deltaEvents: ['NEW', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/cordoba-compras-monitor',
    githubUrl: 'https://github.com/stefanoseggio/cordoba-compras-monitor',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'diario-oficial-cl-monitor',
    title: 'Chile Official Gazette Monitor',
    domain: 'Government Registers & Procurement',
    category: 'NEWS',
    jurisdiction: 'Chile (national)',
    dataSource: 'Diario Oficial de Chile — laws, decrees, resolutions',
    pricing: [{ eventName: 'result', priceUsd: 0.003, unit: 'per record' }],
    deltaEvents: ['NEW_LISTING', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/diario-oficial-cl-monitor',
    githubUrl: 'https://github.com/stefanoseggio/diario-oficial-cl-monitor',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'entrerios-compras-monitor',
    title: 'Entre Rios Government Tenders Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Province of Entre Rios, Argentina',
    dataSource: 'Unidad Central de Contrataciones — Province of Entre Rios',
    pricing: [{ eventName: 'result', priceUsd: 0, unit: 'pay per result (see live Store pricing)' }],
    deltaEvents: ['NEW', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/entrerios-compras-monitor',
    githubUrl: 'https://github.com/stefanoseggio/entrerios-compras-monitor',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'florida-tenders-monitor',
    title: 'Florida State Procurement Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Florida, United States',
    dataSource: 'MyFloridaMarketPlace (MFMP VBS) — ITB/RFP/ITN/RFI/RSQ solicitations',
    pricing: [
      { eventName: 'result', priceUsd: 0.003, unit: 'per full-detail record' },
      { eventName: 'result-summary', priceUsd: 0.001, unit: 'per listing-only record' },
    ],
    deltaEvents: ['NEW', 'AMENDED', 'CLOSED'],
    storeUrl: 'https://apify.com/stefano_seggio/florida-tenders-monitor',
    githubUrl: 'https://github.com/stefanoseggio/florida-tenders-monitor',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'mendoza-compras-monitor',
    title: 'Mendoza Government Tenders Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Province of Mendoza, Argentina',
    dataSource: 'COMPR.AR-based portal — Province of Mendoza',
    pricing: [{ eventName: 'result', priceUsd: 0, unit: 'pay per result (see live Store pricing)' }],
    deltaEvents: ['NEW', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/mendoza-compras-monitor',
    githubUrl: 'https://github.com/stefanoseggio/mendoza-compras-monitor',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'pba-tenders-monitor',
    title: 'Buenos Aires Province Tenders Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Buenos Aires Province, Argentina (PBA — not CABA, not national)',
    dataSource: 'PBAC — official procurement portal of Buenos Aires Province',
    pricing: [{ eventName: 'result', priceUsd: 0, unit: 'pay per result (see live Store pricing)' }],
    deltaEvents: ['NEW', 'STATUS_CHANGE'],
    storeUrl: 'https://apify.com/stefano_seggio/pba-tenders-monitor',
    githubUrl: 'https://github.com/stefanoseggio/pba-tenders-monitor',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'page-metadata-extractor',
    title: 'Page Metadata Extractor (CleanMeta)',
    domain: 'SEO & Data Pipelines',
    category: 'SEO_TOOLS',
    jurisdiction: 'Global',
    dataSource: 'Any target URL — title, description, canonical, Open Graph, H1, word count',
    pricing: [{ eventName: 'result', priceUsd: 0.0005, unit: 'per result (never per wasted run)' }],
    deltaEvents: [],
    storeUrl: 'https://apify.com/stefano_seggio/page-metadata-extractor',
    githubUrl: 'https://github.com/stefanoseggio/primer-actor',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'salta-compras-monitor',
    title: 'Salta Government Tenders Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Province of Salta, Argentina',
    dataSource: "Province of Salta's official public-procurement portal",
    pricing: [
      { eventName: 'result', priceUsd: 0.003, unit: 'per full-detail record' },
      { eventName: 'result-summary', priceUsd: 0.001, unit: 'per listing-only record' },
    ],
    deltaEvents: ['NEW', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/salta-compras-monitor',
    githubUrl: 'https://github.com/stefanoseggio/salta-compras-monitor',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'santafe-compras-monitor',
    title: 'Santa Fe Government Tenders Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Province of Santa Fe, Argentina',
    dataSource: 'Province of Santa Fe portal — ministries and hospitals',
    pricing: [
      { eventName: 'result', priceUsd: 0.003, unit: 'per full-detail record' },
      { eventName: 'result-summary', priceUsd: 0.001, unit: 'per listing-only record' },
    ],
    deltaEvents: ['NEW', 'STATUS_CHANGE', 'AMENDED'],
    storeUrl: 'https://apify.com/stefano_seggio/santafe-compras-monitor',
    githubUrl: 'https://github.com/stefanoseggio/santafe-compras-monitor',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'tucuman-compras-monitor',
    title: 'Tucuman Government Tenders Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Province of Tucuman, Argentina',
    dataSource: "Province of Tucuman's official public-procurement portal",
    pricing: [{ eventName: 'result', priceUsd: 0.003, unit: 'per result' }],
    deltaEvents: ['NEW', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/tucuman-compras-monitor',
    githubUrl: 'https://github.com/stefanoseggio/tucuman-compras-monitor',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'uk-hse-enforcement-monitor',
    title: 'UK HSE Enforcement Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'United Kingdom',
    dataSource: 'UK Health & Safety Executive — convictions and enforcement notices',
    pricing: [
      { eventName: 'result', priceUsd: 0.003, unit: 'per detail-enriched record' },
      { eventName: 'result-summary', priceUsd: 0.001, unit: 'per listing-only record' },
    ],
    deltaEvents: ['NEW', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/uk-hse-enforcement-monitor',
    githubUrl: 'https://github.com/stefanoseggio/uk-hse-enforcement-monitor',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },

  // --- Added 2026-09-16: 6 actors that brought the fleet from 18 to 24. Pricing/BYOK/delta
  // events below are read directly from each actor's own README "Pricing (Pay-Per-Event)" and
  // BYOK-disclosure sections; isPublic independently re-verified against the live Apify API.
  {
    slug: 'kipris-patent-trademark-status-monitor',
    title: 'KIPRIS Patent & Trademark Monitor',
    domain: 'Patent & IP Enforcement',
    category: 'BUSINESS',
    jurisdiction: 'South Korea (KIPRIS Plus)',
    dataSource: 'KIPRIS Plus Open API — Korean patent & utility-model filings by applicant or application number',
    pricing: [
      { eventName: 'result', priceUsd: 0.02, unit: 'per new filing or status change' },
      { eventName: 'result-summary', priceUsd: 0.008, unit: 'per non-status field update' },
    ],
    deltaEvents: ['NEW_APPLICATION', 'STATUS_CHANGE', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/kipris-patent-trademark-status-monitor',
    githubUrl: 'https://github.com/stefanoseggio/kipris-patent-trademark-status-monitor',
    byok: 'required',
    byokDetail: 'Requires your own KIPRIS Plus service key — a paid annual license billed directly by KIPRIS, never pooled or resold.',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'singapore-acra-registry-monitor',
    title: 'Singapore ACRA Registry Monitor',
    domain: 'Corporate Registries',
    category: 'BUSINESS',
    jurisdiction: 'Singapore',
    dataSource: 'data.gov.sg ACRA Collection 2 — full-field Singapore corporate register (~2.1M entities, UEN-indexed)',
    pricing: [
      { eventName: 'result', priceUsd: 0.03, unit: 'per NEW_LISTING or STATUS_CHANGE record' },
      { eventName: 'result-summary', priceUsd: 0.01, unit: 'per UPDATED record' },
    ],
    deltaEvents: ['NEW_LISTING', 'STATUS_CHANGE', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/singapore-acra-registry-monitor',
    githubUrl: 'https://github.com/stefanoseggio/singapore-acra-registry-monitor',
    byok: 'optional',
    byokDetail: 'Optional customer-supplied ACRA Business Profile API key unlocks real-time watchlist refresh on top of the default Collection 2 dataset.',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'sec-enforcement-litigation-delta-feed',
    title: 'SEC Enforcement & Litigation Feed',
    domain: 'Securities & Financial Enforcement',
    category: 'BUSINESS',
    jurisdiction: 'United States (SEC)',
    dataSource: 'SEC.gov litigation-release & administrative-proceeding RSS feeds + EDGAR CIK resolution',
    pricing: [
      { eventName: 'result', priceUsd: 0.05, unit: 'per new enforcement release' },
      { eventName: 'result-summary', priceUsd: 0.02, unit: 'per updated release' },
    ],
    deltaEvents: ['NEW_LISTING', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/sec-enforcement-litigation-delta-feed',
    githubUrl: 'https://github.com/stefanoseggio/sec-enforcement-litigation-delta-feed',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'ai-crawler-content-signal-permission-monitor',
    title: 'AI Crawler Permission Monitor',
    domain: 'AI Crawler & Content Governance',
    category: 'SEO_TOOLS',
    jurisdiction: 'Global',
    dataSource: 'robots.txt AI-crawler directives + Cloudflare Content-Signal header + llms.txt / llms-full.txt, any domain',
    pricing: [
      { eventName: 'result', priceUsd: 0.015, unit: 'per ALLOWED/DISALLOWED directive flip' },
      { eventName: 'result-summary', priceUsd: 0.006, unit: 'per Content-Signal or llms.txt change' },
    ],
    deltaEvents: ['ALLOWED', 'DISALLOWED', 'CHANGED'],
    storeUrl: 'https://apify.com/stefano_seggio/ai-crawler-content-signal-permission-monitor',
    githubUrl: 'https://github.com/stefanoseggio/ai-crawler-content-signal-permission-monitor',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'aozora-bunko-public-domain-text-feed',
    title: 'Aozora Bunko Public-Domain Feed',
    domain: 'Digital Archives & Publishing',
    category: 'BUSINESS',
    jurisdiction: 'Japan (Aozora Bunko catalog)',
    dataSource: "Aozora Bunko's official catalog export — 19,502-row confirmed-public-domain Japanese literature index",
    pricing: [
      { eventName: 'result', priceUsd: 0.05, unit: 'per new full-text delivery' },
      { eventName: 'result-summary', priceUsd: 0.01, unit: 'per metadata-only change or status change' },
    ],
    deltaEvents: ['NEW_TEXT', 'STATUS_CHANGE', 'REVISED_TEXT'],
    storeUrl: 'https://apify.com/stefano_seggio/aozora-bunko-public-domain-text-feed',
    githubUrl: 'https://github.com/stefanoseggio/aozora-bunko-public-domain-text-feed',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
  {
    slug: 'regione-lombardia-grants-registry-monitor',
    title: 'Lombardy Grants & Tenders Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Lombardy, Italy',
    dataSource: 'dati.lombardia.it Socrata SODA API — Anagrafica dei bandi regionali (~1,912 bandi)',
    pricing: [
      { eventName: 'result', priceUsd: 0.02, unit: 'per NEW_LISTING or STATUS_CHANGE record' },
      { eventName: 'result-summary', priceUsd: 0.008, unit: 'per UPDATED record' },
    ],
    deltaEvents: ['NEW_LISTING', 'STATUS_CHANGE', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/regione-lombardia-grants-registry-monitor',
    githubUrl: 'https://github.com/stefanoseggio/regione-lombardia-grants-registry-monitor',
    byok: 'none',
    updateFrequency: SCHEDULE,
    isPublic: true,
  },
]

export const ACTOR_COUNT = ACTORS.length

export const DOMAINS = Array.from(new Set(ACTORS.map((a) => a.domain)))

// Real GitHub repo count for github.com/stefanoseggio, independently re-verified via
// `gh api users/stefanoseggio/repos` on 2026-09-16 — not derived from ACTORS.length, since
// several repos (distribution/profile/GTM tooling) aren't actor wrappers at all.
export const GITHUB_REPO_COUNT = 34

// Real values with a "pricing not independently re-verified for this figure" placeholder
// (priceUsd: 0) are rendered on the site as "See live Store pricing →" rather than "$0.00" —
// handled in components/ArchitectureMatrix.tsx. Nothing is displayed as a false $0 price.
