import type { Actor } from './types'

// Real, deployed fleet data — every field here traces to the actor's live Apify Store listing
// (apify.com/stefano_seggio/<slug>) as of 2026-09-09. No actor, price, or event type on this page
// is invented. Where a value isn't independently re-verified in this file, it is not included.
export const ACTORS: Actor[] = [
  {
    slug: 'actor-18-b2b-lead-magnet',
    title: 'B2B Lead Enrichment Engine',
    domain: 'B2B Data Enrichment',
    category: 'LEAD_GENERATION',
    jurisdiction: 'Global',
    dataSource: 'OpenStreetMap Overpass API + customer seed list (no Google Maps)',
    pricing: [
      { eventName: 'basic_lead', priceUsd: 0.002, unit: 'per lead' },
      { eventName: 'enriched_lead', priceUsd: 0.015, unit: 'per lead' },
    ],
    deltaEvents: [],
    storeUrl: 'https://apify.com/stefano_seggio/actor-18-b2b-lead-magnet',
  },
  {
    slug: 'actor-19-maritime-sanctions-monitor',
    title: 'Maritime Sanctions Watchdog',
    domain: 'Sanctions & Trade Compliance',
    category: 'BUSINESS',
    jurisdiction: 'Global (OFAC / UN)',
    dataSource: 'OFAC SDN vessel list x UN Security Council Consolidated List (by IMO number)',
    pricing: [{ eventName: 'result', priceUsd: 0.0005, unit: 'per record' }],
    deltaEvents: ['NEW', 'STATUS_CHANGE', 'DELISTED'],
    storeUrl: 'https://apify.com/stefano_seggio/actor-19-maritime-sanctions-monitor',
  },
  {
    slug: 'actor-20-mdb-procurement-monitor',
    title: 'World Bank Procurement & Debarment Monitor',
    domain: 'Development Finance Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Global (World Bank only — ADB / IDB excluded, see docs)',
    dataSource: 'World Bank Procurement Notices API + "Other Sanctions" debarred-firms table',
    pricing: [
      { eventName: 'result', priceUsd: 0.001, unit: 'per notice record' },
      { eventName: 'result', priceUsd: 0.003, unit: 'per debarred-firm record' },
    ],
    deltaEvents: ['NEW', 'STATUS_CHANGE'],
    storeUrl: 'https://apify.com/stefano_seggio/actor-20-mdb-procurement-monitor',
  },
  {
    slug: 'actor-21-patent-ip-enforcement-monitor',
    title: 'Patent & IP Enforcement Monitor',
    domain: 'Patent & IP Enforcement',
    category: 'BUSINESS',
    jurisdiction: 'US (USPTO) + optional EU (EPO, BYOK)',
    dataSource: 'USPTO PTAB proceedings (IPR/PGR/CBM/Derivation) + optional EPO opposition data',
    pricing: [
      { eventName: 'result', priceUsd: 0.002, unit: 'per record' },
      { eventName: 'compute', priceUsd: 0.25, unit: 'per CU-hour' },
    ],
    deltaEvents: ['NEW', 'TERMINATED'],
    storeUrl: 'https://apify.com/stefano_seggio/actor-21-patent-ip-enforcement-monitor',
  },
  {
    slug: 'actor-22-drug-safety-recalls-monitor',
    title: 'Drug Safety & Recall Monitor',
    domain: 'Pharma Safety & Clinical Trials',
    category: 'BUSINESS',
    jurisdiction: 'US (FDA) + EU (EMA)',
    dataSource: 'FDA openFDA drug enforcement API + EMA DHPC safety-alert feed',
    pricing: [{ eventName: 'result', priceUsd: 0.001, unit: 'per delivered record' }],
    deltaEvents: ['NEW'],
    storeUrl: 'https://apify.com/stefano_seggio/actor-22-drug-safety-recalls-monitor',
  },
  {
    slug: 'actor-24-clinical-trials-delta-engine',
    title: 'Clinical Trial Data Extractor',
    domain: 'Pharma Safety & Clinical Trials',
    category: 'BUSINESS',
    jurisdiction: 'Global (ClinicalTrials.gov) + US (FDA Orange Book)',
    dataSource: 'ClinicalTrials.gov API v2 + FDA Orange Book patent/exclusivity data',
    pricing: [
      { eventName: 'result', priceUsd: 0.002, unit: 'per record' },
      { eventName: 'actor-start', priceUsd: 0.00005, unit: 'per run start' },
    ],
    deltaEvents: ['NEW_TRIAL', 'STATUS_CHANGE'],
    storeUrl: 'https://apify.com/stefano_seggio/actor-24-clinical-trials-delta-engine',
  },
  {
    slug: 'australia-grantconnect-monitor',
    title: 'Australian Government Grants Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Australia',
    dataSource: 'GrantConnect (grants.gov.au) — 360,000+ record register, no official API',
    pricing: [{ eventName: 'result', priceUsd: 0, unit: 'pay per result (see live Store pricing)' }],
    deltaEvents: ['NEW', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/australia-grantconnect-monitor',
  },
  {
    slug: 'cordoba-compras-monitor',
    title: 'Cordoba Government Tenders Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Province of Cordoba, Argentina',
    dataSource: "Province of Cordoba's official public-procurement portal",
    pricing: [{ eventName: 'result', priceUsd: 0, unit: 'pay per result (see live Store pricing)' }],
    deltaEvents: ['NEW', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/cordoba-compras-monitor',
  },
  {
    slug: 'diario-oficial-cl-monitor',
    title: 'Chile Official Gazette Monitor',
    domain: 'Government Registers & Procurement',
    category: 'NEWS',
    jurisdiction: 'Chile (national)',
    dataSource: 'Diario Oficial de Chile — laws, decrees, resolutions',
    pricing: [{ eventName: 'result', priceUsd: 0.003, unit: 'per record' }],
    deltaEvents: ['NEW_LISTING', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/diario-oficial-cl-monitor',
  },
  {
    slug: 'entrerios-compras-monitor',
    title: 'Entre Rios Government Tenders Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Province of Entre Rios, Argentina',
    dataSource: 'Unidad Central de Contrataciones — Province of Entre Rios',
    pricing: [{ eventName: 'result', priceUsd: 0, unit: 'pay per result (see live Store pricing)' }],
    deltaEvents: ['NEW', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/entrerios-compras-monitor',
  },
  {
    slug: 'florida-tenders-monitor',
    title: 'Florida State Procurement Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Florida, United States',
    dataSource: 'MyFloridaMarketPlace (MFMP VBS) — ITB/RFP/ITN/RFI/RSQ solicitations',
    pricing: [
      { eventName: 'result', priceUsd: 0.003, unit: 'per full-detail record' },
      { eventName: 'result-summary', priceUsd: 0.001, unit: 'per listing-only record' },
    ],
    deltaEvents: ['NEW', 'AMENDED', 'CLOSED'],
    storeUrl: 'https://apify.com/stefano_seggio/florida-tenders-monitor',
  },
  {
    slug: 'mendoza-compras-monitor',
    title: 'Mendoza Government Tenders Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Province of Mendoza, Argentina',
    dataSource: 'COMPR.AR-based portal — Province of Mendoza',
    pricing: [{ eventName: 'result', priceUsd: 0, unit: 'pay per result (see live Store pricing)' }],
    deltaEvents: ['NEW', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/mendoza-compras-monitor',
  },
  {
    slug: 'pba-tenders-monitor',
    title: 'Buenos Aires Province Tenders Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Buenos Aires Province, Argentina (PBA — not CABA, not national)',
    dataSource: 'PBAC — official procurement portal of Buenos Aires Province',
    pricing: [{ eventName: 'result', priceUsd: 0, unit: 'pay per result (see live Store pricing)' }],
    deltaEvents: ['NEW', 'STATUS_CHANGE'],
    storeUrl: 'https://apify.com/stefano_seggio/pba-tenders-monitor',
  },
  {
    slug: 'primer-actor',
    title: 'Page Metadata Extractor (CleanMeta)',
    domain: 'SEO & Data Pipelines',
    category: 'SEO_TOOLS',
    jurisdiction: 'Global',
    dataSource: 'Any target URL — title, description, canonical, Open Graph, H1, word count',
    pricing: [{ eventName: 'result', priceUsd: 0.0005, unit: 'per result (never per wasted run)' }],
    deltaEvents: [],
    storeUrl: 'https://apify.com/stefano_seggio/primer-actor',
  },
  {
    slug: 'salta-compras-monitor',
    title: 'Salta Government Tenders Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Province of Salta, Argentina',
    dataSource: "Province of Salta's official public-procurement portal",
    pricing: [{ eventName: 'result', priceUsd: 0, unit: 'pay per result (see live Store pricing)' }],
    deltaEvents: ['NEW', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/salta-compras-monitor',
  },
  {
    slug: 'santafe-compras-monitor',
    title: 'Santa Fe Government Tenders Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Province of Santa Fe, Argentina',
    dataSource: 'Province of Santa Fe portal — ministries and hospitals',
    pricing: [
      { eventName: 'result', priceUsd: 0.003, unit: 'per full-detail record' },
      { eventName: 'result-summary', priceUsd: 0.001, unit: 'per listing-only record' },
    ],
    deltaEvents: ['NEW', 'STATUS_CHANGE', 'AMENDED'],
    storeUrl: 'https://apify.com/stefano_seggio/santafe-compras-monitor',
  },
  {
    slug: 'tucuman-compras-monitor',
    title: 'Tucuman Government Tenders Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'Province of Tucuman, Argentina',
    dataSource: "Province of Tucuman's official public-procurement portal",
    pricing: [{ eventName: 'result', priceUsd: 0, unit: 'pay per result (see live Store pricing)' }],
    deltaEvents: ['NEW', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/tucuman-compras-monitor',
  },
  {
    slug: 'uk-hse-enforcement-monitor',
    title: 'UK HSE Enforcement Monitor',
    domain: 'Government Registers & Procurement',
    category: 'BUSINESS',
    jurisdiction: 'United Kingdom',
    dataSource: 'UK Health & Safety Executive — convictions and enforcement notices',
    pricing: [
      { eventName: 'result', priceUsd: 0.003, unit: 'per detail-enriched record' },
      { eventName: 'result-summary', priceUsd: 0.001, unit: 'per listing-only record' },
    ],
    deltaEvents: ['NEW', 'UPDATED'],
    storeUrl: 'https://apify.com/stefano_seggio/uk-hse-enforcement-monitor',
  },
]

export const ACTOR_COUNT = ACTORS.length

export const DOMAINS = Array.from(new Set(ACTORS.map((a) => a.domain)))

// Real values with a "pricing not independently re-verified for this figure" placeholder
// (priceUsd: 0) are rendered on the site as "See live Store pricing →" rather than "$0.00" —
// handled in components/ArchitectureMatrix.tsx. Nothing is displayed as a false $0 price.
