"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'actor-18-b2b-lead-magnet' (local .actor/input_schema.json), generated 2026-09-18.
Regenerate with: node generate-all.js
"""
import os
from typing import Optional

import requests
from pydantic import BaseModel, Field
from langchain_core.tools import StructuredTool

APIFY_ACTOR_ID = '5QufcYxRkFNHM4h8K'  # stefano_seggio/actor-18-b2b-lead-magnet
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


class Actor18B2bLeadMagnetInput(BaseModel):
    """Mirrors actor-18-b2b-lead-magnet's real .actor/input_schema.json field-for-field."""

    discoveryMode: Optional[str] = Field(default="seedList", description='seedList (Mode A): enrich the company names/domains you supply directly - zero discovery-layer risk. osmOverpass (Mode B): discover candidate businesses from OpenStreetMap\'s Overpass API within a bounding box (ODbL-licensed - Google Maps is intentionally excluded from discovery because its Maps/Earth Additional ToS and Maps Platform ToS both prohibit building a business-listings/mailing-list database from Maps content).')
    seedList: Optional[list[str]] = Field(default=[], description='Company names or website domains/URLs to enrich directly. Required (non-empty) when discoveryMode is "seedList". Mixed entries are fine - each is heuristically read as either a bare name ("Acme Corp") or a domain/URL ("acme.com", "https://acme.com").')
    overpassBbox: Optional[str] = Field(default=None, description='"south,west,north,east" in decimal degrees, e.g. "50.70,-1.90,50.90,-1.30". Required when discoveryMode is "osmOverpass". Queries the public overpass-api.de mirror, which is fair-use only - budget a self-hosted Overpass instance for production volume.')
    maxLeads: Optional[int] = Field(default=50, ge=1, description='Hard cap on how many candidates are enriched and charged this run.')
    includeIntentScore: Optional[bool] = Field(default=False, description='When enabled, each lead gets one Claude Haiku 4.5 call scoring hiring-page, funding-news, and tech-stack signals read only from the business\'s own crawled site text (always paired with a mandatory disclaimer field - a heuristic read of public text, never a verified fact). Bills the enriched_lead PPE event ($0.015/record) instead of basic_lead ($0.002/record). Requires this Actor\'s own ANTHROPIC_API_KEY environment variable to be configured on the Actor - this is the operator\'s own compute cost (priced into the Enriched Lead rate), not a customer BYOK field.')
    hunterApiKey: Optional[str] = Field(default=None, description='Your own Hunter.io API key. When supplied, this actor calls Hunter.io\'s domain-search endpoint using YOUR key - Hunter.io bills your own account directly, never this actor\'s own PPE price.')
    peopleDataLabsApiKey: Optional[str] = Field(default=None, description='Your own People Data Labs API key, used and billed the same way as hunterApiKey - your own account is charged by People Data Labs directly.')
    skipKnownLeads: Optional[bool] = Field(default=False, description='When enabled, a lead already discovered (and charged for) in a prior run of this Actor is skipped before the enrichment waterfall runs - no repeat website crawl, no repeat BYOK/intent-score calls, and no repeat basic_lead/enriched_lead charge for the same business. Identity is a stable id derived from the OSM id (Mode B) or normalized name+domain (Mode A), persisted in this Actor\'s own key-value store across runs. Leave off (default) for a full re-enrichment on every run, e.g. if a business\'s own site content may have changed since last time.')


def _run_actor_18_b2b_lead_magnet(discoveryMode: Optional[str] = None, seedList: Optional[list[str]] = None, overpassBbox: Optional[str] = None, maxLeads: Optional[int] = None, includeIntentScore: Optional[bool] = None, hunterApiKey: Optional[str] = None, peopleDataLabsApiKey: Optional[str] = None, skipKnownLeads: Optional[bool] = None) -> list[dict]:
    token = os.environ["APIFY_TOKEN"]  # never hardcode the token
    payload = {
        **({"discoveryMode": discoveryMode} if discoveryMode is not None else {}),
        **({"seedList": seedList} if seedList is not None else {}),
        **({"overpassBbox": overpassBbox} if overpassBbox is not None else {}),
        **({"maxLeads": maxLeads} if maxLeads is not None else {}),
        **({"includeIntentScore": includeIntentScore} if includeIntentScore is not None else {}),
        **({"hunterApiKey": hunterApiKey} if hunterApiKey is not None else {}),
        **({"peopleDataLabsApiKey": peopleDataLabsApiKey} if peopleDataLabsApiKey is not None else {}),
        **({"skipKnownLeads": skipKnownLeads} if skipKnownLeads is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.json()  # dataset items array, returned directly


run_actor_18_b2b_lead_magnet_tool = StructuredTool.from_function(
    func=_run_actor_18_b2b_lead_magnet,
    name='actor-18-b2b-lead-magnet',
    description='Discovers B2B leads from your own seed list or OpenStreetMap\'s Overpass API (Google Maps excluded on ToS grounds), crawls each site for contact emails, verifies plausibility via DNS/MX, supports BYOK Hunter.io/People Data Labs enrichment, and optionally scores buying intent with Claude Haiku 4.5.',
    args_schema=Actor18B2bLeadMagnetInput,
)
