// Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
// Source: Apify actor 'actor-18-b2b-lead-magnet' (local .actor/input_schema.json), generated 2026-09-18.
// Regenerate with: node generate-all.js
import { tool } from "langchain";
import * as z from "zod";

const APIFY_ACTOR_ID = "5QufcYxRkFNHM4h8K"; // stefano_seggio/actor-18-b2b-lead-magnet

export const actor18B2bLeadMagnetTool = tool(
  async (input) => {
    const token = process.env.APIFY_TOKEN;
    if (!token) throw new Error("APIFY_TOKEN is not set");
    const res = await fetch(
      `https://api.apify.com/v2/acts/${APIFY_ACTOR_ID}/run-sync-get-dataset-items?token=${token}`,
      { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) },
    );
    if (!res.ok) throw new Error(`Apify run failed: ${res.status} ${res.statusText}`);
    return res.json(); // dataset items array, returned directly
  },
  {
    name: "actor-18-b2b-lead-magnet",
    description: "Discovers B2B leads from your own seed list or OpenStreetMap's Overpass API (Google Maps excluded on ToS grounds), crawls each site for contact emails, verifies plausibility via DNS/MX, supports BYOK Hunter.io/People Data Labs enrichment, and optionally scores buying intent with Claude Haiku 4.5.",
    schema: z.object({
    discoveryMode: z.enum(["seedList", "osmOverpass"]).describe("seedList (Mode A): enrich the company names/domains you supply directly - zero discovery-layer risk. osmOverpass (Mode B): discover candidate businesses from OpenStreetMap's Overpass API within a bounding box (ODbL-licensed - Google Maps is intentionally excluded from discovery because its Maps/Earth Additional ToS and Maps Platform ToS both prohibit building a business-listings/mailing-list database from Maps content).").default("seedList"),
    seedList: z.array(z.string()).describe("Company names or website domains/URLs to enrich directly. Required (non-empty) when discoveryMode is \"seedList\". Mixed entries are fine - each is heuristically read as either a bare name (\"Acme Corp\") or a domain/URL (\"acme.com\", \"https://acme.com\").").default([]),
    overpassBbox: z.string().describe("\"south,west,north,east\" in decimal degrees, e.g. \"50.70,-1.90,50.90,-1.30\". Required when discoveryMode is \"osmOverpass\". Queries the public overpass-api.de mirror, which is fair-use only - budget a self-hosted Overpass instance for production volume.").optional(),
    maxLeads: z.number().int().min(1).describe("Hard cap on how many candidates are enriched and charged this run.").default(50),
    includeIntentScore: z.boolean().describe("When enabled, each lead gets one Claude Haiku 4.5 call scoring hiring-page, funding-news, and tech-stack signals read only from the business's own crawled site text (always paired with a mandatory disclaimer field - a heuristic read of public text, never a verified fact). Bills the enriched_lead PPE event ($0.015/record) instead of basic_lead ($0.002/record). Requires this Actor's own ANTHROPIC_API_KEY environment variable to be configured on the Actor - this is the operator's own compute cost (priced into the Enriched Lead rate), not a customer BYOK field.").default(false),
    hunterApiKey: z.string().describe("Your own Hunter.io API key. When supplied, this actor calls Hunter.io's domain-search endpoint using YOUR key - Hunter.io bills your own account directly, never this actor's own PPE price.").optional(),
    peopleDataLabsApiKey: z.string().describe("Your own People Data Labs API key, used and billed the same way as hunterApiKey - your own account is charged by People Data Labs directly.").optional(),
    skipKnownLeads: z.boolean().describe("When enabled, a lead already discovered (and charged for) in a prior run of this Actor is skipped before the enrichment waterfall runs - no repeat website crawl, no repeat BYOK/intent-score calls, and no repeat basic_lead/enriched_lead charge for the same business. Identity is a stable id derived from the OSM id (Mode B) or normalized name+domain (Mode A), persisted in this Actor's own key-value store across runs. Leave off (default) for a full re-enrichment on every run, e.g. if a business's own site content may have changed since last time.").default(false),
    }),
  },
);
