"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'entrerios-compras-monitor' (local .actor/input_schema.json), generated 2026-09-18.
Regenerate with: node generate-all.js

NOTE: this targets AG2 Classic (import autogen), the AutoGen-lineage conversational-agent API.
"AutoGen" itself is in Microsoft-maintenance mode as of 2026; AG2 (ag2ai/ag2) is the actively
developed continuation. AG2 also has a newer, separate v1.0 protocol-driven surface (shipped
2026-09-11) not covered here because its docs could not be verified at generation time.
"""
import os
from typing import Annotated, Optional

import requests
from autogen import ConversableAgent, register_function, LLMConfig

APIFY_ACTOR_ID = 'oiXeFzZGlIQ6mKgoo'  # stefano_seggio/entrerios-compras-monitor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


def run_entrerios_compras_monitor(
    estado: Annotated[Optional[str], 'Filter by process status. Leave blank (default) to pull every status in one request - the site\'s own union of all 4, verified live to be far larger than any single status alone.'] = "",
    tipoLicitacion: Annotated[Optional[str], 'Filter by contracting procedure type. Leave blank for all types.'] = "",
    organismo: Annotated[Optional[str], 'Filter by issuing organism. Leave blank for all organisms.'] = "",
    anio: Annotated[Optional[str], 'Filter by year, e.g. "2025". Leave blank for all years (data goes back to at least 2004).'] = "",
    palabra: Annotated[Optional[str], 'Free-text keyword filter, matched server-side the same way the site\'s own "Palabra" search box works.'] = "",
    maxItems: Annotated[Optional[int], 'Hard cap on the number of tenders returned this run. The full unfiltered backlog is over 5000 rows (verified live) - narrow with the filters above or raise this cap to pull all of it.'] = 1000,
    onlyNew: Annotated[Optional[bool], 'For recurring/scheduled runs: return only tenders that are new, changed estado, or closed since a prior run of this actor (tracked in a named key-value store scoped to this actor, so it survives between scheduled runs). This source is fetched as a single unfiltered POST covering the entire backlog rather than genuine, reliably newest-first pagination (verified live - see AGENTS.md), so enabling this does NOT reduce fetch time or request volume: the full backlog is still fetched every run either way, and this only changes which records get pushed to the dataset afterward.'] = false,
    eventTypes: Annotated[Optional[list[str]], 'Which kinds of change to deliver when \'Only new records\' is on (ignored, everything delivered, when it is off). NEW_LISTING = never seen before. STATUS_CHANGE = seen before, estado changed - free to detect, record_id\'s own hash excludes estado on purpose. CLOSED = a previously-seen record_id is absent from this run\'s fetch - only computed on an UNFILTERED run (no status/type/organism/year/keyword filter set), since a filtered run\'s fetch is a subset of the register, not the whole thing; skipped otherwise.'] = ["NEW_LISTING","STATUS_CHANGE","CLOSED"],
    dateRange: Annotated[Optional[str], 'Filters to a source\'s own natural per-record date field, where one of this portfolio\'s monitor actors has one. This source (Entre Rios\' tender listing) publishes NO per-record date field anywhere - not on the listing, not on any detail page (there isn\'t one) - verified live against the real page (see AGENTS.md). Setting this has NO effect on the results returned; the actor logs a warning instead of silently applying a misleading filter. Present only for input-shape consistency with the rest of the portfolio.'] = "",
) -> str:
    """Extracts the full public tender backlog of the Province of Entre Rios, Argentina's Unidad Central de Contrataciones - 5,505 records verified live, back to at least 2004 - with organism, objeto, and status detail, and flags new, status-changed, and closed tenders across scheduled runs."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        **({"estado": estado} if estado is not None else {}),
        **({"tipoLicitacion": tipoLicitacion} if tipoLicitacion is not None else {}),
        **({"organismo": organismo} if organismo is not None else {}),
        **({"anio": anio} if anio is not None else {}),
        **({"palabra": palabra} if palabra is not None else {}),
        **({"maxItems": maxItems} if maxItems is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"eventTypes": eventTypes} if eventTypes is not None else {}),
        **({"dateRange": dateRange} if dateRange is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.text


# Wire into your own agents, e.g.:
#
# with LLMConfig(api_type="openai", model="gpt-4o-mini"):
#     compliance_agent = ConversableAgent(name="compliance_agent", system_message="...")
# executor_agent = ConversableAgent(name="executor_agent", human_input_mode="NEVER")
#
# register_function(
#     run_entrerios_compras_monitor,
#     caller=compliance_agent,
#     executor=executor_agent,
#     description='Extracts the full public tender backlog of the Province of Entre Rios, Argentina\'s Unidad Central de Contrataciones - 5,505 records verified live, back to at least 2004 - with organism, objeto, and status detail, and flags new, status-changed, and closed tenders across scheduled runs.',
# )
