"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'ai-crawler-content-signal-permission-monitor' (live Apify API), generated 2026-09-18.
Regenerate with: node generate-all.js

NOTE: this targets AG2 Classic (import autogen), the AutoGen-lineage conversational-agent API.
"AutoGen" itself is in Microsoft-maintenance mode as of 2026; AG2 (ag2ai/ag2) is the actively
developed continuation. AG2 also has a newer, separate v1.0 protocol-driven surface (shipped
2026-09-11) not covered here because its docs could not be verified at generation time.
"""
import os
from typing import Annotated, Optional

import requests
from autogen import ConversableAgent, register_function, LLMConfig

APIFY_ACTOR_ID = 'eWDx4XY54R5GXysFi'  # stefano_seggio/ai-crawler-content-signal-permission-monitor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


def run_ai_crawler_content_signal_permission_monitor(
    domains: Annotated[list[str], 'Bare hostnames to monitor - no protocol, no path, no trailing slash. Example: "cloudflare.com", "openai.com". Each domain is checked at its own https://{domain}/robots.txt (and, if enabled, /llms.txt and /llms-full.txt). Mix your own domains with competitor/vendor domains freely - each gets fully independent delta state.'],
    trackedBots: Annotated[Optional[list[str]], 'The robots.txt User-agent tokens whose Allow/Disallow directives are watched for changes over time. Defaults to 18 currently-documented AI-crawler tokens spanning OpenAI, Anthropic, Google, Apple, Perplexity, Common Crawl, ByteDance, Amazon, Meta, Diffbot, and Cohere. Add a newly-published crawler token, or narrow this to one vendor family, by editing this list.'] = ["GPTBot","ChatGPT-User","OAI-SearchBot","ClaudeBot","Claude-User","Claude-SearchBot","Google-Extended","Applebot-Extended","PerplexityBot","Perplexity-User","CCBot","Bytespider","Amazonbot","Meta-ExternalAgent","Meta-ExternalFetcher","Diffbot","cohere-ai","omgilibot"],
    checkContentSignals: Annotated[Optional[bool], 'Parses any "Content-Signal: search=..., ai-input=..., ai-train=..." line found in robots.txt (Cloudflare\'s proposed extension to the standard, formalized as the IETF draft draft-romm-aipref-contentsignals) and tracks all three category values for change over time. Turn this off only if you exclusively care about classic robots.txt Allow/Disallow directives.'] = true,
    checkLlmsTxt: Annotated[Optional[bool], 'Fetches both well-known paths (llmstxt.org\'s proposed convention) and tracks presence/absence plus a content hash, so an added, removed, or edited llms.txt is reported as a CHANGED event. llms.txt is an informal community proposal, not a ratified standard - this Actor reports its presence and content as a signal, never as a compliance guarantee.'] = true,
    onlyNew: Annotated[Optional[bool], 'When true (default), a repeat run of an already-baselined domain only delivers ALLOWED, DISALLOWED, and CHANGED events - the free NO_CHANGE row is suppressed when nothing differs. A domain\'s first-ever check always delivers a free BASELINE_SNAPSHOT regardless of this setting, since that is the point of adding a domain to the watchlist. Set to false to also see an explicit "nothing changed" row on every run.'] = true,
    maxDomainsPerRun: Annotated[Optional[int], 'Hard cap on how many domains from the list are checked (and, where applicable, charged) in a single run. Domains beyond this cap are simply checked on the next run - nothing about their state is lost or marked as seen.'] = 200,
    concurrency: Annotated[Optional[int], 'Caps the total number of in-flight HTTP requests across the whole run. Each domain fans out to up to three independent resource fetches (robots.txt, llms.txt, llms-full.txt), so this bounds total concurrent load across every domain being checked, not per-domain concurrency. Raise cautiously - most of the wall-clock cost of a large watchlist run is waiting on slow or unresponsive third-party domains, not this Actor\'s own compute.'] = 15,
    requestTimeoutSecs: Annotated[Optional[int], 'Aborts a single robots.txt/llms.txt/llms-full.txt request that takes longer than this, so one slow or unresponsive domain never stalls the whole run. Applies per individual attempt, not per domain overall.'] = 15,
    maxRetries: Annotated[Optional[int], 'Retry attempts (exponential backoff with jitter, capped at 15 seconds between attempts) before a single request is given up on as failed. Applies only to retryable outcomes (429 and 5xx responses, or a request timeout) - any other non-2xx, non-404 response is treated as final immediately and does not consume retry budget. A 404 is never a failure: it is parsed as a valid "resource absent" signal.'] = 4,
    deltaStateName: Annotated[Optional[str], 'Names this run\'s persistent delta-state store. Use a distinct name per independent schedule (for example "own-sites" versus "competitor-watchlist") so their baselines never cross-contaminate each other.'] = "default",
    resetState: Annotated[Optional[bool], 'Wipes all remembered state for every domain under this deltaStateName before the run starts, so every domain is re-baselined from scratch on this run (delivered as free BASELINE_SNAPSHOT records, subject to onlyNew\'s usual free-baseline behavior).'] = false,
) -> str:
    """Watches any domain and reports the instant its AI-crawler permissions change: a robots.txt Allow/Disallow flip for GPTBot, ClaudeBot and 15 other tracked tokens, a Cloudflare Content-Signal flip, or llms.txt appearing/changing. Pay-per-event: billed only for what changed, with a free baseline audit."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        "domains": domains,
        **({"trackedBots": trackedBots} if trackedBots is not None else {}),
        **({"checkContentSignals": checkContentSignals} if checkContentSignals is not None else {}),
        **({"checkLlmsTxt": checkLlmsTxt} if checkLlmsTxt is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"maxDomainsPerRun": maxDomainsPerRun} if maxDomainsPerRun is not None else {}),
        **({"concurrency": concurrency} if concurrency is not None else {}),
        **({"requestTimeoutSecs": requestTimeoutSecs} if requestTimeoutSecs is not None else {}),
        **({"maxRetries": maxRetries} if maxRetries is not None else {}),
        **({"deltaStateName": deltaStateName} if deltaStateName is not None else {}),
        **({"resetState": resetState} if resetState is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.text


# Wire into your own agents, e.g.:
#
# with LLMConfig(api_type="openai", model="gpt-4o-mini"):
#     compliance_agent = ConversableAgent(name="compliance_agent", system_message="...")
# executor_agent = ConversableAgent(name="executor_agent", human_input_mode="NEVER")
#
# register_function(
#     run_ai_crawler_content_signal_permission_monitor,
#     caller=compliance_agent,
#     executor=executor_agent,
#     description='Watches any domain and reports the instant its AI-crawler permissions change: a robots.txt Allow/Disallow flip for GPTBot, ClaudeBot and 15 other tracked tokens, a Cloudflare Content-Signal flip, or llms.txt appearing/changing. Pay-per-event: billed only for what changed, with a free baseline audit.',
# )
