"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'actor-20-mdb-procurement-monitor' (local .actor/input_schema.json), generated 2026-09-18.
Regenerate with: node generate-all.js

NOTE: this targets AG2 Classic (import autogen), the AutoGen-lineage conversational-agent API.
"AutoGen" itself is in Microsoft-maintenance mode as of 2026; AG2 (ag2ai/ag2) is the actively
developed continuation. AG2 also has a newer, separate v1.0 protocol-driven surface (shipped
2026-09-11) not covered here because its docs could not be verified at generation time.
"""
import os
from typing import Annotated, Optional

import requests
from autogen import ConversableAgent, register_function, LLMConfig

APIFY_ACTOR_ID = 'dyzTtWjfyYd7bvUZY'  # stefano_seggio/actor-20-mdb-procurement-monitor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


def run_actor_20_mdb_procurement_monitor(
    sources: Annotated[Optional[list[str]], 'worldBankProcurementNotices = the live World Bank Procurement Notices API (search.worldbank.org). worldBankDebarredFirms = the World Bank\'s static \'Other Sanctions\' debarment sub-table (worldbank.org). ADB and IDB are NOT selectable here - both were live-researched and found gated/non-compliant for v1 (Cloudflare/WAF for ADB; Power BI embed + robots.txt-blocked API for IDB) - see README.md.'] = ["worldBankProcurementNotices","worldBankDebarredFirms"],
    maxItemsPerSource: Annotated[Optional[int], 'Hard cap on how many records to return per selected source this run. For worldBankProcurementNotices this bounds rows/os pagination against a live corpus of several hundred thousand notices; for worldBankDebarredFirms it is a no-op ceiling since the \'Other Sanctions\' sub-table is a single small page.'] = 100,
    onlyNew: Annotated[Optional[bool], 'When enabled, persists a content fingerprint per Procurement Notice between runs (in this actor\'s own named key-value store) and returns only notices that are new since the last run OR whose notice_status or other tracked fields changed since they were last seen - notices identical to last time are skipped. is_new is always populated (true/false) regardless of this setting. Only applies to worldBankProcurementNotices - Other Sanctions has no delta-tracking concept (a small static snapshot page, not a dated/paginated feed). The World Bank Procurement Notices API documents no server-side \'since\' filter, so pagination always walks from the start of the result set each run - onlyNew filters client-side after the fact rather than early-stopping pagination.'] = false,
    countryFilter: Annotated[Optional[list[str]], 'Optional client-side filter on project_ctry_name (e.g. \'Kenya\', \'India\'). The World Bank API documents no server-side country filter parameter, so this is applied after fetching each page.'] = None,
    noticeTypeFilter: Annotated[Optional[list[str]], 'Optional client-side filter on notice_type (e.g. \'Invitation for Bids\', \'Request for Expression of Interest\', \'Contract Award\'). Applied after fetching each page, same caveat as countryFilter.'] = None,
    dateRange: Annotated[Optional[str], 'Optionally restrict procurement-notice results to records whose noticedate falls within this window. Not applied to worldBankDebarredFirms records (that source has no reliable per-record publish date field in the static sub-table).'] = None,
) -> str:
    """Monitors the World Bank's public Procurement Notices API and 'Other Sanctions' debarment table, normalizing records into a consistent 18-field schema with cross-run delta detection (new, status-changed, updated). World Bank only — ADB and IDB were researched and excluded as inaccessible."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        **({"sources": sources} if sources is not None else {}),
        **({"maxItemsPerSource": maxItemsPerSource} if maxItemsPerSource is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"countryFilter": countryFilter} if countryFilter is not None else {}),
        **({"noticeTypeFilter": noticeTypeFilter} if noticeTypeFilter is not None else {}),
        **({"dateRange": dateRange} if dateRange is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.text


# Wire into your own agents, e.g.:
#
# with LLMConfig(api_type="openai", model="gpt-4o-mini"):
#     compliance_agent = ConversableAgent(name="compliance_agent", system_message="...")
# executor_agent = ConversableAgent(name="executor_agent", human_input_mode="NEVER")
#
# register_function(
#     run_actor_20_mdb_procurement_monitor,
#     caller=compliance_agent,
#     executor=executor_agent,
#     description='Monitors the World Bank\'s public Procurement Notices API and \'Other Sanctions\' debarment table, normalizing records into a consistent 18-field schema with cross-run delta detection (new, status-changed, updated). World Bank only — ADB and IDB were researched and excluded as inaccessible.',
# )
