"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'salta-compras-monitor' (local .actor/input_schema.json), generated 2026-09-18.
Regenerate with: node generate-all.js

NOTE: this targets AG2 Classic (import autogen), the AutoGen-lineage conversational-agent API.
"AutoGen" itself is in Microsoft-maintenance mode as of 2026; AG2 (ag2ai/ag2) is the actively
developed continuation. AG2 also has a newer, separate v1.0 protocol-driven surface (shipped
2026-09-11) not covered here because its docs could not be verified at generation time.
"""
import os
from typing import Annotated, Optional

import requests
from autogen import ConversableAgent, register_function, LLMConfig

APIFY_ACTOR_ID = 'Tx9wBKZyySZa5WcsE'  # stefano_seggio/salta-compras-monitor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


def run_salta_compras_monitor(
    fetchDetail: Annotated[Optional[bool], 'When enabled (default), fetches each publication\'s detail page for the full field set (organismo gestor, costo pliego, lugar de entrega, when present) plus attached document links. Disable for a faster, listing-only run.'] = true,
    maxItems: Annotated[Optional[int], 'Hard cap on the number of publications returned this run. The portal serves ~250 currently-open (vigentes) publications at a time, 5 per page.'] = 100,
    onlyNew: Annotated[Optional[bool], 'Delta mode for daily/recurring monitoring: returns only publications that are new, changed (a fingerprinted amendment - a new monto, document, date...) or closed since a previous run. Seen ids are persisted across runs in a named key-value store unique to this actor ("salta-compras-monitor-delta-state"), not the run\'s own default store (which is isolated per run and would not survive between scheduled runs). Every record still carries is_new, so a normal (onlyNew=false) run also tells you which of its results are new. Pagination is NOT stopped early once already-seen records are reached: this actor\'s listing is sorted by Fecha/Hora Apertura (the bid-opening deadline), not by when a publication was created, so a genuinely new publication can appear on any page - onlyNew filters after a full fetch up to maxItems instead of short-circuiting it. See AGENTS.md for the live evidence behind this.'] = false,
    eventTypes: Annotated[Optional[list[str]], 'Which kinds of change to deliver when \'Only new\' is on (ignored, everything delivered, when it is off). NEW_LISTING = never seen before. UPDATED = seen before, a field changed (fingerprinted). CLOSED = a previously-seen publication is absent from a complete walk this run - no longer vigente. CLOSED detection only runs when maxItems does not truncate the walk (a partial walk cannot prove absence) - see AGENTS.md.'] = ["NEW_LISTING","UPDATED","CLOSED"],
    dateRange: Annotated[Optional[str], 'Filters results to publications whose own Fecha/Hora Apertura (bid-opening deadline - the only date field this source exposes anywhere, listing or detail; there is no separate publication date) falls within the given window. For the "vigentes" (currently open) publications this actor covers, that date is almost always in the FUTURE relative to when this actor runs, so this is an upcoming-deadline filter ("opens within the next 24h/7d/30d"), not a "published in the last N" filter. Independent of onlyNew.'] = None,
) -> str:
    """Extracts every currently open tender and contract award (licitaciones, adjudicaciones, contrataciones) from Salta Province, Argentina's official procurement portal, with organism, expediente, opening date/time and document links per publication. Delta mode flags new, amended and closed processes."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        **({"fetchDetail": fetchDetail} if fetchDetail is not None else {}),
        **({"maxItems": maxItems} if maxItems is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"eventTypes": eventTypes} if eventTypes is not None else {}),
        **({"dateRange": dateRange} if dateRange is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.text


# Wire into your own agents, e.g.:
#
# with LLMConfig(api_type="openai", model="gpt-4o-mini"):
#     compliance_agent = ConversableAgent(name="compliance_agent", system_message="...")
# executor_agent = ConversableAgent(name="executor_agent", human_input_mode="NEVER")
#
# register_function(
#     run_salta_compras_monitor,
#     caller=compliance_agent,
#     executor=executor_agent,
#     description='Extracts every currently open tender and contract award (licitaciones, adjudicaciones, contrataciones) from Salta Province, Argentina\'s official procurement portal, with organism, expediente, opening date/time and document links per publication. Delta mode flags new, amended and closed processes.',
# )
