// Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
// Source: Apify actor 'salta-compras-monitor' (local .actor/input_schema.json), generated 2026-09-18.
// Regenerate with: node generate-all.js
import { tool } from "langchain";
import * as z from "zod";

const APIFY_ACTOR_ID = "Tx9wBKZyySZa5WcsE"; // stefano_seggio/salta-compras-monitor

export const saltaComprasMonitorTool = tool(
  async (input) => {
    const token = process.env.APIFY_TOKEN;
    if (!token) throw new Error("APIFY_TOKEN is not set");
    const res = await fetch(
      `https://api.apify.com/v2/acts/${APIFY_ACTOR_ID}/run-sync-get-dataset-items?token=${token}`,
      { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) },
    );
    if (!res.ok) throw new Error(`Apify run failed: ${res.status} ${res.statusText}`);
    return res.json(); // dataset items array, returned directly
  },
  {
    name: "salta-compras-monitor",
    description: "Extracts every currently open tender and contract award (licitaciones, adjudicaciones, contrataciones) from Salta Province, Argentina's official procurement portal, with organism, expediente, opening date/time and document links per publication. Delta mode flags new, amended and closed processes.",
    schema: z.object({
    fetchDetail: z.boolean().describe("When enabled (default), fetches each publication's detail page for the full field set (organismo gestor, costo pliego, lugar de entrega, when present) plus attached document links. Disable for a faster, listing-only run.").default(true),
    maxItems: z.number().int().min(1).describe("Hard cap on the number of publications returned this run. The portal serves ~250 currently-open (vigentes) publications at a time, 5 per page.").default(100),
    onlyNew: z.boolean().describe("Delta mode for daily/recurring monitoring: returns only publications that are new, changed (a fingerprinted amendment - a new monto, document, date...) or closed since a previous run. Seen ids are persisted across runs in a named key-value store unique to this actor (\"salta-compras-monitor-delta-state\"), not the run's own default store (which is isolated per run and would not survive between scheduled runs). Every record still carries is_new, so a normal (onlyNew=false) run also tells you which of its results are new. Pagination is NOT stopped early once already-seen records are reached: this actor's listing is sorted by Fecha/Hora Apertura (the bid-opening deadline), not by when a publication was created, so a genuinely new publication can appear on any page - onlyNew filters after a full fetch up to maxItems instead of short-circuiting it. See AGENTS.md for the live evidence behind this.").default(false),
    eventTypes: z.array(z.string()).describe("Which kinds of change to deliver when 'Only new' is on (ignored, everything delivered, when it is off). NEW_LISTING = never seen before. UPDATED = seen before, a field changed (fingerprinted). CLOSED = a previously-seen publication is absent from a complete walk this run - no longer vigente. CLOSED detection only runs when maxItems does not truncate the walk (a partial walk cannot prove absence) - see AGENTS.md.").default(["NEW_LISTING","UPDATED","CLOSED"]),
    dateRange: z.enum(["24h", "7d", "30d"]).describe("Filters results to publications whose own Fecha/Hora Apertura (bid-opening deadline - the only date field this source exposes anywhere, listing or detail; there is no separate publication date) falls within the given window. For the \"vigentes\" (currently open) publications this actor covers, that date is almost always in the FUTURE relative to when this actor runs, so this is an upcoming-deadline filter (\"opens within the next 24h/7d/30d\"), not a \"published in the last N\" filter. Independent of onlyNew.").optional(),
    }),
  },
);
