"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'kipris-patent-trademark-status-monitor' (live Apify API), generated 2026-09-18.
Regenerate with: node generate-all.js

NOTE: this targets AG2 Classic (import autogen), the AutoGen-lineage conversational-agent API.
"AutoGen" itself is in Microsoft-maintenance mode as of 2026; AG2 (ag2ai/ag2) is the actively
developed continuation. AG2 also has a newer, separate v1.0 protocol-driven surface (shipped
2026-09-11) not covered here because its docs could not be verified at generation time.
"""
import os
from typing import Annotated, Optional

import requests
from autogen import ConversableAgent, register_function, LLMConfig

APIFY_ACTOR_ID = '9Wg73rplxFqgVq6fY'  # stefano_seggio/kipris-patent-trademark-status-monitor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


def run_kipris_patent_trademark_status_monitor(
    byoKiprisServiceKey: Annotated[str, 'KIPRIS Plus is a paid, registered product license (a flat annual fee, independently confirmed against the official KIPRIS Plus fee page - not free developer registration like USPTO/EPO). This Actor is deliberately bring-your-own-key: there is no operator-held shared key, by design, not as a stopgap - you hold your own KIPRIS Plus subscription and pay KIPRIS directly for API usage, which is what keeps this Actor\'s own per-event price low. Never logged or persisted beyond this run. Because this Actor\'s build could not obtain a paid key of its own, the exact field names in a successful KIPRIS Plus response were not independently verified against a real successful call - see README.'],
    watchlistApplicants: Annotated[Optional[list[str]], 'Applicant (출원인) legal names, Korean or English, e.g. "한빛전자 주식회사" or "Hanbit Electronics Co., Ltd.". Matched against KIPRIS Plus\'s applicant-name search field. Known limitation: Korean legal-entity names have romanization/translation variants, so name matching can miss or double-count filings.'] = [],
    watchlistApplicationNumbers: Annotated[Optional[list[str]], 'Exact KIPO-format application numbers, e.g. "1020220114820". Tracks individual filings directly rather than an applicant\'s whole portfolio.'] = [],
    includePatents: Annotated[Optional[bool], 'When true (default), patent (특허) filings are included in the watchlist walk.'] = true,
    includeUtilityModels: Annotated[Optional[bool], 'When true (default), utility model (실용신안) filings are included in the watchlist walk, alongside patents.'] = true,
    onlyNew: Annotated[Optional[bool], 'When enabled, persists seen records between runs and only emits NEW_APPLICATION/STATUS_CHANGE/UPDATED events for what actually changed. When disabled, every matched record is delivered every run as BASELINE_SNAPSHOT/SNAPSHOT_NO_DIFF (always free) - the recommended way to validate this Actor\'s output against your real watchlist before committing to paid events.'] = false,
    maxItemsPerWatchlistEntry: Annotated[Optional[int], 'Hard cap on how many records KIPRIS Plus may return for a single watchlist entry in one run, applied independently per entry.'] = 100,
    deltaStateName: Annotated[Optional[str], 'Names the Key-Value Store this watchlist\'s seen-record state is kept in. Run multiple independent watchlists without them sharing or overwriting each other\'s baseline by giving each a distinct name here.'] = "default",
    resetState: Annotated[Optional[bool], 'When true, clears this watchlist\'s stored seen-record state before running, so the next run re-baselines from scratch (every matched record becomes a fresh, uncharged BASELINE_SNAPSHOT again, subject to onlyNew). Use for testing or recovering a corrupted state store, not routine operation.'] = false,
    requestDelayMs: Annotated[Optional[int], 'KIPRIS Plus\'s real per-key rate ceiling has not been independently confirmed - this default trades a slower walk for not trusting an unverified number, the same reasoning this operator\'s other actors use for an unconfirmed rate limit.'] = 500,
    maxRetries: Annotated[Optional[int], 'Retry attempts (exponential backoff with jitter) for a 429/5xx response or a network-level failure before a single KIPRIS Plus request is given up on as failed.'] = 4,
    requestTimeoutSecs: Annotated[Optional[int], 'Aborts a single KIPRIS Plus API request that takes longer than this, so one slow response never stalls the whole run.'] = 30,
) -> str:
    """Polls Korea's official KIPRIS Plus Open API for a watchlist of applicants/marks/applications and emits events on new filings and status changes. Extends this operator's USPTO/EPO patent-dispute monitor into a jurisdiction neither source touches. Pay-per-event: billed for what changed."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        **({"watchlistApplicants": watchlistApplicants} if watchlistApplicants is not None else {}),
        **({"watchlistApplicationNumbers": watchlistApplicationNumbers} if watchlistApplicationNumbers is not None else {}),
        **({"includePatents": includePatents} if includePatents is not None else {}),
        **({"includeUtilityModels": includeUtilityModels} if includeUtilityModels is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"maxItemsPerWatchlistEntry": maxItemsPerWatchlistEntry} if maxItemsPerWatchlistEntry is not None else {}),
        **({"deltaStateName": deltaStateName} if deltaStateName is not None else {}),
        **({"resetState": resetState} if resetState is not None else {}),
        "byoKiprisServiceKey": byoKiprisServiceKey,
        **({"requestDelayMs": requestDelayMs} if requestDelayMs is not None else {}),
        **({"maxRetries": maxRetries} if maxRetries is not None else {}),
        **({"requestTimeoutSecs": requestTimeoutSecs} if requestTimeoutSecs is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.text


# Wire into your own agents, e.g.:
#
# with LLMConfig(api_type="openai", model="gpt-4o-mini"):
#     compliance_agent = ConversableAgent(name="compliance_agent", system_message="...")
# executor_agent = ConversableAgent(name="executor_agent", human_input_mode="NEVER")
#
# register_function(
#     run_kipris_patent_trademark_status_monitor,
#     caller=compliance_agent,
#     executor=executor_agent,
#     description='Polls Korea\'s official KIPRIS Plus Open API for a watchlist of applicants/marks/applications and emits events on new filings and status changes. Extends this operator\'s USPTO/EPO patent-dispute monitor into a jurisdiction neither source touches. Pay-per-event: billed for what changed.',
# )
