// Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
// Source: Apify actor 'kipris-patent-trademark-status-monitor' (live Apify API), generated 2026-09-18.
// Regenerate with: node generate-all.js
import { tool } from "langchain";
import * as z from "zod";

const APIFY_ACTOR_ID = "9Wg73rplxFqgVq6fY"; // stefano_seggio/kipris-patent-trademark-status-monitor

export const kiprisPatentTrademarkStatusMonitorTool = tool(
  async (input) => {
    const token = process.env.APIFY_TOKEN;
    if (!token) throw new Error("APIFY_TOKEN is not set");
    const res = await fetch(
      `https://api.apify.com/v2/acts/${APIFY_ACTOR_ID}/run-sync-get-dataset-items?token=${token}`,
      { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) },
    );
    if (!res.ok) throw new Error(`Apify run failed: ${res.status} ${res.statusText}`);
    return res.json(); // dataset items array, returned directly
  },
  {
    name: "kipris-patent-trademark-status-monitor",
    description: "Polls Korea's official KIPRIS Plus Open API for a watchlist of applicants/marks/applications and emits events on new filings and status changes. Extends this operator's USPTO/EPO patent-dispute monitor into a jurisdiction neither source touches. Pay-per-event: billed for what changed.",
    schema: z.object({
    watchlistApplicants: z.array(z.string()).describe("Applicant (출원인) legal names, Korean or English, e.g. \"한빛전자 주식회사\" or \"Hanbit Electronics Co., Ltd.\". Matched against KIPRIS Plus's applicant-name search field. Known limitation: Korean legal-entity names have romanization/translation variants, so name matching can miss or double-count filings.").default([]),
    watchlistApplicationNumbers: z.array(z.string()).describe("Exact KIPO-format application numbers, e.g. \"1020220114820\". Tracks individual filings directly rather than an applicant's whole portfolio.").default([]),
    includePatents: z.boolean().describe("When true (default), patent (특허) filings are included in the watchlist walk.").default(true),
    includeUtilityModels: z.boolean().describe("When true (default), utility model (실용신안) filings are included in the watchlist walk, alongside patents.").default(true),
    onlyNew: z.boolean().describe("When enabled, persists seen records between runs and only emits NEW_APPLICATION/STATUS_CHANGE/UPDATED events for what actually changed. When disabled, every matched record is delivered every run as BASELINE_SNAPSHOT/SNAPSHOT_NO_DIFF (always free) - the recommended way to validate this Actor's output against your real watchlist before committing to paid events.").default(false),
    maxItemsPerWatchlistEntry: z.number().int().min(1).describe("Hard cap on how many records KIPRIS Plus may return for a single watchlist entry in one run, applied independently per entry.").default(100),
    deltaStateName: z.string().describe("Names the Key-Value Store this watchlist's seen-record state is kept in. Run multiple independent watchlists without them sharing or overwriting each other's baseline by giving each a distinct name here.").default("default"),
    resetState: z.boolean().describe("When true, clears this watchlist's stored seen-record state before running, so the next run re-baselines from scratch (every matched record becomes a fresh, uncharged BASELINE_SNAPSHOT again, subject to onlyNew). Use for testing or recovering a corrupted state store, not routine operation.").default(false),
    byoKiprisServiceKey: z.string().describe("KIPRIS Plus is a paid, registered product license (a flat annual fee, independently confirmed against the official KIPRIS Plus fee page - not free developer registration like USPTO/EPO). This Actor is deliberately bring-your-own-key: there is no operator-held shared key, by design, not as a stopgap - you hold your own KIPRIS Plus subscription and pay KIPRIS directly for API usage, which is what keeps this Actor's own per-event price low. Never logged or persisted beyond this run. Because this Actor's build could not obtain a paid key of its own, the exact field names in a successful KIPRIS Plus response were not independently verified against a real successful call - see README."),
    requestDelayMs: z.number().int().min(0).describe("KIPRIS Plus's real per-key rate ceiling has not been independently confirmed - this default trades a slower walk for not trusting an unverified number, the same reasoning this operator's other actors use for an unconfirmed rate limit.").default(500),
    maxRetries: z.number().int().min(0).describe("Retry attempts (exponential backoff with jitter) for a 429/5xx response or a network-level failure before a single KIPRIS Plus request is given up on as failed.").default(4),
    requestTimeoutSecs: z.number().int().min(5).describe("Aborts a single KIPRIS Plus API request that takes longer than this, so one slow response never stalls the whole run.").default(30),
    }),
  },
);
