"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'diario-oficial-cl-monitor' (local .actor/input_schema.json), generated 2026-09-18.
Regenerate with: node generate-all.js

NOTE: this targets AG2 Classic (import autogen), the AutoGen-lineage conversational-agent API.
"AutoGen" itself is in Microsoft-maintenance mode as of 2026; AG2 (ag2ai/ag2) is the actively
developed continuation. AG2 also has a newer, separate v1.0 protocol-driven surface (shipped
2026-09-11) not covered here because its docs could not be verified at generation time.
"""
import os
from typing import Annotated, Optional

import requests
from autogen import ConversableAgent, register_function, LLMConfig

APIFY_ACTOR_ID = 'qfBeEKuLfYUw9UOuW'  # stefano_seggio/diario-oficial-cl-monitor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


def run_diario_oficial_cl_monitor(
    sections: Annotated[Optional[list[str]], 'Which sections of the edition to fetch. Not every section publishes content every day - a section with nothing that day returns 404 from the source and is skipped, not treated as an error.'] = ["normas_generales"],
    maxItems: Annotated[Optional[int], 'Hard cap on the number of publications returned this run, across all selected sections.'] = 300,
    onlyNew: Annotated[Optional[bool], 'Return only publications that are new or amended (a correction re-published under the same CVE) since a prior run today, tracked in a named key-value store scoped to this actor. Most useful re-running the same day\'s edition on a schedule to catch late additions/corrections. There is no CLOSED or status-change event in this domain - a published legal notice is never withdrawn or \'closed\', it is a permanent public record.'] = false,
    eventTypes: Annotated[Optional[list[str]], 'Which kinds of change to deliver when \'Only new records\' is on (ignored, everything delivered, when it is off). NEW_LISTING = never seen before. UPDATED = same CVE (or identity), the content changed - a correction.'] = ["NEW_LISTING","UPDATED"],
) -> str:
    """Extracts today's edition of Chile's Diario Oficial (official gazette): laws, decrees and resolutions with branch, ministry and agency hierarchy, plus a direct PDF link per entry. Delta mode reports only new listings and corrections across recurring runs."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        **({"sections": sections} if sections is not None else {}),
        **({"maxItems": maxItems} if maxItems is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"eventTypes": eventTypes} if eventTypes is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.text


# Wire into your own agents, e.g.:
#
# with LLMConfig(api_type="openai", model="gpt-4o-mini"):
#     compliance_agent = ConversableAgent(name="compliance_agent", system_message="...")
# executor_agent = ConversableAgent(name="executor_agent", human_input_mode="NEVER")
#
# register_function(
#     run_diario_oficial_cl_monitor,
#     caller=compliance_agent,
#     executor=executor_agent,
#     description='Extracts today\'s edition of Chile\'s Diario Oficial (official gazette): laws, decrees and resolutions with branch, ministry and agency hierarchy, plus a direct PDF link per entry. Delta mode reports only new listings and corrections across recurring runs.',
# )
