"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'diario-oficial-cl-monitor' (local .actor/input_schema.json), generated 2026-09-18.
Regenerate with: node generate-all.js
"""
import os
from typing import Optional

import requests
from pydantic import BaseModel, Field
from llama_index.core.tools import FunctionTool

APIFY_ACTOR_ID = 'qfBeEKuLfYUw9UOuW'  # stefano_seggio/diario-oficial-cl-monitor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


class DiarioOficialClMonitorInput(BaseModel):
    """Mirrors diario-oficial-cl-monitor's real .actor/input_schema.json field-for-field."""

    sections: Optional[list[str]] = Field(default=["normas_generales"], min_length=1, description='Which sections of the edition to fetch. Not every section publishes content every day - a section with nothing that day returns 404 from the source and is skipped, not treated as an error.')
    maxItems: Optional[int] = Field(default=300, ge=1, description='Hard cap on the number of publications returned this run, across all selected sections.')
    onlyNew: Optional[bool] = Field(default=False, description='Return only publications that are new or amended (a correction re-published under the same CVE) since a prior run today, tracked in a named key-value store scoped to this actor. Most useful re-running the same day\'s edition on a schedule to catch late additions/corrections. There is no CLOSED or status-change event in this domain - a published legal notice is never withdrawn or \'closed\', it is a permanent public record.')
    eventTypes: Optional[list[str]] = Field(default=["NEW_LISTING","UPDATED"], description='Which kinds of change to deliver when \'Only new records\' is on (ignored, everything delivered, when it is off). NEW_LISTING = never seen before. UPDATED = same CVE (or identity), the content changed - a correction.')


def run_diario_oficial_cl_monitor(sections: Optional[list[str]] = None, maxItems: Optional[int] = None, onlyNew: Optional[bool] = None, eventTypes: Optional[list[str]] = None) -> list[dict]:
    """Extracts today's edition of Chile's Diario Oficial (official gazette): laws, decrees and resolutions with branch, ministry and agency hierarchy, plus a direct PDF link per entry. Delta mode reports only new listings and corrections across recurring runs."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        **({"sections": sections} if sections is not None else {}),
        **({"maxItems": maxItems} if maxItems is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"eventTypes": eventTypes} if eventTypes is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.json()


run_diario_oficial_cl_monitor_tool = FunctionTool.from_defaults(
    fn=run_diario_oficial_cl_monitor,
    name='diario-oficial-cl-monitor',
    description='Extracts today\'s edition of Chile\'s Diario Oficial (official gazette): laws, decrees and resolutions with branch, ministry and agency hierarchy, plus a direct PDF link per entry. Delta mode reports only new listings and corrections across recurring runs.',
    fn_schema=DiarioOficialClMonitorInput,
)
