"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'emerging-market-sovereign-debt-auction-monitor' (local .actor/input_schema.json), generated 2026-09-18.
Regenerate with: node generate-all.js

NOTE: this targets AG2 Classic (import autogen), the AutoGen-lineage conversational-agent API.
"AutoGen" itself is in Microsoft-maintenance mode as of 2026; AG2 (ag2ai/ag2) is the actively
developed continuation. AG2 also has a newer, separate v1.0 protocol-driven surface (shipped
2026-09-11) not covered here because its docs could not be verified at generation time.
"""
import os
from typing import Annotated, Optional

import requests
from autogen import ConversableAgent, register_function, LLMConfig

APIFY_ACTOR_ID = 'V3i5xKy1kf7vL0Rue'  # stefano_seggio/emerging-market-sovereign-debt-auction-monitor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


def run_emerging_market_sovereign_debt_auction_monitor(
    years: Annotated[Optional[list[str]], 'Which registry years of Brazil\'s National Treasury domestic auction results to check this run. The source publishes one full XLSX file per year (2000-2026 confirmed live at authoring time; 2027 is listed for when it becomes real). Each run fully downloads AND parses every selected year\'s file - this source has no HEAD/Range support and its ETag header was found to change on every request regardless of content (confirmed live), so there is no cheap way to skip an unchanged year at the file level; the per-record content fingerprint is what avoids re-billing unchanged auctions instead (see AGENTS.md section 1). Files are small (58-85 KB), so this is fast in practice. Defaults to the current year only to keep a first/default run fast.'] = ["2026"],
    bondTypeFilter: Annotated[Optional[list[str]], 'Deliver only auctions for these bond types - the real, currently-issued instrument types confirmed live: LTN (zero-coupon, fixed rate), LFT (floating rate, Selic-indexed), NTN-B (inflation-linked, IPCA-indexed), NTN-F (fixed rate, semi-annual coupon). Leave empty to deliver all types. This is a client-side filter applied after parsing (the source\'s bulk file has no server-side query mechanism), so it does not reduce download size, only which normalized auctions are delivered.'] = [],
    auctionTypeFilter: Annotated[Optional[list[str]], 'Deliver only these auction types - the real, documented values from the source\'s own legend: Venda (Sale), Troca (Exchange), Compra (Purchase), Extra Compra (Extraordinary Purchase), Extra Venda (Extraordinary Sale). Leave empty to deliver all types.'] = [],
    yieldChangeThresholdBps: Annotated[Optional[int], 'Fires a notification (webhook/Slack/Teams - does not affect what\'s pushed to the dataset, only what\'s flagged as a high-value alert) when a bond type + benchmark\'s accepted (marginal/cutoff) rate moves by at least this many basis points versus its own last observed value. A real NEW_AUCTION always alerts regardless of this threshold, since there is no \'previous value\' to compare against. Set to 0 to alert on any nonzero rate change for an AUCTION_RESULT_REVISED event.'] = 10,
    coverageRatioFloor: Annotated[Optional[float], 'Fires a notification when an auction\'s coverage ratio (Quantity Accepted / Quantity Tendered - NOT a true bid-to-cover ratio, since this source does not publish total market demand; see AGENTS.md section 3) falls at or below this fraction, signalling weak demand relative to the offered supply. Set to 0 to disable this specific alert.'] = 0.5,
    maxItems: Annotated[Optional[int], 'Stops the run once this many changed/new auction records have been pushed (and charged, where applicable) across all selected years - this actor\'s own safety valve. Records not yet reached when the limit is hit are simply re-evaluated fresh next run. Defaults to 50 so a default/test run completes in well under Apify\'s automated-test window.'] = 50,
    deltaStateName: Annotated[Optional[str], 'Names the persistent Key-Value Store this run\'s delta memory (per-auction fingerprints, per-year baseline-completion flags, and per-instrument last-observed rate for threshold comparisons, tracked by bond type + auction type + maturity date) lives in. Use a distinct name per independent schedule/filter configuration. Leave as \'default\' for a single schedule.'] = "default",
    resetState: Annotated[Optional[bool], 'When true, ignores all previously-remembered auctions, per-year baseline-completion flags, and per-instrument rate history for this deltaStateName and re-baselines from scratch. Use only to deliberately restart monitoring.'] = false,
    onlyNew: Annotated[Optional[bool], 'When true (recommended, and the only free-of-charge default), only NEW_AUCTION and AUCTION_RESULT_REVISED events are delivered - never a snapshot of an unchanged auction or a first-run baseline. When false, every matched auction is delivered every run its year is processed, including BASELINE_SNAPSHOT (first run) and AUCTION_UNCHANGED rows.'] = true,
    webhookUrl: Annotated[Optional[str], 'Any HTTPS endpoint that accepts a JSON POST - receives the full raw event payload with no channel-specific formatting. Independent of Apify\'s own platform-level webhook system.'] = None,
    slackWebhookUrl: Annotated[Optional[str], 'A Slack Incoming Webhook URL created via a Slack App (Slack\'s current, supported method - not the older \'legacy custom integrations\' path). Receives a formatted Slack Block Kit message highlighting the marginal-rate change and coverage ratio on a threshold breach.'] = None,
    teamsWebhookUrl: Annotated[Optional[str], 'A Microsoft Teams \'Workflows\' webhook URL (the current mechanism as of 2026 - NOT the retired classic Incoming Webhook connector; see README). Receives a formatted Adaptive Card highlighting the same yield/coverage signal as the Slack alert.'] = None,
) -> str:
    """Delta-tracks Brazil's National Treasury domestic bond auction results (LTN, LFT, NTN-B, NTN-F) for new auctions, marginal-rate threshold breaches, and coverage-ratio anomalies. Sourced from the official Tesouro Transparente open-data portal. Financial-grade basis-point precision. Pay-per-event."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        **({"years": years} if years is not None else {}),
        **({"bondTypeFilter": bondTypeFilter} if bondTypeFilter is not None else {}),
        **({"auctionTypeFilter": auctionTypeFilter} if auctionTypeFilter is not None else {}),
        **({"yieldChangeThresholdBps": yieldChangeThresholdBps} if yieldChangeThresholdBps is not None else {}),
        **({"coverageRatioFloor": coverageRatioFloor} if coverageRatioFloor is not None else {}),
        **({"maxItems": maxItems} if maxItems is not None else {}),
        **({"deltaStateName": deltaStateName} if deltaStateName is not None else {}),
        **({"resetState": resetState} if resetState is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"webhookUrl": webhookUrl} if webhookUrl is not None else {}),
        **({"slackWebhookUrl": slackWebhookUrl} if slackWebhookUrl is not None else {}),
        **({"teamsWebhookUrl": teamsWebhookUrl} if teamsWebhookUrl is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.text


# Wire into your own agents, e.g.:
#
# with LLMConfig(api_type="openai", model="gpt-4o-mini"):
#     compliance_agent = ConversableAgent(name="compliance_agent", system_message="...")
# executor_agent = ConversableAgent(name="executor_agent", human_input_mode="NEVER")
#
# register_function(
#     run_emerging_market_sovereign_debt_auction_monitor,
#     caller=compliance_agent,
#     executor=executor_agent,
#     description='Delta-tracks Brazil\'s National Treasury domestic bond auction results (LTN, LFT, NTN-B, NTN-F) for new auctions, marginal-rate threshold breaches, and coverage-ratio anomalies. Sourced from the official Tesouro Transparente open-data portal. Financial-grade basis-point precision. Pay-per-event.',
# )
