"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'actor-24-clinical-trials-delta-engine' (live Apify API), generated 2026-09-18.
Regenerate with: node generate-all.js

NOTE: this targets AG2 Classic (import autogen), the AutoGen-lineage conversational-agent API.
"AutoGen" itself is in Microsoft-maintenance mode as of 2026; AG2 (ag2ai/ag2) is the actively
developed continuation. AG2 also has a newer, separate v1.0 protocol-driven surface (shipped
2026-09-11) not covered here because its docs could not be verified at generation time.
"""
import os
from typing import Annotated, Optional

import requests
from autogen import ConversableAgent, register_function, LLMConfig

APIFY_ACTOR_ID = 'PkYgfW33Sh6teGXUX'  # stefano_seggio/actor-24-clinical-trials-delta-engine
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


def run_actor_24_clinical_trials_delta_engine(
    sources: Annotated[list[str], 'clinicaltrials = ClinicalTrials.gov API v2 trial-status delta tracking. orangebook = FDA Orange Book patent/exclusivity delta tracking.'],
    condition: Annotated[Optional[str], 'Passed to ClinicalTrials.gov\'s query.cond parameter, e.g. \'diabetes\'. Leave empty to walk all trials matching other filters (not recommended without a narrow maxPages).'] = None,
    orangeBookQuery: Annotated[Optional[str], 'Filter applied to the Orange Book query - an ingredient name or application number.'] = None,
    maxPages: Annotated[Optional[int], 'Hard cap on the number of 100-record ClinicalTrials.gov API pages walked per run.'] = 20,
    onlyChanged: Annotated[Optional[bool], 'Returns only trials/products that are new or whose tracked fields (overall_status, patent/exclusivity data) changed since a previous run. State persists in a named key-value store unique to this actor across scheduled runs.'] = false,
    maxRetries: Annotated[Optional[int], 'Maximum retry attempts (full-jitter exponential backoff) for a single page/extract fetch before it is dead-lettered.'] = 5,
    fdaApiKey: Annotated[Optional[str], 'Optional. openFDA allows 1,000 requests/day without a key (240/min) or 120,000/day with a free key (still 240/min). Only matters for high-volume Orange Book runs - the ClinicalTrials.gov source does not use this key.'] = None,
) -> str:
    """Delta-tracks ClinicalTrials.gov trial status changes (RECRUITING, COMPLETED, TERMINATED) and FDA Orange Book patent/exclusivity data against verified live public APIs. Fingerprint-based diffing delivers only new or changed records per run, with full-jitter retry and strict ISO 8601 timestamps."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        "sources": sources,
        **({"condition": condition} if condition is not None else {}),
        **({"orangeBookQuery": orangeBookQuery} if orangeBookQuery is not None else {}),
        **({"maxPages": maxPages} if maxPages is not None else {}),
        **({"onlyChanged": onlyChanged} if onlyChanged is not None else {}),
        **({"maxRetries": maxRetries} if maxRetries is not None else {}),
        **({"fdaApiKey": fdaApiKey} if fdaApiKey is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.text


# Wire into your own agents, e.g.:
#
# with LLMConfig(api_type="openai", model="gpt-4o-mini"):
#     compliance_agent = ConversableAgent(name="compliance_agent", system_message="...")
# executor_agent = ConversableAgent(name="executor_agent", human_input_mode="NEVER")
#
# register_function(
#     run_actor_24_clinical_trials_delta_engine,
#     caller=compliance_agent,
#     executor=executor_agent,
#     description='Delta-tracks ClinicalTrials.gov trial status changes (RECRUITING, COMPLETED, TERMINATED) and FDA Orange Book patent/exclusivity data against verified live public APIs. Fingerprint-based diffing delivers only new or changed records per run, with full-jitter retry and strict ISO 8601 timestamps.',
# )
