// Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
// Source: Apify actor 'actor-24-clinical-trials-delta-engine' (live Apify API), generated 2026-09-18.
// Regenerate with: node generate-all.js
import { tool } from "langchain";
import * as z from "zod";

const APIFY_ACTOR_ID = "PkYgfW33Sh6teGXUX"; // stefano_seggio/actor-24-clinical-trials-delta-engine

export const actor24ClinicalTrialsDeltaEngineTool = tool(
  async (input) => {
    const token = process.env.APIFY_TOKEN;
    if (!token) throw new Error("APIFY_TOKEN is not set");
    const res = await fetch(
      `https://api.apify.com/v2/acts/${APIFY_ACTOR_ID}/run-sync-get-dataset-items?token=${token}`,
      { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) },
    );
    if (!res.ok) throw new Error(`Apify run failed: ${res.status} ${res.statusText}`);
    return res.json(); // dataset items array, returned directly
  },
  {
    name: "actor-24-clinical-trials-delta-engine",
    description: "Delta-tracks ClinicalTrials.gov trial status changes (RECRUITING, COMPLETED, TERMINATED) and FDA Orange Book patent/exclusivity data against verified live public APIs. Fingerprint-based diffing delivers only new or changed records per run, with full-jitter retry and strict ISO 8601 timestamps.",
    schema: z.object({
    sources: z.array(z.string()).describe("clinicaltrials = ClinicalTrials.gov API v2 trial-status delta tracking. orangebook = FDA Orange Book patent/exclusivity delta tracking."),
    condition: z.string().describe("Passed to ClinicalTrials.gov's query.cond parameter, e.g. 'diabetes'. Leave empty to walk all trials matching other filters (not recommended without a narrow maxPages).").optional(),
    orangeBookQuery: z.string().describe("Filter applied to the Orange Book query - an ingredient name or application number.").optional(),
    maxPages: z.number().int().min(1).describe("Hard cap on the number of 100-record ClinicalTrials.gov API pages walked per run.").default(20),
    onlyChanged: z.boolean().describe("Returns only trials/products that are new or whose tracked fields (overall_status, patent/exclusivity data) changed since a previous run. State persists in a named key-value store unique to this actor across scheduled runs.").default(false),
    maxRetries: z.number().int().min(0).describe("Maximum retry attempts (full-jitter exponential backoff) for a single page/extract fetch before it is dead-lettered.").default(5),
    fdaApiKey: z.string().describe("Optional. openFDA allows 1,000 requests/day without a key (240/min) or 120,000/day with a free key (still 240/min). Only matters for high-volume Orange Book runs - the ClinicalTrials.gov source does not use this key.").optional(),
    }),
  },
);
