"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'actor-24-clinical-trials-delta-engine' (live Apify API), generated 2026-09-18.
Regenerate with: node generate-all.js
"""
import os
from typing import Optional

import requests
from pydantic import BaseModel, Field
from llama_index.core.tools import FunctionTool

APIFY_ACTOR_ID = 'PkYgfW33Sh6teGXUX'  # stefano_seggio/actor-24-clinical-trials-delta-engine
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


class Actor24ClinicalTrialsDeltaEngineInput(BaseModel):
    """Mirrors actor-24-clinical-trials-delta-engine's real .actor/input_schema.json field-for-field."""

    sources: list[str] = Field(..., description='clinicaltrials = ClinicalTrials.gov API v2 trial-status delta tracking. orangebook = FDA Orange Book patent/exclusivity delta tracking.')
    condition: Optional[str] = Field(default=None, description='Passed to ClinicalTrials.gov\'s query.cond parameter, e.g. \'diabetes\'. Leave empty to walk all trials matching other filters (not recommended without a narrow maxPages).')
    orangeBookQuery: Optional[str] = Field(default=None, description='Filter applied to the Orange Book query - an ingredient name or application number.')
    maxPages: Optional[int] = Field(default=20, ge=1, description='Hard cap on the number of 100-record ClinicalTrials.gov API pages walked per run.')
    onlyChanged: Optional[bool] = Field(default=False, description='Returns only trials/products that are new or whose tracked fields (overall_status, patent/exclusivity data) changed since a previous run. State persists in a named key-value store unique to this actor across scheduled runs.')
    maxRetries: Optional[int] = Field(default=5, ge=0, description='Maximum retry attempts (full-jitter exponential backoff) for a single page/extract fetch before it is dead-lettered.')
    fdaApiKey: Optional[str] = Field(default=None, description='Optional. openFDA allows 1,000 requests/day without a key (240/min) or 120,000/day with a free key (still 240/min). Only matters for high-volume Orange Book runs - the ClinicalTrials.gov source does not use this key.')


def run_actor_24_clinical_trials_delta_engine(sources: list[str], condition: Optional[str] = None, orangeBookQuery: Optional[str] = None, maxPages: Optional[int] = None, onlyChanged: Optional[bool] = None, maxRetries: Optional[int] = None, fdaApiKey: Optional[str] = None) -> list[dict]:
    """Delta-tracks ClinicalTrials.gov trial status changes (RECRUITING, COMPLETED, TERMINATED) and FDA Orange Book patent/exclusivity data against verified live public APIs. Fingerprint-based diffing delivers only new or changed records per run, with full-jitter retry and strict ISO 8601 timestamps."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        "sources": sources,
        **({"condition": condition} if condition is not None else {}),
        **({"orangeBookQuery": orangeBookQuery} if orangeBookQuery is not None else {}),
        **({"maxPages": maxPages} if maxPages is not None else {}),
        **({"onlyChanged": onlyChanged} if onlyChanged is not None else {}),
        **({"maxRetries": maxRetries} if maxRetries is not None else {}),
        **({"fdaApiKey": fdaApiKey} if fdaApiKey is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.json()


run_actor_24_clinical_trials_delta_engine_tool = FunctionTool.from_defaults(
    fn=run_actor_24_clinical_trials_delta_engine,
    name='actor-24-clinical-trials-delta-engine',
    description='Delta-tracks ClinicalTrials.gov trial status changes (RECRUITING, COMPLETED, TERMINATED) and FDA Orange Book patent/exclusivity data against verified live public APIs. Fingerprint-based diffing delivers only new or changed records per run, with full-jitter retry and strict ISO 8601 timestamps.',
    fn_schema=Actor24ClinicalTrialsDeltaEngineInput,
)
