"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'cordoba-compras-monitor' (local .actor/input_schema.json), generated 2026-09-18.
Regenerate with: node generate-all.js

NOTE: this targets AG2 Classic (import autogen), the AutoGen-lineage conversational-agent API.
"AutoGen" itself is in Microsoft-maintenance mode as of 2026; AG2 (ag2ai/ag2) is the actively
developed continuation. AG2 also has a newer, separate v1.0 protocol-driven surface (shipped
2026-09-11) not covered here because its docs could not be verified at generation time.
"""
import os
from typing import Annotated, Optional

import requests
from autogen import ConversableAgent, register_function, LLMConfig

APIFY_ACTOR_ID = 'q9jhMgJRSGjyNbXKA'  # stefano_seggio/cordoba-compras-monitor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


def run_cordoba_compras_monitor(
    maxItems: Annotated[Optional[int], 'Hard cap on the number of active tenders (licitaciones) returned this run. The source only covers active/open tenders (Licitaciones) - awarded or historical tenders are out of scope for this actor.'] = 200,
    onlyNew: Annotated[Optional[bool], 'When enabled, persists which tender ids (nroCotizacion) this actor has already returned - and their last-known estado + content fingerprint - in its own named key-value store that survives between scheduled runs, and returns only tenders that are new, changed estado, amended, or closed since a prior run. IMPORTANT: this source\'s listing is NOT reliably sorted newest-first end to end (verified live - a real tender can appear out of order relative to both its own Fecha Inicio and its own nroCotizacion, within the very first page), so onlyNew filters AFTER a full fetch (up to maxItems) rather than stopping pagination early like this fleet\'s other delta-enabled actors. It is correct, just not a pagination-cost optimization. Independent of dateRange. Recommended for recurring monitoring; leave off for a full one-off extraction.'] = false,
    eventTypes: Annotated[Optional[list[str]], 'Which kinds of change to deliver when \'Delta mode\' is on (ignored, everything delivered, when it is off). NEW_LISTING = never seen before. STATUS_CHANGE = seen before, estado changed - free to detect. UPDATED = seen before, same estado, a field changed (a prorroga granted, an amended item/budget). CLOSED = a previously-active tender is absent from this run\'s fetch - only computed when maxItems does not truncate the walk (a partial walk cannot prove absence).'] = ["NEW_LISTING","STATUS_CHANGE","UPDATED","CLOSED"],
    dateRange: Annotated[Optional[str], 'Optionally restrict results to tenders whose Fecha Inicio (publication date) falls within this window. Independent of onlyNew - this is the source\'s own declared publication timestamp, not independently cross-verified against when a tender actually first appeared on the portal.'] = None,
) -> str:
    """Monitors active public tenders (licitaciones) on the Province of Cordoba, Argentina official procurement portal. Returns organism, dates, status, per-item reference budget, and contact phone, with a delta mode that flags new, status-changed, amended, or closed tenders on recurring runs."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        **({"maxItems": maxItems} if maxItems is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"eventTypes": eventTypes} if eventTypes is not None else {}),
        **({"dateRange": dateRange} if dateRange is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.text


# Wire into your own agents, e.g.:
#
# with LLMConfig(api_type="openai", model="gpt-4o-mini"):
#     compliance_agent = ConversableAgent(name="compliance_agent", system_message="...")
# executor_agent = ConversableAgent(name="executor_agent", human_input_mode="NEVER")
#
# register_function(
#     run_cordoba_compras_monitor,
#     caller=compliance_agent,
#     executor=executor_agent,
#     description='Monitors active public tenders (licitaciones) on the Province of Cordoba, Argentina official procurement portal. Returns organism, dates, status, per-item reference budget, and contact phone, with a delta mode that flags new, status-changed, amended, or closed tenders on recurring runs.',
# )
