"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'cordoba-compras-monitor' (local .actor/input_schema.json), generated 2026-09-18.
Regenerate with: node generate-all.js
"""
import os
from typing import Optional, Type

import requests
from crewai.tools import BaseTool
from pydantic import BaseModel, Field

APIFY_ACTOR_ID = 'q9jhMgJRSGjyNbXKA'  # stefano_seggio/cordoba-compras-monitor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


class CordobaComprasMonitorInput(BaseModel):
    """Mirrors cordoba-compras-monitor's real .actor/input_schema.json field-for-field."""

    maxItems: Optional[int] = Field(default=200, ge=1, description='Hard cap on the number of active tenders (licitaciones) returned this run. The source only covers active/open tenders (Licitaciones) - awarded or historical tenders are out of scope for this actor.')
    onlyNew: Optional[bool] = Field(default=False, description='When enabled, persists which tender ids (nroCotizacion) this actor has already returned - and their last-known estado + content fingerprint - in its own named key-value store that survives between scheduled runs, and returns only tenders that are new, changed estado, amended, or closed since a prior run. IMPORTANT: this source\'s listing is NOT reliably sorted newest-first end to end (verified live - a real tender can appear out of order relative to both its own Fecha Inicio and its own nroCotizacion, within the very first page), so onlyNew filters AFTER a full fetch (up to maxItems) rather than stopping pagination early like this fleet\'s other delta-enabled actors. It is correct, just not a pagination-cost optimization. Independent of dateRange. Recommended for recurring monitoring; leave off for a full one-off extraction.')
    eventTypes: Optional[list[str]] = Field(default=["NEW_LISTING","STATUS_CHANGE","UPDATED","CLOSED"], description='Which kinds of change to deliver when \'Delta mode\' is on (ignored, everything delivered, when it is off). NEW_LISTING = never seen before. STATUS_CHANGE = seen before, estado changed - free to detect. UPDATED = seen before, same estado, a field changed (a prorroga granted, an amended item/budget). CLOSED = a previously-active tender is absent from this run\'s fetch - only computed when maxItems does not truncate the walk (a partial walk cannot prove absence).')
    dateRange: Optional[str] = Field(default=None, description='Optionally restrict results to tenders whose Fecha Inicio (publication date) falls within this window. Independent of onlyNew - this is the source\'s own declared publication timestamp, not independently cross-verified against when a tender actually first appeared on the portal.')


class CordobaComprasMonitorTool(BaseTool):
    name: str = 'cordoba-compras-monitor'
    description: str = 'Monitors active public tenders (licitaciones) on the Province of Cordoba, Argentina official procurement portal. Returns organism, dates, status, per-item reference budget, and contact phone, with a delta mode that flags new, status-changed, amended, or closed tenders on recurring runs.'
    args_schema: Type[BaseModel] = CordobaComprasMonitorInput

    def _run(self, maxItems: Optional[int] = None, onlyNew: Optional[bool] = None, eventTypes: Optional[list[str]] = None, dateRange: Optional[str] = None) -> str:
        token = os.environ["APIFY_TOKEN"]
        payload = {
            **({"maxItems": maxItems} if maxItems is not None else {}),
            **({"onlyNew": onlyNew} if onlyNew is not None else {}),
            **({"eventTypes": eventTypes} if eventTypes is not None else {}),
            **({"dateRange": dateRange} if dateRange is not None else {}),
        }
        resp = requests.post(
            APIFY_RUN_SYNC_URL,
            params={"token": token},
            json=payload,
            timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
        )
        resp.raise_for_status()
        return resp.text  # dataset items as a JSON array string
