"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'tucuman-compras-monitor' (local .actor/input_schema.json), generated 2026-09-18.
Regenerate with: node generate-all.js
"""
import os
from typing import Optional

import requests
from pydantic import BaseModel, Field
from llama_index.core.tools import FunctionTool

APIFY_ACTOR_ID = 'TdJtze8dfyykMj2qA'  # stefano_seggio/tucuman-compras-monitor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


class TucumanComprasMonitorInput(BaseModel):
    """Mirrors tucuman-compras-monitor's real .actor/input_schema.json field-for-field."""

    estados: Optional[list[str]] = Field(default=["1"], min_length=1, description='Which procurement states to fetch (estado_compra on the portal). 1 = upcoming opening, 2 = in adjudication, 3 = already awarded.')
    maxItems: Optional[int] = Field(default=100, ge=1, description='Hard cap on the number of tenders returned this run, across all selected states. The portal lists only 5 tenders per page, so a high value across multiple states means many sequential requests - estado 2 alone has 3700+ historical records. Start small.')
    onlyNew: Optional[bool] = Field(default=False, description='Delta mode for recurring/scheduled monitoring: returns only tenders that are new, changed to a different estado_compra (a real lifecycle transition, e.g. upcoming -> awarded) or amended (a changed monto, renglon or date) since a previous run. Tracked cross-estado, per idCompra, in this actor\'s own named key-value store (tucuman-compras-monitor-delta-state), so it survives between scheduled runs - unlike the run\'s default key-value store, which is created fresh per run. Implemented as a POST-FILTER: this actor still fetches up to maxItems as usual and only then drops unchanged already-seen ids, rather than stopping pagination early once N pages come back with nothing new. Early-stop is NOT used here because this portal\'s own listing order was verified live (2026-09-06) to be sorted by each tender\'s own opening-date field - ascending for estado 1, descending for estado 3 - not by when the tender was added to the site, so a later page can hold a genuinely new tender while an earlier page is full of ones already seen. See AGENTS.md for the page-by-page evidence.')
    eventTypes: Optional[list[str]] = Field(default=["NEW_LISTING","STATUS_CHANGE","UPDATED"], description='Which kinds of change to deliver when \'Only new\' is on (ignored, everything delivered, when it is off). NEW_LISTING = never seen before. STATUS_CHANGE = seen before under a different estado_compra (a real lifecycle transition). UPDATED = seen before, same estado, but a monto, renglon, date or other field changed.')
    dateRange: Optional[str] = Field(default=None, description='Filters results to tenders whose fechaAperturaSobres (bid-opening date - the only per-tender date this source publishes) falls within the last 24 hours / 7 days / 30 days. Independent of onlyNew - combine both for \'new to me AND recently opened\'. Gotcha: for estado 1 (apertura proxima) this date is always in the FUTURE, since the opening has not happened yet, so it can never fall inside this backward-looking window - dateRange only has a real effect on estado 2/3 tenders, whose opening has already occurred. See README.md \'Delta mode\'.')


def run_tucuman_compras_monitor(estados: Optional[list[str]] = None, maxItems: Optional[int] = None, onlyNew: Optional[bool] = None, eventTypes: Optional[list[str]] = None, dateRange: Optional[str] = None) -> list[dict]:
    """Monitors the Province of Tucuman, Argentina's official procurement portal for public tenders - licitaciones publicas, privadas, concursos de precios and contrataciones directas - across upcoming, in-adjudication and awarded stages, with full renglon detail, montos and direct pliego PDF links."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        **({"estados": estados} if estados is not None else {}),
        **({"maxItems": maxItems} if maxItems is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"eventTypes": eventTypes} if eventTypes is not None else {}),
        **({"dateRange": dateRange} if dateRange is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.json()


run_tucuman_compras_monitor_tool = FunctionTool.from_defaults(
    fn=run_tucuman_compras_monitor,
    name='tucuman-compras-monitor',
    description='Monitors the Province of Tucuman, Argentina\'s official procurement portal for public tenders - licitaciones publicas, privadas, concursos de precios and contrataciones directas - across upcoming, in-adjudication and awarded stages, with full renglon detail, montos and direct pliego PDF links.',
    fn_schema=TucumanComprasMonitorInput,
)
