"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor 'australia-grantconnect-monitor' (local .actor/input_schema.json), generated 2026-09-18.
Regenerate with: node generate-all.js

NOTE: this targets AG2 Classic (import autogen), the AutoGen-lineage conversational-agent API.
"AutoGen" itself is in Microsoft-maintenance mode as of 2026; AG2 (ag2ai/ag2) is the actively
developed continuation. AG2 also has a newer, separate v1.0 protocol-driven surface (shipped
2026-09-11) not covered here because its docs could not be verified at generation time.
"""
import os
from typing import Annotated, Optional

import requests
from autogen import ConversableAgent, register_function, LLMConfig

APIFY_ACTOR_ID = 'gt7wS4T0uFRXDz49n'  # stefano_seggio/australia-grantconnect-monitor
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


def run_australia_grantconnect_monitor(
    keyword: Annotated[Optional[str], 'Full-text search over grant title, purpose and activity (also accepts a GA ID such as GA578886). Matching mode below.'] = None,
    keywordMatch: Annotated[Optional[str], 'How the keyword(s) must match.'] = "AllWord",
    categories: Annotated[Optional[list[str]], 'GrantConnect\'s 29 top-level categories. Select several to get their union. The record\'s own \'category\' field shows the finer sub-category label (e.g. \'Medical Research\').'] = [],
    agencyNameContains: Annotated[Optional[str], 'Case-insensitive substring match on the awarding agency, e.g. \'Health\' or \'Infrastructure\'. Applied client-side (GrantConnect\'s public form has no agency parameter), so combine it with a category, keyword or date window to keep the walk short.'] = None,
    recipientName: Annotated[Optional[str], 'Substring match on the recipient\'s legal name, e.g. \'Monash University\' or \'Regional Express\'.'] = None,
    recipientAbn: Annotated[Optional[str], 'Exact match on the recipient\'s 11-digit Australian Business Number (spaces optional). Returns every Commonwealth grant that entity has received.'] = None,
    minValueAud: Annotated[Optional[int], 'Only awards worth at least this amount. Tip: 1000000 narrows the 360,000-record register to roughly 28,000.'] = None,
    maxValueAud: Annotated[Optional[int], 'Only awards worth at most this amount.'] = None,
    goId: Annotated[Optional[str], 'All awards made under one Grant Opportunity (funding round), e.g. GO6105.'] = None,
    dateType: Annotated[Optional[str], 'Which date the \'from\'/\'to\' window applies to. \'Current\' = grants running today and \'Closed\' = grants whose term has ended (both ignore the window).'] = "Publish Date",
    dateFrom: Annotated[Optional[str], 'Absolute (2026-07-01) or relative (\'7 days\', \'3 months\', \'1 year\' back from today, Canberra time). Leave empty for the whole archive (December 2017 onwards).'] = None,
    dateTo: Annotated[Optional[str], 'Absolute or relative upper bound of the window. Leave empty for \'today\'.'] = None,
    oneOffAdHoc: Annotated[Optional[str], 'Ad hoc grants (no competitive round) are the ones probity and integrity teams watch most closely.'] = "any",
    aggregateGrantAward: Annotated[Optional[str], 'Aggregate awards bundle several recipients into one record (\'Multiple\').'] = "any",
    eventTypes: Annotated[Optional[list[str]], 'NEW_LISTING = a brand-new award; AWARD_VARIATION = a variation/amendment record (value or term changed, e.g. GA270901-V1); UPDATED = an award you already received whose \'Last Updated\' stamp moved (delta mode only).'] = ["NEW_LISTING","AWARD_VARIATION","UPDATED"],
    onlyNew: Annotated[Optional[bool], 'Remembers every award it has delivered (per filter set, in a named key-value store) and returns only awards that are new, varied or updated since. The walk stops as soon as it reaches already-known records, so a scheduled run costs a few pages instead of the whole register.'] = false,
    sortBy: Annotated[Optional[str], '\'Last updated\' (recommended, and required for reliable monitoring): variations and corrections of old awards keep their original publish date, so only this order surfaces them. \'Relevance\' needs a keyword.'] = "Last Updated",
    deltaStateName: Annotated[Optional[str], 'Optional label for the memory of a monitoring task. Defaults to a fingerprint of your filters, so different schedules never interfere. Set the same name on two tasks to make them share one memory.'] = None,
    resetState: Annotated[Optional[bool], 'Forget every previously delivered award for this delta state and re-baseline (the run then returns up to \'Max records\' most recently updated awards).'] = false,
    maxItems: Annotated[Optional[int], 'Hard cap on delivered records (and therefore on cost: you pay per record). In delta mode anything beyond the cap is simply delivered by the next run.'] = 100,
    fetchDetail: Annotated[Optional[bool], 'Opens each award\'s page (one extra request) for recipient ABN and location, delivery location, purpose, program, Grant Opportunity link, selection process, confidentiality flags and the agency contact. Off = listing-only summary records (cheaper \'result-summary\' price).'] = true,
    maxConcurrency: Annotated[Optional[int], 'How many award pages are fetched at once. GrantConnect tolerates 10 comfortably; 5 keeps a 500-record run under two minutes.'] = 5,
    dateRange: Annotated[Optional[str], 'Kept for tasks created with version 1: \'24h\', \'7d\' or \'30d\' are interpreted as \'Date from\'.'] = None,
) -> str:
    """Monitor every Australian Government grant award on GrantConnect (grants.gov.au): recipient, ABN, agency, value, purpose, program and location. Server-side filters (keyword, category, ABN, value, dates), delta mode flags new, varied and updated awards, ISO dates, numeric AUD. Pay per result."""
    token = os.environ["APIFY_TOKEN"]
    payload = {
        **({"keyword": keyword} if keyword is not None else {}),
        **({"keywordMatch": keywordMatch} if keywordMatch is not None else {}),
        **({"categories": categories} if categories is not None else {}),
        **({"agencyNameContains": agencyNameContains} if agencyNameContains is not None else {}),
        **({"recipientName": recipientName} if recipientName is not None else {}),
        **({"recipientAbn": recipientAbn} if recipientAbn is not None else {}),
        **({"minValueAud": minValueAud} if minValueAud is not None else {}),
        **({"maxValueAud": maxValueAud} if maxValueAud is not None else {}),
        **({"goId": goId} if goId is not None else {}),
        **({"dateType": dateType} if dateType is not None else {}),
        **({"dateFrom": dateFrom} if dateFrom is not None else {}),
        **({"dateTo": dateTo} if dateTo is not None else {}),
        **({"oneOffAdHoc": oneOffAdHoc} if oneOffAdHoc is not None else {}),
        **({"aggregateGrantAward": aggregateGrantAward} if aggregateGrantAward is not None else {}),
        **({"eventTypes": eventTypes} if eventTypes is not None else {}),
        **({"onlyNew": onlyNew} if onlyNew is not None else {}),
        **({"sortBy": sortBy} if sortBy is not None else {}),
        **({"deltaStateName": deltaStateName} if deltaStateName is not None else {}),
        **({"resetState": resetState} if resetState is not None else {}),
        **({"maxItems": maxItems} if maxItems is not None else {}),
        **({"fetchDetail": fetchDetail} if fetchDetail is not None else {}),
        **({"maxConcurrency": maxConcurrency} if maxConcurrency is not None else {}),
        **({"dateRange": dateRange} if dateRange is not None else {}),
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=320,  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.text


# Wire into your own agents, e.g.:
#
# with LLMConfig(api_type="openai", model="gpt-4o-mini"):
#     compliance_agent = ConversableAgent(name="compliance_agent", system_message="...")
# executor_agent = ConversableAgent(name="executor_agent", human_input_mode="NEVER")
#
# register_function(
#     run_australia_grantconnect_monitor,
#     caller=compliance_agent,
#     executor=executor_agent,
#     description='Monitor every Australian Government grant award on GrantConnect (grants.gov.au): recipient, ABN, agency, value, purpose, program and location. Server-side filters (keyword, category, ABN, value, dates), delta mode flags new, varied and updated awards, ISO dates, numeric AUD. Pay per result.',
# )
