// Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
// Source: Apify actor 'australia-grantconnect-monitor' (local .actor/input_schema.json), generated 2026-09-18.
// Regenerate with: node generate-all.js
import { tool } from "langchain";
import * as z from "zod";

const APIFY_ACTOR_ID = "gt7wS4T0uFRXDz49n"; // stefano_seggio/australia-grantconnect-monitor

export const australiaGrantconnectMonitorTool = tool(
  async (input) => {
    const token = process.env.APIFY_TOKEN;
    if (!token) throw new Error("APIFY_TOKEN is not set");
    const res = await fetch(
      `https://api.apify.com/v2/acts/${APIFY_ACTOR_ID}/run-sync-get-dataset-items?token=${token}`,
      { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) },
    );
    if (!res.ok) throw new Error(`Apify run failed: ${res.status} ${res.statusText}`);
    return res.json(); // dataset items array, returned directly
  },
  {
    name: "australia-grantconnect-monitor",
    description: "Monitor every Australian Government grant award on GrantConnect (grants.gov.au): recipient, ABN, agency, value, purpose, program and location. Server-side filters (keyword, category, ABN, value, dates), delta mode flags new, varied and updated awards, ISO dates, numeric AUD. Pay per result.",
    schema: z.object({
    keyword: z.string().describe("Full-text search over grant title, purpose and activity (also accepts a GA ID such as GA578886). Matching mode below.").optional(),
    keywordMatch: z.enum(["AllWord", "AnyWord", "ExactPhrase"]).describe("How the keyword(s) must match.").default("AllWord"),
    categories: z.array(z.string()).describe("GrantConnect's 29 top-level categories. Select several to get their union. The record's own 'category' field shows the finer sub-category label (e.g. 'Medical Research').").default([]),
    agencyNameContains: z.string().describe("Case-insensitive substring match on the awarding agency, e.g. 'Health' or 'Infrastructure'. Applied client-side (GrantConnect's public form has no agency parameter), so combine it with a category, keyword or date window to keep the walk short.").optional(),
    recipientName: z.string().describe("Substring match on the recipient's legal name, e.g. 'Monash University' or 'Regional Express'.").optional(),
    recipientAbn: z.string().regex(new RegExp("^\\s*\\d{2}\\s?\\d{3}\\s?\\d{3}\\s?\\d{3}\\s*$")).describe("Exact match on the recipient's 11-digit Australian Business Number (spaces optional). Returns every Commonwealth grant that entity has received.").optional(),
    minValueAud: z.number().int().min(0).describe("Only awards worth at least this amount. Tip: 1000000 narrows the 360,000-record register to roughly 28,000.").optional(),
    maxValueAud: z.number().int().min(0).describe("Only awards worth at most this amount.").optional(),
    goId: z.string().regex(new RegExp("^\\s*[Gg][Oo]\\d+\\s*$")).describe("All awards made under one Grant Opportunity (funding round), e.g. GO6105.").optional(),
    dateType: z.enum(["Publish Date", "Approval Date", "Start Date", "End Date", "Current", "Closed"]).describe("Which date the 'from'/'to' window applies to. 'Current' = grants running today and 'Closed' = grants whose term has ended (both ignore the window).").default("Publish Date"),
    dateFrom: z.string().describe("Absolute (2026-07-01) or relative ('7 days', '3 months', '1 year' back from today, Canberra time). Leave empty for the whole archive (December 2017 onwards).").optional(),
    dateTo: z.string().describe("Absolute or relative upper bound of the window. Leave empty for 'today'.").optional(),
    oneOffAdHoc: z.enum(["any", "yes", "no"]).describe("Ad hoc grants (no competitive round) are the ones probity and integrity teams watch most closely.").default("any"),
    aggregateGrantAward: z.enum(["any", "yes", "no"]).describe("Aggregate awards bundle several recipients into one record ('Multiple').").default("any"),
    eventTypes: z.array(z.string()).describe("NEW_LISTING = a brand-new award; AWARD_VARIATION = a variation/amendment record (value or term changed, e.g. GA270901-V1); UPDATED = an award you already received whose 'Last Updated' stamp moved (delta mode only).").default(["NEW_LISTING","AWARD_VARIATION","UPDATED"]),
    onlyNew: z.boolean().describe("Remembers every award it has delivered (per filter set, in a named key-value store) and returns only awards that are new, varied or updated since. The walk stops as soon as it reaches already-known records, so a scheduled run costs a few pages instead of the whole register.").default(false),
    sortBy: z.enum(["Last Updated", "Publish Date", "Relevance"]).describe("'Last updated' (recommended, and required for reliable monitoring): variations and corrections of old awards keep their original publish date, so only this order surfaces them. 'Relevance' needs a keyword.").default("Last Updated"),
    deltaStateName: z.string().regex(new RegExp("^[A-Za-z0-9-]{1,30}$")).describe("Optional label for the memory of a monitoring task. Defaults to a fingerprint of your filters, so different schedules never interfere. Set the same name on two tasks to make them share one memory.").optional(),
    resetState: z.boolean().describe("Forget every previously delivered award for this delta state and re-baseline (the run then returns up to 'Max records' most recently updated awards).").default(false),
    maxItems: z.number().int().min(1).describe("Hard cap on delivered records (and therefore on cost: you pay per record). In delta mode anything beyond the cap is simply delivered by the next run.").default(100),
    fetchDetail: z.boolean().describe("Opens each award's page (one extra request) for recipient ABN and location, delivery location, purpose, program, Grant Opportunity link, selection process, confidentiality flags and the agency contact. Off = listing-only summary records (cheaper 'result-summary' price).").default(true),
    maxConcurrency: z.number().int().min(1).describe("How many award pages are fetched at once. GrantConnect tolerates 10 comfortably; 5 keeps a 500-record run under two minutes.").default(5),
    dateRange: z.string().regex(new RegExp("^(24h|7d|30d)$")).describe("Kept for tasks created with version 1: '24h', '7d' or '30d' are interpreted as 'Date from'.").optional(),
    }),
  },
);
