import type { ResolvedActorSchema } from './types';
import { mappableFields, mappableFieldsForPythonSignature, toPythonIdentifier } from './field-mapper';
import { pyStr, pyFieldAnnotation, pyFieldExpr } from './codegen-helpers';

const APIFY_TIMEOUT_SECS = 320; // real Apify run-sync-get-dataset-items cap is 300s; 20s client-side margin

/**
 * CrewAI: `crewai.tools.BaseTool` subclass with a Pydantic `args_schema` — verified live against
 * docs.crewai.com/en/learn/create-custom-tools, 2026-09-18. Import path is `crewai.tools`, NOT
 * the older separate `crewai_tools` package some tutorials still show.
 */
export function toCrewAIPython(resolved: ResolvedActorSchema): string {
  const className = `${pascalCase(resolved.meta.slug)}Tool`;
  const modelName = `${pascalCase(resolved.meta.slug)}Input`;
  const fields = mappableFields(resolved.inputSchema);

  const modelFields = fields
    .map(({ name, field, required }) => `    ${name}: ${pyFieldAnnotation(field, required)} = ${pyFieldExpr(field, required)}`)
    .join('\n');

  // Required-first: Python function signatures reject a non-default param after a defaulted one.
  const runParamList = mappableFieldsForPythonSignature(resolved.inputSchema)
    .map(({ name, field, required }) => `${name}: ${pyFieldAnnotation(field, required)}${required ? '' : ' = None'}`)
    .join(', ');

  const payloadLines = fields.map(({ name, required }) => (required ? `            "${name}": ${name},` : `            **({"${name}": ${name}} if ${name} is not None else {}),`)).join('\n');

  return `"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor '${resolved.meta.slug}' (${resolved.inputSchemaSource === 'local-file' ? 'local .actor/input_schema.json' : 'live Apify API'}), generated ${new Date().toISOString().slice(0, 10)}.
Regenerate with: node generate-all.js
"""
import os
from typing import Optional, Type

import requests
from crewai.tools import BaseTool
from pydantic import BaseModel, Field

APIFY_ACTOR_ID = ${pyStr(resolved.meta.apifyActorId)}  # stefano_seggio/${resolved.meta.slug}
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


class ${modelName}(BaseModel):
    """Mirrors ${resolved.meta.slug}'s real .actor/input_schema.json field-for-field."""

${modelFields || '    pass'}


class ${className}(BaseTool):
    name: str = ${pyStr(resolved.meta.slug)}
    description: str = ${pyStr(resolved.description)}
    args_schema: Type[BaseModel] = ${modelName}

    def _run(self, ${runParamList}) -> str:
        token = os.environ["APIFY_TOKEN"]
        payload = {
${payloadLines}
        }
        resp = requests.post(
            APIFY_RUN_SYNC_URL,
            params={"token": token},
            json=payload,
            timeout=${APIFY_TIMEOUT_SECS},  # Apify's real run-sync-get-dataset-items cap is 300s
        )
        resp.raise_for_status()
        return resp.text  # dataset items as a JSON array string
`;
}

/**
 * AG2 Classic (`import autogen`, `pip install ag2`): `register_function` splitting caller/executor
 * agents — verified live against docs.ag2.ai/0.8.5, 2026-09-18. "AutoGen" itself is stale branding:
 * Microsoft's own AutoGen line is in maintenance mode; AG2 is the actively developed continuation,
 * and AG2 itself forked again into a new, unverified v1.0 protocol-driven architecture one week
 * before this was written (v1.0.5, 2026-09-11) — this generates the Classic API, the one surface
 * confirmed real and working, not the unverified v1.0 syntax.
 */
export function toAG2Python(resolved: ResolvedActorSchema): string {
  const fnName = `run_${toPythonIdentifier(resolved.meta.slug)}`;
  const fields = mappableFields(resolved.inputSchema);

  // Required-first: Python function signatures reject a non-default param after a defaulted one.
  const paramList = mappableFieldsForPythonSignature(resolved.inputSchema)
    .map(({ name, field, required }) => {
      const ann = pyFieldAnnotation(field, required);
      const desc = field.description ?? field.title ?? name;
      const defaultPart = required ? '' : field.default !== undefined ? ` = ${JSON.stringify(field.default)}` : ' = None';
      return `    ${name}: Annotated[${ann}, ${pyStr(desc)}]${defaultPart},`;
    })
    .join('\n');

  const payloadLines = fields.map(({ name, required }) => (required ? `        "${name}": ${name},` : `        **({"${name}": ${name}} if ${name} is not None else {}),`)).join('\n');

  return `"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor '${resolved.meta.slug}' (${resolved.inputSchemaSource === 'local-file' ? 'local .actor/input_schema.json' : 'live Apify API'}), generated ${new Date().toISOString().slice(0, 10)}.
Regenerate with: node generate-all.js

NOTE: this targets AG2 Classic (import autogen), the AutoGen-lineage conversational-agent API.
"AutoGen" itself is in Microsoft-maintenance mode as of 2026; AG2 (ag2ai/ag2) is the actively
developed continuation. AG2 also has a newer, separate v1.0 protocol-driven surface (shipped
2026-09-11) not covered here because its docs could not be verified at generation time.
"""
import os
from typing import Annotated, Optional

import requests
from autogen import ConversableAgent, register_function, LLMConfig

APIFY_ACTOR_ID = ${pyStr(resolved.meta.apifyActorId)}  # stefano_seggio/${resolved.meta.slug}
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


def ${fnName}(
${paramList || '    # no fields beyond Apify-infrastructure-only ones (e.g. proxyConfiguration), excluded above'}
) -> str:
    """${resolved.description}"""
    token = os.environ["APIFY_TOKEN"]
    payload = {
${payloadLines}
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=${APIFY_TIMEOUT_SECS},  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.text


# Wire into your own agents, e.g.:
#
# with LLMConfig(api_type="openai", model="gpt-4o-mini"):
#     compliance_agent = ConversableAgent(name="compliance_agent", system_message="...")
# executor_agent = ConversableAgent(name="executor_agent", human_input_mode="NEVER")
#
# register_function(
#     ${fnName},
#     caller=compliance_agent,
#     executor=executor_agent,
#     description=${pyStr(resolved.description)},
# )
`;
}

function pascalCase(slug: string): string {
  return slug.split('-').map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join('');
}
