import type { ResolvedActorSchema } from './types';
import { mappableFields, mappableFieldsForPythonSignature, toPythonIdentifier } from './field-mapper';
import { pyStr, tsStr, pyFieldAnnotation, pyFieldExpr, zodFieldExpr } from './codegen-helpers';

const APIFY_TIMEOUT_SECS = 320; // real Apify run-sync-get-dataset-items cap is 300s; 20s client-side margin

/**
 * Python: `langchain_core.tools.StructuredTool.from_function` with a Pydantic v2 `args_schema`
 * (verified live against `langchain_core/tools/structured.py` on langchain-ai/langchain `master`,
 * 2026-09-18 — `langchain-core >= 0.3`, NOT the deprecated `langchain_core.pydantic_v1` shim).
 */
export function toLangChainPython(resolved: ResolvedActorSchema): string {
  const fnName = `run_${toPythonIdentifier(resolved.meta.slug)}`;
  const modelName = `${pascalCase(resolved.meta.slug)}Input`;
  const fields = mappableFields(resolved.inputSchema);

  const modelFields = fields
    .map(({ name, field, required }) => `    ${name}: ${pyFieldAnnotation(field, required)} = ${pyFieldExpr(field, required)}`)
    .join('\n');

  const payloadLines = fields.map(({ name, required }) => (required ? `        "${name}": ${name},` : `        **({"${name}": ${name}} if ${name} is not None else {}),`)).join('\n');

  // Required-first: Python function signatures reject a non-default param after a defaulted one.
  const paramList = mappableFieldsForPythonSignature(resolved.inputSchema)
    .map(({ name, field, required }) => `${name}: ${pyFieldAnnotation(field, required)}${required ? '' : ' = None'}`)
    .join(', ');

  return `"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor '${resolved.meta.slug}' (${resolved.inputSchemaSource === 'local-file' ? 'local .actor/input_schema.json' : 'live Apify API'}), generated ${new Date().toISOString().slice(0, 10)}.
Regenerate with: node generate-all.js
"""
import os
from typing import Optional

import requests
from pydantic import BaseModel, Field
from langchain_core.tools import StructuredTool

APIFY_ACTOR_ID = ${pyStr(resolved.meta.apifyActorId)}  # stefano_seggio/${resolved.meta.slug}
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


class ${modelName}(BaseModel):
    """Mirrors ${resolved.meta.slug}'s real .actor/input_schema.json field-for-field."""

${modelFields || '    pass'}


def _${fnName}(${paramList}) -> list[dict]:
    token = os.environ["APIFY_TOKEN"]  # never hardcode the token
    payload = {
${payloadLines}
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=${APIFY_TIMEOUT_SECS},  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.json()  # dataset items array, returned directly


${fnName}_tool = StructuredTool.from_function(
    func=_${fnName},
    name=${pyStr(resolved.meta.slug)},
    description=${pyStr(resolved.description)},
    args_schema=${modelName},
)
`;
}

/**
 * TypeScript: `langchain`'s `tool()` function with a Zod schema (verified live against
 * docs.langchain.com/oss/javascript/langchain/overview and langchain-ts.dev, 2026-09-18 —
 * `import { tool } from "langchain"`, not the older `@langchain/core/tools` DynamicStructuredTool
 * pattern, which the current docs present as superseded).
 */
export function toLangChainTypeScript(resolved: ResolvedActorSchema): string {
  const fields = mappableFields(resolved.inputSchema);
  const zodShape = fields.map(({ name, field, required }) => `    ${name}: ${zodFieldExpr(field, required)},`).join('\n');
  const camelName = camelCase(resolved.meta.slug);

  return `// Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
// Source: Apify actor '${resolved.meta.slug}' (${resolved.inputSchemaSource === 'local-file' ? 'local .actor/input_schema.json' : 'live Apify API'}), generated ${new Date().toISOString().slice(0, 10)}.
// Regenerate with: node generate-all.js
import { tool } from "langchain";
import * as z from "zod";

const APIFY_ACTOR_ID = ${tsStr(resolved.meta.apifyActorId)}; // stefano_seggio/${resolved.meta.slug}

export const ${camelName}Tool = tool(
  async (input) => {
    const token = process.env.APIFY_TOKEN;
    if (!token) throw new Error("APIFY_TOKEN is not set");
    const res = await fetch(
      \`https://api.apify.com/v2/acts/\${APIFY_ACTOR_ID}/run-sync-get-dataset-items?token=\${token}\`,
      { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(input) },
    );
    if (!res.ok) throw new Error(\`Apify run failed: \${res.status} \${res.statusText}\`);
    return res.json(); // dataset items array, returned directly
  },
  {
    name: ${tsStr(resolved.meta.slug)},
    description: ${tsStr(resolved.description)},
    schema: z.object({
${zodShape || '      // no fields beyond Apify-infrastructure-only ones (e.g. proxyConfiguration), excluded above'}
    }),
  },
);
`;
}

function pascalCase(slug: string): string {
  return slug.split('-').map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join('');
}
function camelCase(slug: string): string {
  const p = pascalCase(slug);
  return p.charAt(0).toLowerCase() + p.slice(1);
}
