import type { ResolvedActorSchema } from './types';
import { mappableFields, mappableFieldsForPythonSignature, toPythonIdentifier } from './field-mapper';
import { pyStr, pyFieldAnnotation, pyFieldExpr } from './codegen-helpers';

const APIFY_TIMEOUT_SECS = 320; // real Apify run-sync-get-dataset-items cap is 300s; 20s client-side margin

/**
 * Python: `llama_index.core.tools.FunctionTool.from_defaults(fn=..., fn_schema=..., name=...,
 * description=...)` — verified live against `llama_index/core/tools/function_tool.py` on
 * run-llama/llama_index `main`, 2026-09-18. No verified LlamaIndex.TS equivalent exists in this
 * fleet's research pass, so only the Python surface is generated — not fabricated for TypeScript.
 */
export function toLlamaIndexPython(resolved: ResolvedActorSchema): string {
  const fnName = `run_${toPythonIdentifier(resolved.meta.slug)}`;
  const modelName = `${pascalCase(resolved.meta.slug)}Input`;
  const fields = mappableFields(resolved.inputSchema);

  const modelFields = fields
    .map(({ name, field, required }) => `    ${name}: ${pyFieldAnnotation(field, required)} = ${pyFieldExpr(field, required)}`)
    .join('\n');

  const payloadLines = fields.map(({ name, required }) => (required ? `        "${name}": ${name},` : `        **({"${name}": ${name}} if ${name} is not None else {}),`)).join('\n');

  // Required-first: Python function signatures reject a non-default param after a defaulted one.
  const paramList = mappableFieldsForPythonSignature(resolved.inputSchema)
    .map(({ name, field, required }) => `${name}: ${pyFieldAnnotation(field, required)}${required ? '' : ' = None'}`)
    .join(', ');

  return `"""Auto-generated by delta-registry-website/lib/schema-generator — do not hand-edit.
Source: Apify actor '${resolved.meta.slug}' (${resolved.inputSchemaSource === 'local-file' ? 'local .actor/input_schema.json' : 'live Apify API'}), generated ${new Date().toISOString().slice(0, 10)}.
Regenerate with: node generate-all.js
"""
import os
from typing import Optional

import requests
from pydantic import BaseModel, Field
from llama_index.core.tools import FunctionTool

APIFY_ACTOR_ID = ${pyStr(resolved.meta.apifyActorId)}  # stefano_seggio/${resolved.meta.slug}
APIFY_RUN_SYNC_URL = f"https://api.apify.com/v2/acts/{APIFY_ACTOR_ID}/run-sync-get-dataset-items"


class ${modelName}(BaseModel):
    """Mirrors ${resolved.meta.slug}'s real .actor/input_schema.json field-for-field."""

${modelFields || '    pass'}


def ${fnName}(${paramList}) -> list[dict]:
    """${resolved.description}"""
    token = os.environ["APIFY_TOKEN"]
    payload = {
${payloadLines}
    }
    resp = requests.post(
        APIFY_RUN_SYNC_URL,
        params={"token": token},
        json=payload,
        timeout=${APIFY_TIMEOUT_SECS},  # Apify's real run-sync-get-dataset-items cap is 300s
    )
    resp.raise_for_status()
    return resp.json()


${fnName}_tool = FunctionTool.from_defaults(
    fn=${fnName},
    name=${pyStr(resolved.meta.slug)},
    description=${pyStr(resolved.description)},
    fn_schema=${modelName},
)
`;
}

function pascalCase(slug: string): string {
  return slug.split('-').map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join('');
}
